apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner-wrapper
spec:
  interval: 1h
  releaseName: nfs-subdir-external-provisioner-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      version: 1.3.0
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  values:
    optional: true
    name: nfs-subdir-external-provisioner
    spec:
      interval: 1h
      releaseName: nfs-subdir-external-provisioner
      targetNamespace: kube-nfs
      install:
        createNamespace: true
      chart:
        spec:
          chart: deploy/helm
          version: 3.0.0
          sourceRef:
            kind: GitRepository
            name: nfs-subdir-external-provisioner
          interval: 1h
    template:
      nfs:
        server: "{ var:server }"
        path: "{ var:path }"
      storageClass:
        defaultClass: true
        accessModes: "{ var:accessMode }"
    defaults:
      accessMode: ReadWriteMany
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: nfs
      targetPath: config
