apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner-wrapper
spec:
  interval: 1h
  releaseName: nfs-subdir-external-provisioner-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  values:
    name: nfs-subdir-external-provisioner
    spec:
      interval: 1h
      releaseName: nfs-subdir-external-provisioner
      targetNamespace: kube-nfs
      install:
        createNamespace: true
      chart:
        spec:
          chart: nfs-subdir-external-provisioner
          version: 4.0.13
          sourceRef:
            kind: HelmRepository
            name: nfs-subdir-external-provisioner
          interval: 1h
    template:
      nfs:
        server: "{ var:server }"
        path: "{ var:path }"
        mountOptions: "{ var:mountOptions }"
      storageClass:
        create: true
        name: "{ var:storageClassName }"
        defaultClass: "{ var:defaultClass }"
        accessModes: "{ var:accessMode }"
        reclaimPolicy: "{ var:reclaimPolicy }"
        archiveOnDelete: "{ var:archiveOnDelete }"
    defaults:
      mountOptions: ""
      accessMode: ReadWriteMany
      defaultClass: false
      reclaimPolicy: Delete
      archiveOnDelete: true
    required: true
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: nfs
      targetPath: config
      optional: true
