vars:
  - http:
      url: https://github.com/samber/awesome-prometheus-alerts/raw/refs/tags/2026-07-26.1/dist/rules/cilium/embedded-exporter.yml
    targetPath: rules.cilium
    when: "'operator.victoriametrics.com' in apigroups"

deployments:
  - path: namespace
    waitReadiness: true
  - path: helm
  - barrier: true
    waitReadinessObjects:
      - kind: CustomResourceDefinition
        name: ciliumnetworkpolicies.cilium.io
  - path: networkpolicies
{% if config.base.cilium.loadbalancer.enabled | default(false) %}
  - path: loadbalancer
{% endif %}
  - path: metrics
    when: "'operator.victoriametrics.com' in apigroups"
