---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudnative-pg
  updatePolicy:
    updateMode: "Off"
