---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unifi-ap-exporter-resources
  namespace: flux
spec:
  force: false
  interval: 30m0s
  path: ./manifests/unifi-ap-exporter/resources
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
    - name: cluster
