apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-rendered.yaml

{% if 'ip' in config.base.ingress %}
patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: haproxy-ingress
        namespace: ingress
      spec:
        allocateLoadBalancerNodePorts: false
{% endif %}
