apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: haproxy
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  rules:
  - host: ${hostname}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: zigbee2mqtt
            port:
              number: 8080
      - path: /api
        pathType: ImplementationSpecific
        backend:
          service:
            name: zigbee2mqtt
            port:
              number: 8080
      - path: /outpost.goauthentik.io
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 80
  tls:
  - hosts:
    - ${hostname}
    secretName: zigbee2mqtt-tls
