---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: zigbee2mqtt
  updatePolicy:
    updateMode: "Off"
