apiVersion: v1
kind: Secret
metadata:
  name: gitea
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:uWDG7Q==,iv:phSrlcJyC88t6C8bRW+RHugKj4nEy2E4rns+lDem4A4=,tag:E0D7lhStlvHr0SztSgk75w==,type:str]
  hostname: ENC[AES256_GCM,data:ZTqZdl+LcSJKOS2vyuXKZao=,iv:0K6jm8pwwqx0Hb/emdr6bRjDLWW5NGV1sFy4wYQQc+U=,tag:pnajRMG7EMu7p5t+WwMZiQ==,type:str]
  adminpassword: ENC[AES256_GCM,data:FeosTOk8DTYysrGlajU=,iv:NjaOtRmNVV7x+zd5ugtVxYUdE9cxjaNl3Ov0ltvi5Qw=,tag:aX7UFVtwvDeVQaFy5DLDMw==,type:str]
  oauthkey: ENC[AES256_GCM,data:lO3DiWVKoFXemGQhIDDXmLPPDaT9m7eDcsllvUqrvWyG9mvMoUKjrg==,iv:rmaKVZ0EazkD5FdozUk67HXybIHbyGiIEPsL1ALaUWY=,tag:sIQHkmW0o4wFKB2sy5exyg==,type:str]
  oauthsecret: ENC[AES256_GCM,data:IgOeKpWtp2SGBGFlf3WSCMsXWCinm1yMeLn0uEM4jRdSbF2iOK7BiZHbeTMPKmzuCjBGPrxUoOchZ2Z6q7p2CAe4ET26xq0wZSl7pTnZL8jFJnqABqtb8v0HzkxynB3axDj1D2hC2kwtxMKZm1UnmjlkgUE6zUGrEEnKBLX/ZJg=,iv:z/fWCF7nscO9WOnptSvHaKOSE0eVGm0B1PGufr3PRVo=,tag:puGQyQ1XtBes8yIsIiUyFg==,type:str]
  oauthdiscover: ENC[AES256_GCM,data:5lpu9hGwrNJ2mWq3afCgFWkshWjrCSiO6DGg5zC9urwhVfCGOzCjOwabRxcoon8e+Y1eXShszRak6iJikB93nANaypHqeiFQDvpo1L2x2w==,iv:7CL6NVLYJWM6h+6WBrBnRbxayS/sDD/AbATh6ysItPA=,tag:TSeuBEkzhXALFUsiHlRSvQ==,type:str]
  smtphost: ENC[AES256_GCM,data:H1IDVkTIo7B2FJBmTORmnReb,iv:IWThRfpTXOr9hqfBvTfQXmbmoUXfKRcI8zfJIGRt9Is=,tag:ONH+OJcIyN+zV93BmTyduQ==,type:str]
  smtpuser: ENC[AES256_GCM,data:2oW8baJrwc6zyRzjBZkQP8k4uA==,iv:EFzXva8wOJLfRcDgdTcxLGX7MgwH325x/e6Rxp5g9Qo=,tag:4xVdR6bklsymKDvsYcgthw==,type:str]
  smtppassword: ENC[AES256_GCM,data:wiyP8UHeoPXkvdWpgkE=,iv:/YgLBPRso/PCrYa78k8LUbwTBdeWVZm8lQP3IvvP9nk=,tag:qJ0F1z1D0O2TxXOWI17Fwg==,type:str]
  smtpfrom: ENC[AES256_GCM,data:/5ieB++Y2W6SHTy9xNUw7/qqu4xI3yslSBld,iv:YApBrA4enrh6aABbT8PuvBMgqly/qItovmnGWXKVyc4=,tag:eQkq9oqqy/QTsTuNDjZM5w==,type:str]
  smtpenvelope: ENC[AES256_GCM,data:srtTqPzMgHjZTtPr8dpuI5mmMO0n,iv:nKoij4t0lDG4W1HWMfavLXhgezt7ArosUrT1q5nD2G4=,tag:2AADDBN+oABcpS9aHHe9vw==,type:str]
  backupusername: ENC[AES256_GCM,data:8Hmz/yeJcs8=,iv:wrswwozMXMI8eLVTsVcut71xeE3SFTOSCyOUpDj5isU=,tag:qM+7YRBrcu9n7WSz5TqHaw==,type:str]
  backuppassword: ENC[AES256_GCM,data:TvOfmiPvX3TQQNg8,iv:1WpSrxZznYYUawjCg3CWzNkfoSq8zD4rsn0Db5NUlWE=,tag:7aR1/X54Dr3EkHVLXnNcRw==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:eG+plZKNkDBOH/8xBzo=,iv:tQae9qtVW6pqBz6FoaEaPMfszKXCB+bahwdeUSOtSls=,tag:OkZmYo0vZWKsCnPPlshuaQ==,type:str]
  backuphost: ENC[AES256_GCM,data:bWf5re/FscCwtqk4yjj6KnaqvH9V1BBGgvmnpmcJ,iv:VmNO9Y9JVuRhXywg3OdijBEWbwDlgcHaqrdxkXJZ934=,tag:ec05sa0M6D5HmyyJ74rl/Q==,type:str]
  backupurl: ENC[AES256_GCM,data:zXiuKwHCm3dKA3qBoYCkSutv7NYxtvlQNle7RmPj+nAmzkZxVNaVM8tw/KgJpcF1ux9i,iv:ubgb01waA+6oKG+sW58UjtkXfmvUMWXJEcgx2LySnjk=,tag:2sGRVP9VZL3W+/hdFOMrnQ==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bjA1Q0NOUUFqVGV3aUxZ
        U2ZKSVZUKytKZEFYRVY5NU9Zc2Y3ZUpyM3pFCnZyZHFzTmZvWDdBS2NZSFlpak5X
        eUNxcjM5aWlNbm5LQkIyV3lTU2x5T2MKLS0tIFd3UnpLbmpsSHZWWFE1TC9jSldy
        VWxScWJVbXc1dUphZDVaYUtSeVdyWGcKqLOJVJJzhs0z9PfrPuJY/yWXLv7LbLr5
        62u5LIM2cabBK/s2GXVCLvWVGkRkUQOVMI0fC3A8G5+SvaCpKLuuBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T11:29:14Z"
  mac: ENC[AES256_GCM,data:ACCAyZsGfGd8FuTY6rgMy0jtzVzElOS5bOU09KY1BrZJdF7537DVRyXmklmJ8j9tvtY5p/o8Fj1um8TQGesTulNg//bjlXkrPH9AkwcJsllr225vyTIaXaf1gQLBepLkYGzVqnx4ydnwXh7XvXRT+LTCwtWePL5J7hTL+6Onbac=,iv:EAp3H8wDf9H0n4PAQhv6o08Vh1hqLD1cqtUBr9cDm+w=,tag:26G9L1VnzWtWQeB4Fo4AwQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
