---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: postgresql
  namespace: nextcloud2
spec:
  affinity:
    nodeSelector:
      kubernetes.io/hostname: ${nodename}
  inheritedMetadata:
    annotations:
      volume.kubernetes.io/selected-node: ${nodename}
      k8up.io/backupcommand: sh -c 'PGDATABASE="nextcloud2" pg_dump --clean'
      k8up.io/file-extension: .sql
  instances: 1
  storage:
    size: 5Gi
    storageClass: ssd
  bootstrap:
    initdb:
      database: nextcloud2
  monitoring:
    enablePodMonitor: true
  enablePDB: false
