---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: unifi-controller
  namespace: unifi-controller
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unifi-controller
  updatePolicy:
    updateMode: "Off"
