apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux
spec:
  interval: 1h
  releaseName: nfs-subdir-external-provisioner
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
      interval: 1h
  values:
    storageClass:
      create: true
      name: nfs
      defaultClass: true
      accessModes: ReadWriteMany
      reclaimPolicy: Delete
      archiveOnDelete: true
    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
  valuesFrom:
    - kind: Secret
      name: cluster-info
      valuesKey: nfs.server
      targetPath: nfs.server
    - kind: Secret
      name: cluster-info
      valuesKey: nfs.path
      targetPath: nfs.path
