apiVersion: v1
kind: Secret
metadata:
    name: cluster-info
    namespace: flux
type: Opaque
stringData:
    adminEmail: ENC[AES256_GCM,data:UXgn9VsqUPore9VXagzy8OaNbA==,iv:hxC/NbpqM4d9wxVZJvhgvQd2J0+h1NnvqCxOOi37Vtw=,tag:dF0ybMHIRVZvdIQD5eOV6w==,type:str]
    apiAddress: ENC[AES256_GCM,data:sgX5McCwJWOkk+lfvQ==,iv:6FR2a819VCEDicbXlGN/TddXIzx5JzC3hPqB+z9xUng=,tag:37Y5Sv7tfRoMkkJNOMXehQ==,type:str]
    nfsServer: ENC[AES256_GCM,data:7XP+Yjc2kAjGJNIt,iv:wNjJKLEi+eeNhLP74ovSmIyBofcTcdFVd02q2pHVBnc=,tag:MAJzNmGr8NawODhmmhAJKQ==,type:str]
    nfsPath: ENC[AES256_GCM,data:td/yoBRixVX0D50m4Co=,iv:qs217CWhsOJpkts0yv50IBW5d5bU/NyVIgRl60+jXuM=,tag:y9cFYFBxZSqQtnOQBm49qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-03T11:35:03Z"
    mac: ENC[AES256_GCM,data:TixL818sEhAMO50nGmRz9lAqqphvXzgryaNMwmWJeG0Blmblt7mFtk/OMVT9x3e8Q4cTJaGZe69Oir933AWMoygmvOp7/k7RvQHFlVeV+MxVgUuW3n9+he2C5ftxoA6KgpWzDFnl9vw86FMoDs3KMPqUId68RM39uy1TXzgmBpg=,iv:+w+2te5lnNlgCCNOxD0OWRQIg4OdGZsAyMe381MqLoI=,tag:+3Ze5O2uCVfx5PFKR9RwbA==,type:str]
    pgp:
        - created_at: "2023-05-03T11:35:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3AQ//YCog2SX4kuNEsVIuAglvgw/g6m1m0mkRnu0lAI/SLB4p
            xaumswsw7iqiykzFhw8m2A8fcA19OaCm/KzKwZUqvgGkNq5YV1sPah/2nU1+wEVW
            +xHNigrEoQM703/P5A1hH2YS68MqUG5LTCMciaqgg/gC6mpfTXGhC3CeGzIKdgWu
            Q6TVqEagGPzie8Rc3FFK9hXn7pKAcCYhTCjOMYOumGWEUrIeE47ssXpjQ3xYvhAF
            Q2jcRV8qkLpBSOg9ctUmgOD5hRC8rLsH5OakJqzPHfqGExuGPWVhiC6lI0vvSK+f
            GqdaInQ0KTJ6xgC7R93CyYVopwJ104E9MJW+4Tht7XRSHE6dESqbTbgIAp/wmiG2
            WbM/bZVSIwg1JrVU8cxeVncS4EHuGufmjMRzh88ExEEGmkwtkaaTZQomJxOgKy+H
            u/t3UpPIr7r8JCnU+lO9TuY80kzrBS/4lyLSI/dYu7/Bu/fNs1B+wpNNLKoOSZOD
            Z7rj5rOqQ74oLUEv2aTiTf7U0zIdNCZyVg0ks5/c45Ed6c1w2W8ALA2MdtQYsbzA
            TPWg7Dhry5jwS8Bg6mDp1R6lLpP+K77WcMsYniUOkBktLKXOVIu/9itCMdlCr3bF
            RJFd0jULSEt6DVa/R56pVxcPZZ6VqqAkuZc2UjFjZPXs2+F/6QQ9MDDszO/EJHfS
            XgFKAzN4BINDknADu2LEA820XhpN4esNkiM3eeKUPRhEP7dmS7S5L4PfFhCTqmCJ
            ODnLywT2izbMhaEDIWK/G/v/L+acZXj+E7ksmF5hW1VfjVaJLeETWJF3dvPeQuo=
            =TILJ
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
