apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - cluster-info.yaml

  - ../../base

  - vaultwarden-values.yaml
  - vaultwarden.yaml

  - netbox-values.yaml
  - netbox.yaml
