apiVersion: v1
kind: Secret
metadata:
    name: netbox-openid
    namespace: netbox
type: Opaque
stringData:
    openid.yaml: ENC[AES256_GCM,data:Zl+L0gcepE5FLPpZgEMnjlYFY14ZGtmHwnr1G+yaeszszxuZIBk0TKN6qmpKFMrxo3DUD0iFFSCoCPW2zIpJvd5kOjk6WkwNNeqQ74UBlkNlz/r0MorUcC/rd0hoZsCi6yvYp3ZZDbBnNF7oy6wlFEPmIFOeYYmzwgnbKkyBi0NYSWNPYsknvXTn9OnIxCNKQeCvW4Jbg6jMVHBd9RNtpac/2uzTrMylZO/sUPtjNYB8aBNmSkIbnFLSi90AkDBDl6Oli5LJZziGhM87oj9VC7mogQQuoZmhop/xQ42zjU0d7GXbvr4pZpON0l5LEcYoGW550JKNne6e/nY6d5EQAJuh6NtLY/yVb5QvZ9Rlf0xlxJslDi6NuCD/qiZGARP9Me1XBbsjMF6w5PgFMKrWCSuNSWUO7DjJw5ndOYNDZKwpQcZPkw==,iv:jkTpNZgzl7/fExL0UJPxjkmV5JBhBace/PdexkDJOuM=,tag:zRSEV9A/ZoMoNB75wzWWZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-10T08:23:13Z"
    mac: ENC[AES256_GCM,data:89JnFz7/tM1fgsxvrpEomMJaKsv2i2+T/xE8ycT9lLYNNTltLIKl+Ob/pr70GMg+yTeXzY06U1SFEprOJ2pQzQ7pszRPk1bMnj2eg5z1Y6SG83qWlwq0SpQ/p6BgkJdIy23cprjtbc/C81mdPrJmPOc9nlLR4MuAdI0YXShAMBs=,iv:JL/6cnQJz++ZcQx98/6lzQN5RzTYe8hR+9pZ0qXQHRk=,tag:agQoRtGV346INbD2FSJnCQ==,type:str]
    pgp:
        - created_at: "2023-05-10T08:23:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3AQ/9G5iELW+m8x+u84qBTW29A2nnwOBMC1l/MH+1eFpejhdw
            IqhLPUWLf7WOzRz7cKs0SKdIm6TtFTRlSeGxH9juQHzZV5QTRSwY17RgpWTLjdrG
            lKcO5QGLooG8UqwNhn+xMtmafPQC2v1py2JEs4RHX9U+l8ptGQf6v+mrylxlHhMy
            ngeCdulKA/IN5tqabTKwGqOKIJSAdzukh7V9d/w3NtUxkQmu8YQLkvE40GcnnhmI
            0q6H4k3WHKA06ILNss6zty7rskv90uDJQNKf2uon5uFMfOYiUqmpBzAUXWSpenAE
            pkwumwZgjway7VDYfAN4ivlipmG0KZsRE4bFq/qqkOyhMDc/fEQXViH09qrdc82d
            NsOg7U6QrmeXM2eRmQC6jxa3ppdi+pFvez8dOv9JU2YuE/tFMU1XdN3exN1mQLei
            OTGg2gsRNmjKuwIbxGe/cDc056EJIrlzaKm7diR38UdZUjllX1Clts2PVOh2qB3H
            1IdtjUnv9wrrHNQ6wevPzsg5ajxWUBCBiSzJBHvQBA/3WpeUA7THZr21mA+jvVSL
            Il3VPgQDHBFykweNi3M60MBiouFG0toiCpdVszCQ0oGolhKh2zw1JdfbtZwkJ45Y
            awiy+ry/LcsDOmHAG1y/UaLAT7XQaCJG0WK4iO0SirLFjMbYu9XHRjDUbRE/KuXS
            XAGAlOG10HNGEcktNqXta4YxAQF2rFaiGLDYTb0NYjdUuw6xNwDzxse3TKyuyha0
            6tNsN1OT1HRhZcKk/pu1Ll3kKoq9U31MietID9/DbygTWfkLwQib0AKUUmo3
            =ipyc
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
