apiVersion: v1
kind: Secret
metadata:
    name: netbox-values
    namespace: flux
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:9J9eIzwJ,iv:9Tm1TNOJj+t/IkVDKWB3FGmvQ3pIgz1FMa3JQvon830=,tag:zkQ1silMinM5RXUb8k8D8g==,type:str]
    namespace: ENC[AES256_GCM,data:9cSYt2Hs,iv:SBISJ8e4vDDykLe/QmtkkX78mKHjVHUsn5eyb60Z6Vo=,tag:DQV4XH3O5kWk7MRY4/+JPg==,type:str]
    hostname: ENC[AES256_GCM,data:sHZ7f8TdnAp+5yPpllQCBmE=,iv:me4tnNvKcME+zmrEpVB9xPHTZxEywAnq6XYNBOlUQDg=,tag:iy8C3s83/xlRZcVWrtl+Lg==,type:str]
    issuer: ENC[AES256_GCM,data:IM6Hlca+Jpgc+sSZOugB2+sWEw==,iv:uiSTtW2hy9zAwUcn6tXHKW2u1ZF8F6zOpuy5ZLpIowQ=,tag:mjrI9ELEFkdkd/135Qx+kg==,type:str]
    values: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-03T13:50:25Z"
    mac: ENC[AES256_GCM,data:n727ofZ+pF2bJfw/G6zakKi7StZin0DFcIsN+x9Vkzd/qeHQZ/PH7Nnj14lQPl6pyfPuPcYe+DED4A3Bc6soN8mdSgcNuwXpppVt7x9BK4W+HYoZ0eZA9iR42Qgo2rQkFIxN5DwHIGzi1ELJQfTtT8zFPSnP4uFnJyMJKFOeWyM=,iv:17wF8Txtjz4K4E7RS9oRR6aAq/1jmru/ADKQE0HKkS0=,tag:bR0kJ56QplE9sRQscCSukg==,type:str]
    pgp:
        - created_at: "2023-05-03T13:50:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3ARAAwMoZ1HEK8xcpAxqyqnFwTxhzOERs8LUqLu3L4UT44UWA
            k/UL9F0NDIoxdVxSiKKp+yVXxUjKG6feeBkKrmQsIr3url+WegBEzoSp+x9xpuDK
            aQUy/Q+zbQwUiJC8xv1RHjgkIId6lPgMhVRjIVNycqrSmioXL7aBO3eRIjXeZaC+
            XY59P5kKJ/vIwIvNf5aBZmbRnwUX6Rq40Yuy1JnO0+RpcVyZkXL0Cl631nMJRVec
            HcwVj8xXmtMBi58zwbOI/axSsPnUdiPDVC9mF7uhYE8O+bqJnIuUHyFhFRlLEjmd
            iK1s1g5ttyap7FWkBVg3Ft6W/53vRMU6AoOS6A63L96bysNlB7OUoe9GsjMgHHXT
            7S58AaQ1Kl8CJnEZpp3zHBWKwqj6wZRxbNy1bKZUf/qsQ68hY3+kdwnJBESGlq6F
            ++dXQ6rDGZAp1T5AKee/kfCt05dkFN3MgDmER5oVByWEE9GsakRtU53OPhYWWGpr
            +27cnf8GJ4wtobPd1YxN5b0Znr10IV1iDpH2CSZT/TmvSS9dk6XSox21PkM4rjEk
            rZPFgz4Jpo7pS+KwHxj/Z7fQEJ/vjGzSSUQsMmICeRygf9gea50kcOKsPNYA3t0M
            7e83/ODrCjnnt4TzAPvDTHr/juZ63CsgcKidtxIRtFciFbK7FOJt2UKjfxPM0YLS
            XgEucM94+8X2npe0h0kqndYXsYPqfaIyPzEbuKAvQIoZ18Jig+debx3e/SjBzq0n
            4DYZaPAsf6fmYXvwO41IYhXzwf5lBYKP6GTQaUdQJl2C3L4a2RMl1CL8GMFiWds=
            =G06e
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
