apiVersion: v1
kind: Secret
metadata:
    name: netbox-values
    namespace: flux
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:PAwe4q0A,iv:cmoOU0Kge7DvSmUD4l+11EeUepM9hV9ckRvzcTrjV0E=,tag:Ld9qpohi3GO1V/p74W5zFw==,type:str]
    namespace: ENC[AES256_GCM,data:dUzrG8QF,iv:ZX9M6ir6LMS4ncvV7T/is4Lle2wD9DmNqytcZ3Y6uqc=,tag:D3KEo618wFp4DUR94TVCyg==,type:str]
    hostname: ENC[AES256_GCM,data:B5Rxzt+QyI4/giNUIzFrQfM=,iv:5hnvVnV36nHfROqm0hUg/3W8MXw9xPu6tArR+SGr1Eg=,tag:Sk73DZYoeGZHSK/Dh1vGXA==,type:str]
    issuer: ENC[AES256_GCM,data:elvMWSc3JQO47jemyxjW7HZB7A==,iv:DKanNdPYNHBS0bs+LiJyLy9+UF+EFtPhxc7B0Wa0bow=,tag:l5YN4SyKiCOWFlvr1dpErw==,type:str]
    values: ENC[AES256_GCM,data:azCzBSFmrmGPnPUe95yda9olUozseZv2uFPQPW1+yCSM8KHupGgQVc3Fowi2REQaUn5bq28liNTVQQgqQXfqJZTBi2U5q0NO6v8pDaNExicMh02T/LgETpexxuwRMCPe2JW2DhCBgH5A5QrwKznPEakWYbJ2c6CIvnaKTZOzAvmWKc0HT8cQkrGwFpNj3jnI2c2tfvN1c6Y86/O/vKsbWRUhglfa,iv:5Di0bliKJ2aeK+nlPB7/Sw2yLjwS+l1oNFfLyDKlwNs=,tag:QoHJ8JtodjHUsNDbyDZoRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-10T08:14:27Z"
    mac: ENC[AES256_GCM,data:OJAmzw3yZKMwEZ9TKMjngtcNgDN9qvW1yf5LQlpkQrCglFjdNGs7YeyEox6PtHXEK2MMTYQbPzRijeNw7XHD3DtUyC8JoCZ0L5xm3KKwhXu9eRiSlx1niqiBu3JhKROQ8V14BMY4E0z6dWovJVNHLKkVoIWtoqP1OvDuviAUWZw=,iv:R83g8o6OZOWcGSUtV4QzncKXWoRxKP5ZirbSbzytQIk=,tag:E6vBCg/38XLk+uT9WpYTZQ==,type:str]
    pgp:
        - created_at: "2023-05-10T08:14:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3AQ/+Jd9HN+8smYAiM04jBak9mPAlhwD7Fp3lA+52G1Q8nsmL
            0sXnxKGEnITNxwsNhuK7JQdUmq/mngO7MEPSt+poCFnkxRjkhQiJeiTsbyKChXAE
            dA0YRTJ5iigeOGbwZ6C64O/IdKwVCwpuxwG1IokvBK/v2+It9TeRGgEj83ZCwoF2
            veKaMDRXzpjOp9b4qrQLknmt578LkzRmoO08LtAuReyCNn8/hPmHQyJAKr5WVeRw
            h1Ln4OM/TEq3ObQXsRB1g/1VzgPUUAt5TauiCYvitAY70ljX3ZWmxxfq3vR3TayY
            ilGYMOjpjgz4SNQ0ceO00qFSItfzss2KkpRT29lx2uslzIaUC8f2KDe2k2m+LxAi
            ZR5tzVFCxR0E8A6LaT4mXlmHSmzA0l+JMWRLI6TP3rozw3fm1LyHik/ldD54BsQE
            gpGKNpiJmAMR1CpycL6uAzqTnjClReOXvTLxNQ2RFOxncBpsl33AWxM+OW4wSwpB
            8AlVA7CEeot/Vyf2tt+C+jPDzig4P9aXDW4hZPWHD2ldXkB/scpG87G5aBnD6bjv
            M0Urk2dteYYMvmGVIikh4NxsSNI5D26y+w3YzO6mO+negb3halUeaTBPgtAv5ONQ
            qF866pPZs7VwktSu+Zj+fRXkfCQsvRVMniP3RhzVSDEZpav5ulq6wLuTa66oXbLS
            XgE31/kKlpE26YU3+6mUQfXUUmQLtBsf81hyh0LSqFFAi9L1RqroPNsbv4hmdLG4
            qly+aEO7wi+Bfy4nPipnfPW2g7pEqXuIeJz8qPeQrrvHsUj9z4nG2xpbgiMAL9w=
            =6tg4
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
