apiVersion: v1
kind: Secret
metadata:
    name: netbox-values
    namespace: flux
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:Y8+fac0B,iv:ROS5NMoo2JMFl8dIPp+k/dJvgMzkCGWN1tuvfajJ/68=,tag:YHoCZA/0Xl63qN+J8TAyTg==,type:str]
    namespace: ENC[AES256_GCM,data:oSF/ThEY,iv:WaHigak5hZGdhBa5dxtwq7mmrYS0cAqI4hz4tih4IuI=,tag:fE5uZFuYjIGk10mqC3tvfQ==,type:str]
    hostname: ENC[AES256_GCM,data:GF90WcRYJWMrbv/EqaQsD98=,iv:uKLLb7+uhbmw7f0Q7+otM1qxW52v9n4O+MvK7xHugKI=,tag:r22ZCSVcn3csmMQzS2uQsg==,type:str]
    issuer: ENC[AES256_GCM,data:2TGmv27Uk6Hmpx2my/o1dwiLRw==,iv:Za59Lu1/EHzEoleAlhMFGOX3id4KKJONc+nB349jqrI=,tag:YOmzVRbYdb9w1xotQ7/hSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-03T13:48:38Z"
    mac: ENC[AES256_GCM,data:Wd1tVarpmDwLxn1cizkHHV7LE2Xs+KUGUVWRQUISTQsW/XKpObU/NDpsLIZIGQCG/roP4pkh15UM2rtwBCb9wZqq9tTSf4yJxIGJbcd3UXGeRC3mWPzhKpNxRJ13uILIa6asnweuLOPc1bxebEpMjk0xuCV0QfcLSRXwY5vVdtM=,iv:vHaPanUo6UfCOfB+1xLOmP2mm01hkfCwyXVB2nJME4M=,tag:z2SfKFwHeciSJtPNKX8iQQ==,type:str]
    pgp:
        - created_at: "2023-05-03T13:48:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3AQ//YJRbNb7Jmm8QykW8kVM5cthAqwdiAGfQCy6alcC5HwrP
            rQmqe4N23znchU1J4sgMKD9iO3UqzTECMlKxPPLAkEAi++48gH2R/hSq2GmQ0Vb4
            KU8acpujvCpo6XxGgQI4OJxn6rjPqWy5Hg3X8XeZPWAN/yuT+iBE7TmbwfApAq/s
            aPAZQ0Y9BO3hwNYCSQlY/0j50uulE46XT0PMsf6ZBIW9K5M9rmc2D+uzvvnFX/Jr
            AU4IBAOMm79ka8JS8pzO9iuTmCjl5JF3V7MjMaZWeDPpspVToJ8TNIDp5O3drcIG
            yDu87HaeprvNbtXmKBg0ljxw1ZNePcsLgqoFMRdwxXKRqCFaYTjpuxlB4ohNoYi5
            SG0UqIGw5vVEQHnlYl8fo+NZNjBQso1XDCc2liLgdpaSHycqgbFKw8riK6gdqqFq
            tGShl/UwODm5LS5Apunw6DkYisy+DnuCXGS3DiyHmNbJGxoyMt6PYLskJ22XVv7E
            Zemxy9qYn7UMm668F4lDsvL5jkcWKeykAVsxRt7gMKJMaHkuDs1k0CjMK14chMf/
            Tp0QKk8eilCyMDMaQruEUi1yK/0P+DNYVvTsP0t1THmTNRlxh92qRLqJZYKStg2d
            5qr/eJwxaXO+n6XUtN11Dn2KKnBniLjCU9etVKjjqvqmppGzCNG9iSsGYRtrRQHS
            XgHiqOlUPwIypxq+2NnvBuF9oTNteGF8k/BQTpyVxz1gvQKUTEvhbBWAyqffVMO7
            KVpUE50kr/tUHcdBG0lqO9lDIZNKnRB18Z1GZ/I9yJp/3vrRl0CHcnaBsMvTJLY=
            =uLKD
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
