apiVersion: v1
kind: Secret
metadata:
    name: nfs-values
    namespace: flux
type: Opaque
stringData:
    nfs.server: ENC[AES256_GCM,data:mfCasKSJ4JX1ZK0f,iv:WoHlAVbtVjKskd2k3YE0h/zKCaMxDBOcmXs9aMJ7JtU=,tag:pNdSU6gbUlUzh5lTB6S7PQ==,type:str]
    nfs.path: ENC[AES256_GCM,data:KR//kLdOYxmu0EIl6vg=,iv:o/spGck7FYr2tLmhLNjy27j2raHwJanTcQUW+XnN1Og=,tag:3LDoWp+9peT8i6mbsrQVHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-03T09:40:40Z"
    mac: ENC[AES256_GCM,data:3GcWBcQ0narEl6imeLhEx1R1VzrucmLL0t7rb/oQHjnDO8DdYWLwGCC0KxY3+F2EdHQVmPaPG14BRIQmpTJL1KS38Fi26Uzq2hoJqecXsNBpgB2LpcbDfJrH5QvLYJ0q7R6zvkQO83ZStsPbRE4aKGIZzZLjBKeIrFH4N6D5SdY=,iv:kr/iDC+IQGZ2aPQjdHBjnpu8pLJXN5JgKkBpTd6656Y=,tag:dgzDCAFKhDXWDHdF/Kw3cw==,type:str]
    pgp:
        - created_at: "2023-05-03T09:40:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3AQ//QtyvkZDt3djOOUZb2MjYVzdWUW6IgAhvCLPMNpAf2smp
            v9I+mj8GnBbOBHPCXZObXs/QU04K+TFxgl6xbYBV7ppYFSbgytcUAHIr2EBx29TM
            HrzphAA1y7VcoW4R8qK2xTiRc5codRnRksja3Om4bolqO2EzT7B6/JHcj85FXxWS
            b9OYaHEw5Vb675Mrmfr1PuQKTYJBLff6QDBdBHNITx4ubjMwOaKqSyDu+IB0rAEe
            yPZJ55yEwhkQ208fjLAeiELsu16DeyEpH1bw+4uh2saDEj6AksETl4u4PY6Mz+Z1
            MdR93HNBkPYMVXVspCpgC0/UqsYZrWFRR72gea++7/ad3H1WXVuB3FFqExEEchn0
            VlizGX6QXSe4AqTdJJEVGXOcD5ySuFBiBXFiImKp8iIggsfeNVAm9itt9T7PlKh9
            LpaKVe6L4YuB1+FaaTKGFb8As5x51miglb4vY9dMnsE08hADr5hDLVLopvBhNHm1
            JBhbrGSIsxAlMz6MJKNclai/O6rG3j+V1P20hRSyLQNA+sDGTMt7Si+A12SOS12Q
            ZalwU3e/MpUqB/ANS1ZNzu+xONmQsRw0iRGznNw1ZUsZaP9uReIkp83NYDzRCCE2
            gCqC/lE/Yj7YSgPY0j1E2k8AVLO0Ilv7Si7GX8adBziSQqtdD8c24o/FnSq6UeLS
            XgE2npqAlvzivJCVrwTG/pkfNI6CcBJ0CwO6oFYr3NMBKSFyn/6kl3gqisGF1p3h
            JOHEZwxCXOUjZHf6KAkSD1n4GgRtehQ87ZFZjYIODFNdS/hbuv9vlVokS4YGbOY=
            =HZx1
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
