apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-values
    namespace: flux
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:29Bf780=,iv:pEhoQcv1V6fSF4DV4gCo290jiKrKMsrlOxsa7UANZ30=,tag:qrveEno0/ltbzIf/TUnraQ==,type:str]
    namespace: ENC[AES256_GCM,data:1/rzczbuhEmb,iv:cgb+FaSvmakd0/u+nOscAP6rBN9jCAL8m6LQ92vPW8U=,tag:EtkG/W0A177QU2V3VPx12Q==,type:str]
    hostname: ENC[AES256_GCM,data:pvML2R2ZdcpsI1wteVXY,iv:hFcCqm9GPaZSNTPtqKW3ib6hgKLBBpl13LGc1z1UAb4=,tag:uwu3my6Po7xpHYBS63PfxA==,type:str]
    issuer: ENC[AES256_GCM,data:HbDdOQ5/YqmNfEpHR8bAsNYJmg==,iv:+HFl0iBuAkLp7Xz5N8c1b9d71gvntkuXdyTZis5anqY=,tag:kk2QZLbNdPbgLdvPQHo2xQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-03T11:38:32Z"
    mac: ENC[AES256_GCM,data:o9p492FQH4jd2349V5NDJGeWazDr2cC3oFRD+pNP1rYSifLbGvtjswghDVejyXnbdILwifAeMoLVFwOqwfbU8JYPO60dD87WO1tefLDVKDeawnAn9fXSnEJgjGroRC/b/+FrZh7TtlbjRkCqyHEqfHj9Z3/kC7lAKKyFGRivYdE=,iv:ppMTA3ui+kRiN0M//AU8zy4gpkeO5jdWjDCONhCuKV4=,tag:IOnSezZWlLLX/K73vBiKQA==,type:str]
    pgp:
        - created_at: "2023-05-03T11:38:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3ARAArp2K7y0/rJjErLMfcuhznCzSH77J+h1iU0Y73lFezTIy
            GXEvMf3WiSc9xnVz9rVjUjLl8lybvWwist0KHFGDhqsMqnrUvnRaEad9T+8yAcSN
            pMhLTUKGEWJDZbizAW87Okz22/cmtvbo7HaQlL1I4SHoknds05hBibppDjwsnsN1
            LbL3JBO3hhev5CIeMyt3/LEVb/01fSRBng2/hyxXox3R/qlwnZaFNfrmWPHrQgTJ
            rx6HmX6g9U4XIBbHs30Cc515AtPOPgUmajk27aBGzI5HgjtuylHah1kR97M+9B5j
            4qTBU86VsEvSkMjHw2Su6EaBd4cKXIIUFqpA8OGWz5y3l6s3uzgVh+PwVQKQez/0
            h7QZZTfWTVGULN1AppXN6/VDjqkAtj3k0qbqVLvUdgL//AROTD9QImAN1LN6gUNv
            5pTHYLbxqEQevUsf+2vDs91K/U3YgjWKyblwlISNjqhB02OzkOSi2IPGJ0dLdlEb
            P3ZGV7tZDabHkMmAV1Xe4FphsoYAwSm0GtUPWzcLeWmjyMpp6bIdvyL5G2J7gatd
            EKByXDFgLOQQDbbMHPJNNFhUpr/zq9Ts0YtReuH7WSXMs4xUjJjRFKkppbgl22U6
            u128D7qE8vwFo+Htah6nvU624b1845qwjf/XBxIUnxCIgeFPjHoSRjrydqfFgcTS
            XgFF7I+ZXf5BpJJSiq69081t8fVaaX/Fhym4g2XWWYIqJ9PN3tAeEfika0KCh4uV
            INXP4/XDksWkrONMUEts+yOzDb0B+ngOconupua8xcFvmFYZZH4ecw6y2KOYfK4=
            =G4cl
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
