apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-values
    namespace: flux
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:JKVhbx6VDswFiQ4=,iv:lQ+0dKnHkzZ9rIujkmsLX0NGzIJmobT7hatHVnf2UPc=,tag:76qZ8BpSFy5Ql+wWrobQ6A==,type:str]
    namespace: ENC[AES256_GCM,data:H7VgYOS37up/QgQ=,iv:v3KVQ0mEx/OjNsA1iap59+JKHFFgKw8e826AtKq0xas=,tag:skrZ9yfQg+R6E/TAvUPfCg==,type:str]
    hostname: ENC[AES256_GCM,data:yP/41CgRcrGiYiOgjwmH,iv:fL2xMYjJXxs1H/ern9mNVrlwjdwF9ne20aTqJKMpQSM=,tag:swePtJUM3C9xC4JOdvHpvw==,type:str]
    issuer: ENC[AES256_GCM,data:knodYMcJt92bFSe8aB72nMVN2w==,iv:DiAPvfqybeyqb93rzMwXe0roIsw94R0Yeok9i5IoY94=,tag:GTXb0KeUG25kLHe3FpvoMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-03T13:56:01Z"
    mac: ENC[AES256_GCM,data:WQMAJXuQCw92gWVv7GCX/EYAoyXOw/gVLJA5AlfbFJ99U4X4m26P2GPHav1uAkqq2ih3zJRe25xlvZPL3kVUJbnPaF0nP5gMbiAjr5qFwbxV8tMZpXtMba9GKeZqzybOYvdRuo3nwtbG5Q5gTWu5eA8P+UhifwnMVheh8G0axdg=,iv:TC+BMFi/lQjjEBlZvbqq/wE0NBCVcNvXclB4iDg1mnk=,tag:4T9xVNGTmJ2OpW8l5V047g==,type:str]
    pgp:
        - created_at: "2023-05-03T13:56:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3ARAAs3HPJpm/sr/OHezaTQo0izPNltMfbQPTa3Uf6CGGwC4f
            KrYZ1WJiE6SNztseZjUAW0Z+jNYfmMnEFfLeUr30mq/R9iQ6jow2jE3MaZpUKlOP
            l/4p66EFXF0fQwvn2x5JuuvAYUiPbLa1USZ4pOUAgb2lUvmsSOVxpVuZ/gazvFTD
            Z3Zn/QUi1QtoI+jsFiFW6OrRcfMz/FiG5L1sa8JOmrtl4D6TFF2opU5SJEKClmXL
            5T07+cdf97b0lhGcXcKO6GHyTb6x9XSmV2rR6TYrVgDhuIBexQM5KiEs0/hD9jR1
            J3fAt9Rao9F8EwstxTEghsUKX6zFAxPaS4DtdDfjXOc432Q1NCUeiubYdkFg+7A4
            fZ6xsmtDwhcXkx0hl6Gft+2a/RwTU0UcfcNQO5tES4hcEhao+4sa4eZDfqC5nva5
            Sp1XWdS4SK43DfFwE3FKEeIBV68DIzmK8vn3H1tJSXAFCd6IDBc1arHpmjzznEHe
            Kcx8rxQw+ARAyBr4+01It6dZOJdBjRhKIS+H0/Jkm9iw3gcs7WGHvVSAt0DFvu8V
            j+7laJIH4YS2EGL6ZiB9fIkuwYEojF6pDotK1juqL5/7EWE8MNRVqFM/zGjglqMy
            cLhHl7+Tg8xiWLVXpDUsaq1k/Sg1mf0ZVCAEQFAgIMB3xiIaeE0KPx7ljMYRxB/S
            XgHs0FZDz3uNSnj7D0CaeG72lRfRXiHr7zaXX/3ZNpQfx9bVZeO/q+7y/6HbYiwB
            Qc7WJNy/i4bd3nlP0bDzPoi0nYGqriyIsA4JUcKJW6vdmUqWKbcilI3kkRSvoAg=
            =+6iq
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
