---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gs1200-exporter
  namespace: gs1200-exporter
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gs1200-exporter
  updatePolicy:
    updateMode: "Off"
