---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vertical-pod-autoscaler
  namespace: vertical-pod-autoscaler
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vertical-pod-autoscaler
  egress:
  # Kubernetes API
  - toEntities:
    - kube-apiserver
