---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rest-server
  namespace: rest-server
spec:
  groups:
  - name: Restic Server
    rules:
    - alert: NoBackup
      expr: time() - max_over_time(max by (repo) (timestamp(changes(rest_server_blob_write_total{type="snapshots"}[1h]) > 0))[7d:1h]) > (24*3600)
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "No backup for {{ $labels.repo }}"
        description: "The backup of repository {{ $labels.repo }} has not run today."
