---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rest-server
  namespace: rest-server
spec:
  groups:
  - name: Restic Server
    rules:
    - alert: BackupFailed
      expr: sum by (repo, user) (rate(rest_server_blob_write_total{type="snapshots"}[1d2h])) == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Backup failed for {{ $labels.repo }}"
        description: "The backup of repository {{ $labels.repo }} has failed today."
    - alert: NoBackup
      expr: count by( repo, user) (max_over_time(rest_server_blob_write_total{type="snapshots"}[7d] offset 26h)) unless count by(repo, user) (max_over_time(rest_server_blob_write_total{type="snapshots"}[26h]))
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "No backup for {{ $labels.repo }}"
        description: "The backup of repository {{ $labels.repo }} has not run today."
