apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: metrics-server
  namespace: kube-metrics-server
spec:
  interval: 1h
  url: https://github.com/kubernetes-sigs/metrics-server
  ref:
    tag: v0.5.0
