apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
  namespace: kube-metrics-server
spec:
  interval: 1h
  path: ./manifests/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: metrics-server
  targetNamespace: kube-metrics-server
  validation: client
  patchesJson6902:
  - target:
      kind: Deployment
      name: metrics-server
    patch:
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--kubelet-insecure-tls"
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
