apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${name}
  namespace: flux
spec:
  interval: 1h
  releaseName: ${name}
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: cert-manager
    - name: ingress-nginx
  chart:
    spec:
      chart: vaultwarden
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: ${name}
      interval: 1h
  targetNamespace: ${namespace}
  storageNamespace: ${namespace}
  values:
    vaultwarden:
      allowSignups: false
      admin:
        enabled: true
    ingress:
      enabled: true
      host: ${hostname}
      annotations:
        cert-manager.io/cluster-issuer: ${issuer}
        kubernetes.io/ingress.class: nginx
      tls:
        - secretName: ${name}-tls
          hosts:
            - ${hostname}
    persistence:
      enabled: true
      storageClass: "nfs"
    image:
      tag: "1.30.0"
    securityContext:
      readOnlyRootFilesystem: true
