apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qemu-guest-agent-wrapper
spec:
  interval: 1h
  releaseName: qemu-guest-agent-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  values:
    name: qemu-guest-agent
    configKey: qemu-guest-agent
    spec:
      interval: 1h
      releaseName: qemu-guest-agent
      targetNamespace: kube-qemu-guest-agent
      install:
        createNamespace: true
      chart:
        spec:
          chart: qemu-guest-agent
          version: 0.3.0
          sourceRef:
            kind: HelmRepository
            name: qemu-guest-agent
          interval: 1h
    template:
      nodeSelector:
        feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR: "true"
      securityContext:
        seccompProfile:
          type: RuntimeDefault
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: config
      targetPath: config
