deployments:
  - path: namespace
  - barrier: true
    waitReadinessObjects:
      - kind: Namespace
        name: cilium
  - path: helm
  - barrier: true
    waitReadinessObjects:
      - kind: CustomResourceDefinition
        name: ciliumnetworkpolicies.cilium.io
  - path: networkpolicies
{% if config.loadbalancer.enabled | default(false) %}
  - path: loadbalancer
{% endif %}
