apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: gitea-{{ app.name }}
type: Opaque
stringData:
  username: "{{ config.base.k8up.username | urlencode }}"
  password: "{{ config.base.k8up.password | urlencode }}"
