apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  interval: 1h
  releaseName: node-exporter
  targetNamespace: kube-node-exporter
  install:
    createNamespace: true
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: node-exporter
      interval: 1h
  values: {}
