apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  interval: 1h
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: node-exporter
      interval: 1h
  releaseName: node-exporter
  targetNamespace: kube-system
  values:
    rbac:
      create: true
      pspEnabled: false
