---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: local
  namespace: storage
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storage-local-local-path-provisioner
  updatePolicy:
    updateMode: "Off"
