apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux
spec:
  interval: 1h
  releaseName: cilium
  targetNamespace: cilium
  storageNamespace: cilium
  chart:
    spec:
      chart: cilium
      version: v1.14.3
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
