apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom
  namespace: prometheus
spec:
  groups:
  - name: apt
    rules:
    - alert: AptAutoremovePending
      expr: apt_autoremove_pending > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "There are {{ $value }} unused packages on {{ $labels.instance }}"
    - alert: NodeRequiresReboot
      expr: node_reboot_required > 0
      for: 4h
      labels:
        severity: info
      annotations:
        summary: Host requires reboot (instance {{ $labels.instance }})
  - name: postfix
    rules:
    - alert: PostfixHighQueueSize
      expr: sum by(instance) (postfix_showq_message_size_bytes_count) > 30
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Postfix message size is high (instance {{ $labels.instance }})
        description: "The total size of messages in the Postfix queue on {{ $labels.instance }} is high (> 30)"
