apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: custom
  namespace: prometheus
spec:
  staticConfigs:
    - labels:
        job: node-exporter
        node: ${scrapehostname}
      targets:
        - ${scrapefqdn}:9100
    - labels:
        job: postfix
        node: ${scrapehostname}
      targets:
        - ${scrapefqdn}:9154
