---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-operator
  namespace: prometheus
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus-operator
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kube-state-metrics
  namespace: prometheus
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus-kube-state-metrics
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: grafana
  namespace: prometheus
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus-grafana
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus
  namespace: prometheus
spec:
  targetRef:
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: prometheus
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: alertmanager
  namespace: prometheus
spec:
  targetRef:
    apiVersion: monitoring.coreos.com/v1
    kind: Alertmanager
    name: prometheus
  updatePolicy:
    updateMode: "Off"
