apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant-wrapper
spec:
  interval: 1h
  releaseName: home-assistant-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  dependsOn:
    - name: nfs-subdir-external-provisioner-wrapper
    - name: cert-manager
    - name: clusterissuers
  values:
    name: home-assistant
    spec:
      interval: 1h
      releaseName: unnamed-home-assistant
      targetNamespace: unnamed-home-assistant
      install:
        createNamespace: true
      chart:
        spec:
          chart: home-assistant
          version: 7.4.0
          sourceRef:
            kind: HelmRepository
            name: home-assistant
          interval: 1h
    defaults:
      issuer: letsencrypt-staging
      timezone: Europe/Amsterdam
      hostNetwork: false
      privileged: false
    template:
      env:
        TZ: "{ var:timezone }"
      persistence:
        config:
          enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "{ var:issuer }"
          nginx.org/websocket-services: "{ var:name }"
        hosts:
          - host: "{ var:host }"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - "{ var:host }"
            secretName: nextcloud-tls
      hostNetwork: "{ var:hostNetwork }"
      securityContext:
        privileged: false
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: home-assistant
      targetPath: config
      optional: true
