---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: application
      version: 6.5.0
      sourceRef:
        kind: HelmRepository
        name: unpoller
      interval: 1h
  releaseName: unpoller
  targetNamespace: unpoller
  storageNamespace: unpoller
  valuesFrom:
    - kind: ConfigMap
      name: unpoller
    - kind: Secret
      name: unpoller
      valuesKey: nodename
      targetPath: deployment.nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: unpoller
      valuesKey: username
      targetPath: deployment.env.UP_UNIFI_DEFAULT_USER.value
    - kind: Secret
      name: unpoller
      valuesKey: password
      targetPath: deployment.env.UP_UNIFI_DEFAULT_PASS.value
