---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unpoller
  namespace: flux
data:
  values.yaml: |
    applicationName: unpoller
    deployment:
      image:
        repository: ghcr.io/unpoller/unpoller
        tag: v2.11.2
      env:
        UP_POLLER_QUIET:
          value: "true"
        UP_UNIFI_DEFAULT_USER:
          value: username
        UP_UNIFI_DEFAULT_PASS:
          value: password
        UP_UNIFI_DEFAULT_URL:
          value: https://unifi-controller-gui.unifi-controller.svc.cluster.local:8443
        UP_INFLUXDB_DISABLE:
          value: "true"
      nodeSelector:
        kubernetes.io/hostname: nodename
      ports:
        - containerPort: 9130
          name: metrics
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
    service:
      annotations:
        prometheus.io/port: "9130"
        prometheus.io/scrape: "true"
      ports:
        - port: 9130
          name: metrics
          protocol: TCP
          targetPort: 9130
