---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: v1.16.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1h
  releaseName: cert-manager
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  dependsOn:
    - name: prometheus
  values:
    global:
      leaderElection:
        namespace: cert-manager
    installCRDs: true
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 256Mi
    extraArgs:
      - --enable-certificate-owner-ref=true
    webhook:
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 256Mi
    cainjector:
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 256Mi
    prometheus:
      servicemonitor:
        enabled: true
