---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-resources
  namespace: flux
spec:
  interval: 10m
  path: ./manifests/cert-manager/resources
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
    - name: cluster
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cert-manager
