apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clusterissuers
spec:
  interval: 1h
  releaseName: clusterissuers
  targetNamespace: kube-system
  storageNamespace: kube-system
  install:
    remediation:
      retries: 10
  chart:
    spec:
      chart: charts/cluster-issuers
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  dependsOn:
    - name: cert-manager
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: adminEmail
      targetPath: adminEmail
