apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: v1.7.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1h
  releaseName: cert-manager
  targetNamespace: kube-cert-manager
  install:
    createNamespace: true
  values:
    installCRDs: true
    extraArgs:
      - --enable-certificate-owner-ref=true
    prometheus:
      enabled: false
    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
    webhook:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
    cainjector:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
    startupapicheck:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
