apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  releaseName: cert-manager
  targetNamespace: kube-cert-manager
  install:
    createNamespace: true
  chart:
    spec:
      chart: cert-manager
      version: v1.4.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1h
  values:
    installCRDs: true
    extraArgs:
      - --enable-certificate-owner-ref=true
    prometheus:
      enabled: false
