apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:gJhtyg==,iv:gcF/bGiNP/wRWsubCyXHeBHUha7cTUTW8Ge2vI1vJ/M=,tag:VDUUBUui2R6cPaeI2rBdKw==,type:str]
  adminemail: ENC[AES256_GCM,data:odBwoRQwiSfMmtRXDfsNr57aHg==,iv:KYIK4zjdY0kGponSyAW6hpiC4phL263PMogvvB8BcMI=,tag:Q/Qa+BzIvX8sYaj5SoWOpA==,type:str]
  adminpassword: ENC[AES256_GCM,data:H1pjMgahM1UN+xLV,iv:o8s7bpSHXkJnhIpD0yLnTl1JxgrnXEqAyHGWL1X4wnY=,tag:gnMst6Oj5C/HKIQXGggZUg==,type:str]
  alermanagersmtphello: ENC[AES256_GCM,data:5JK4efHOf+3jR5+UIoSoREfcUzNRJNmB5I0=,iv:BpcKPIRzG5LCz/4w9adlDiPpVOcYeZo96PvPDBw3LCE=,tag:BJvx5Mv1mnx9336ZToHyLg==,type:str]
  alertmanagerhostname: ENC[AES256_GCM,data:c0ruQjYJxiDD5aFFuBe8mm+4WlPwR6GCFH4=,iv:0BZQFfvxVWU+FaOEbf10Ykhjj2G1DUGXYxMPylM2+sg=,tag:teviuMy9CRqdJpQ886tMQw==,type:str]
  alertmanagerurl: ENC[AES256_GCM,data:KOyx6a/t+k8+lJaXC+LgjGtCUKkBNpKPlAqaSCnuPCaXng==,iv:yeb2p8c4FyR1pMWxdi8HYDINkTExAeEz2VefL56jSLI=,tag:j1vODNKvP9ZozNIuFuRiDw==,type:str]
  alertmanagersmtpfrom: ENC[AES256_GCM,data:ViQ6em7QsL4gc92iDWl2/t1YVHgVa68VnvE=,iv:QMSHXJnYqthTJ5HLlo1zn7+w9T+gy2osQl6vo/xmDmo=,tag:WTltbVwRmSUda2B3R0pSXw==,type:str]
  alertmanagersmtpsmarthost: ENC[AES256_GCM,data:S+N2zzXmRstn8T8kYcSDxayC,iv:WwbfAfvDS9/ivHx5Sw82Sy168c032Ob0y9657adv99E=,tag:cnziuJ1pYeJ6uZxvuIZc3w==,type:str]
  alertmanagersmtppassword: ENC[AES256_GCM,data:5q6eSGkAGlQ=,iv:/jUihFhxhuL11ShAZk0FqWUktx5xXlb2WjJourk67wg=,tag:BpeZIHxn/yVzv5TFIwO90A==,type:str]
  alertmanagersmtpusername: ENC[AES256_GCM,data:c938Pg9//Y1ExzvFhTwnzx3rcQ==,iv:qar5pXudX4cqj1ZavJkQgTyAOFy1JdO35GCicMbLxrs=,tag:Klmz3svwPYOWtvmytCpmkg==,type:str]
  grafanahostname: ENC[AES256_GCM,data:WSqFKPcFO6LATMExntZlkC6AH/cf,iv:TEKsOC0vtXy2FWtgTvqIUeD15M+We1hGo3oRfjlJrTE=,tag:rxfm63pUF3atZjWHPZt9XA==,type:str]
  prometheushostname: ENC[AES256_GCM,data:ZqLEgoNzeXivRItHFz2kcM1c8Nk+Wi7Y,iv:rYwls38PatH/b3+JLg6jslLXct0jpHEDILLjxYr4RRE=,tag:himXsXwtmhj1ZjjteNPC9A==,type:str]
  prometheusurl: ENC[AES256_GCM,data:bNLdG+bk1riM6/Cby+VZnqSqqTTxOvyMrHtHR0468QY=,iv:yvFx1D4fvnl/zQbVcMpV4KjZjaFMK3QWeHSecilISw0=,tag:O87K2FgRt567sKTYhM7eQQ==,type:str]
  grafanaclientid: ENC[AES256_GCM,data:ORrARWbBbA+iR4DXBe/Z1VIOh0YPHxejmfOjayQjzaJRqWDOzPdNQQ==,iv:5eKPFSUxteRL9NvDdhGOrmAZ6q567aYknTnZx9XWEIc=,tag:iFuL34rfDb5SmjQnNOI0eg==,type:str]
  grafanaclientsecret: ENC[AES256_GCM,data:DIyHkau85AohaJGNBHsbEUq5sLcPLVELikW3Fl/FEkZO0c2yR2Kje/kVSHtdNTtQ8SvLlMy5VfhjOcO2ASktXvZzc/LJHowXhTE2coA1zaqXArqAqFXDsfCcRd3fhzDho112sFHa5f4GU198OqZj1h3igZimMSz2VaZRUOlYnkA=,iv:4tXMXpS1823TzDOqvDpp3CEVgnOsOoh6xXzQT7dBV54=,tag:JTReCbzWVe18Okj3BUd48A==,type:str]
  authentikhostname: ENC[AES256_GCM,data:sLD3esTdZQk9SVtNzzke9Acp,iv:jZUijWJSi+8uFc2dWmtnzVXk38NZsZ1q3ZL/6FWipP4=,tag:iMBBClwPA2JjlzUKk4dc7g==,type:str]
  grafanarooturl: ENC[AES256_GCM,data:2HMftBxJkJTyy69sSJR7uTCEv3h+lty9mUXxPDg=,iv:0QD4KPd8UymuvpQg0JtOml5v+tYmDbaTEcQiQsnNs20=,tag:hEwzMFFYLVaMbAl6xcvwvQ==,type:str]
  grafanaauthurl: ENC[AES256_GCM,data:4X2NtX5Yw1Jk1hBw+AU9XXLwdkRbyzweQa2ItRBW2zPJw/F9cr4n40lo8xUzStGPRZBa,iv:7DoqYmYPyyk8Dk6OGd7dQxDhByumWDZFZp9gnTICSuY=,tag:7dUKdqNQX+/IzM3u2twVeA==,type:str]
  grafanasignoutredirecturl: ENC[AES256_GCM,data:cha3sW1k5Fu9SpqD8EjZDzT7EsOPRdFF4dWDxpSqGFyitb+bOyZhzSNUvEyvAudm+YB5hmx8viNk/AL+lg==,iv:oy2IpksRHvLs0Dd/wBPysZ6CRZ2yGDgqBj4kE7W1oEY=,tag:Fzdk/rwqNpMjE6dffZO87w==,type:str]
  grafanatokenurl: ENC[AES256_GCM,data:T0KGg+nNnqNCQV9jHb9HP/kM3/mPIwl0IU+Vn+lUnRg1vpG1humn4p6f2FyzMEA=,iv:ddlZ+9od8gUopnkR066dxC3YdeRSfc7GpMl/FIV4dAo=,tag:ooSdKgR550OctaDbu+jzlg==,type:str]
  grafanaapiurl: ENC[AES256_GCM,data:KODzcfts2mFkAnmODe6t8L/loe4sl0IFh9boLGmaikwFTqSOqD/gYUqwNVu7NLDZYk8=,iv:Lvc/fml/RqVtYYL6+5el++v2xt73AsE2EhgF0LFiSPg=,tag:SxCeSq+SbIl4Ba2Rr/Fv3g==,type:str]
  scrapehostname: ENC[AES256_GCM,data:msE/Czw=,iv:icfU56iWuxt/5XCo6nYgaArpJ1amXUpK9UVIcY6E868=,tag:v81kxXG2LDOKbNhcz4oS5Q==,type:str]
  scrapefqdn: ENC[AES256_GCM,data:P6yTW4rDG0FGCrAFYjHtwN2qqQ==,iv:bYcTUvCH5YHxx+VByzwK4uttu8VuVTyghnuHTz7cmr4=,tag:1lJc7o8AoLdzLpvwg664KA==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURUlocWpFcFVPcmZCeW9t
        OW53VGM0MlNrd3UzcVRiZitJV0o2VnNIU1M0ClQxQnl1SW9vMTVPRXREN2NFSzZ0
        ZEFWOGRqQjlNbDF4Z1Z5MEJJemFrWm8KLS0tIHZrbTJRM21Ta0tja0UwWHBKeDl2
        ODE3Q2VNK29kZmZBUThLcFgxc1FzVUUKshEA9/Yhth3PAQeeNp99pVH4AVJ2WX2L
        txHrwRFubOSYWbJJi8rYpPyYrab/+2/t4vApFdPCBcSp/cS4hXaoGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T21:53:43Z"
  mac: ENC[AES256_GCM,data:6j2kBItOopQLblZVJ+SkhXD3QkHmGEKbkqDrn+d6ZDUHtmL/6Hfzq+0zRYZVnMNqIdBUc7yzfg7rblW19diKREu0FhYDX//czdKFc38OljNeGtC6yh6FtEgMhPkz1SZNWJzVasE4Nuhw1DBJprxmqEZ3Lh9qna9DzOE3SRlKrRE=,iv:qGhESTKHx9lYvLO9wtWr2zlCreVK+ztFuy52HLX0uSU=,tag:q9zwU71ImYcypd/G3YboDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
