apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:MTO1QQ==,iv:S1SPHUtfPxm54dRKXuDGHDfF2mhFFeATq23GNg9P1ps=,tag:dlXgK7gr+BX1+tUDpTJY3g==,type:str]
  adminemail: ENC[AES256_GCM,data:VZFz4qOef+pnFnNPENXG9BDBHQ==,iv:ESV8Lw00un8ilSIuRHRwUjI+7Z5C5vTJtpA3vP2774o=,tag:tUB1aa5BinRFIyAPlgapIA==,type:str]
  adminpassword: ENC[AES256_GCM,data:+VntfJ5QrLAHiLTm,iv:G6TGvfjxNFOzqkfJueLs6dJOjmCrBJEl1M1R8urEB+I=,tag:g9/OHkhHwPG5fUgHGncJKQ==,type:str]
  alermanagersmtphello: ENC[AES256_GCM,data:zWw9dO6KDUwoXMm7awBzMIsSrykVWMP6gIc=,iv:m9Tb7P0eus5sdfwn9NQg7h9on2p7bXxFdHCGjUk21zI=,tag:9UdfysjVrjU2FcLxVy5QUw==,type:str]
  alertmanagerhostname: ENC[AES256_GCM,data:oMvDUuPH2IoefJPOorpuUIOu6eQUOxCmlns=,iv:WuzLmTXFQp6pLj7WqiE9OELcz9B2hNRxwjdbFKbDNfA=,tag:slvKw3cHlTgcAW2Sqy7Irw==,type:str]
  alertmanagerurl: ENC[AES256_GCM,data:kSBhRNf1mrF3Kzp7rC/tje8N82C655T0WQqOxCEynDG7PQ==,iv:DVApF/zifQQFo3fvcuhoYicAhFgyPgsEv59mHKGqxd8=,tag:Zp66QJKs3GdxQ3DYxIL5Hg==,type:str]
  alertmanagersmtpfrom: ENC[AES256_GCM,data:3vh+BkviqkzGU9m7jQnwh+B5vthAUSQnOmQ=,iv:5v9hbAkPn0S/WX1Z4av8bigsBxrXzeV5ThjFGFXaSCo=,tag:fiWaEH3Qb4O7QHJ/gEvkoQ==,type:str]
  alertmanagersmtpsmarthost: ENC[AES256_GCM,data:FPw0o2gi5Vx8SgcuY8WrnJ9e2oNx2g==,iv:ml15Zls7IaNQY3Bltwv+/wwDdQa8Z6Q3SOffWsQudl8=,tag:mBFGwO08VZJa92Po6w2BMQ==,type:str]
  alertmanagersmtppassword: ENC[AES256_GCM,data:lvRK8hNvFno7GIuQ1vc=,iv:bpZGuFXhZAUSsz1Yi7vmjoVvzVAh52Ft/0zqXGzk+m0=,tag:q8GKXjPIWlkUo68UJc9y0g==,type:str]
  alertmanagersmtpusername: ENC[AES256_GCM,data:FtBPY8TDWEzUtOn4OMAvc9BW3Q==,iv:X3P9vZiFljozIUXjbHOswUj/3t+ZgP1ujKFBygIKNbc=,tag:Q9n2C3iO7WKePnUWTOLgcg==,type:str]
  grafanahostname: ENC[AES256_GCM,data:T9WSSvz5jMsupYCfCvSfi1Z1eWI7,iv:cjtm/D72ze3BCboHX8mXGGBWtPAKNfsX/le6vVqj4nc=,tag:lv0K/fiqoQpep3B6lxHwRg==,type:str]
  prometheushostname: ENC[AES256_GCM,data:+DSa0/a4WqeehR0a1giTuSiEk6/vAtBi,iv:3bPocSmE8rTBi2GpFP/h9P2pubPiCAtOnacoTmENaFc=,tag:iafY5T/IV1G/IxT5CfaYNA==,type:str]
  prometheusurl: ENC[AES256_GCM,data:OFcUmowJRPwek7cNghF3295NaXE8LZZwpKdq0p+sY1w=,iv:7BqUgx+lWxDuCMAOBEtHzSNDt5pc6Q6hzJJA497IbW0=,tag:/vcsSV3wFq8z5J/js/DsJg==,type:str]
  grafanaclientid: ENC[AES256_GCM,data:gCeHTiqDGaHS3cuH4uQaol6VAmeDL47YOOjAiehi2c1nMqYmfLgQRg==,iv:KcNySVHVQYKHClpdY7sy0tM4ltZD+rjT8bIKAXQgDPE=,tag:eQKIwweR2jVmF+PwlpnpPQ==,type:str]
  grafanaclientsecret: ENC[AES256_GCM,data:oOwgp6L/8cBqD4UooUxsFk8V9GkbAzSe0KdGDXS1PLv1WHoQfKcO9j6mJPG607csm1Wj3ocM7hO4mhqxz9ZxqgcWDqdPfy5rHUUtWzIKfOjCU6P7zgsPZcDGQ3YU+Z/VfU35RlUDkq2VF//68Gg6YAB48kcfac9O/CD8NK/Z/5s=,iv:JNPQd5hzay8HCh99JinNePf3o3p+MdzgJYo6hZC8wgU=,tag:SA1fin+njxBP+j+yl6bwiQ==,type:str]
  authentikhostname: ENC[AES256_GCM,data:h6a3j/9+5rgkgUvzc6kxybKV,iv:zEgGIj34vjGn4QOh27fuLbKXwY7rBL41oR3PmhcYeyo=,tag:aBCT/7ors38bSnYtOtUDSw==,type:str]
  grafanarooturl: ENC[AES256_GCM,data:SEmGKQoHceNXN3T5fqAUoMzftlcCcXzLJqe+8DI=,iv:NNzy6WV7Zxc7sdoCKxVU5P3QLKCfe/Ei7kWmQ+HS/UU=,tag:Bxyq07w0fA+e2WNt5KdgcQ==,type:str]
  grafanaauthurl: ENC[AES256_GCM,data:XiRoutoWv7a77tVsJaJ60XND7COdYCJ/tPXYbzxixYfokUWFFYuoh12pPArRrB8G5EQY,iv:VdTHTPBdtKLPjNW7Fa7oJ/ca4fa6Cc4KoJYgfFEbdjY=,tag:0ipF563PAkr3vMP6b3uhvg==,type:str]
  grafanasignoutredirecturl: ENC[AES256_GCM,data:jVZZilmfm+A9XO3YWZ4iJepvvyj1ut6zN7Lie+2h6C+HqhEIfDGCbsyllPsP8AxOG0Z/yp0hLrpWK24aug==,iv:NKhlaV9zyXdBinI4+UNT3OocL7lEbk4b66q9OW1o/CM=,tag:1286wsyZ1bMwNJgXht5ltw==,type:str]
  grafanatokenurl: ENC[AES256_GCM,data:3qvPlkdDyTdKgFuDjAmv/Kd5zqNYtfg4zpFBEZO7uSAm10Lz03/xsLN4o2xAlvw=,iv:r5cFz4kpSuXeYrRekdMgce20ft9y3Wv7S9QQVg8rl/w=,tag:zdJEA/zriQNiOMBWGhahrA==,type:str]
  grafanaapiurl: ENC[AES256_GCM,data:y8TrP313wIOWJf2bcYEQ2/eRM+U3x2QkidVaG1pHVme/6HRvaQhviBxrZKMk6GdI2qM=,iv:O6Yo2Xf7HrZBhPF8CkbacyU4CyTlJfc0NCNGxFA0wZA=,tag:OnhWeRKEuICqalmPTzROgA==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU1REUThKOWpYMVc3dk5o
        SWNFSWpkSDdFa1R6SWJSRWcyWGVCcTB5VjIwCjNtU0Q3cFI1Q0VhMkErNUE3STht
        MzRhakhvR3Bnby9HblA0S3J4UDZhOVkKLS0tIFUzY3JFVDcxbVc4TEhaM0NvWm0v
        cVhtaWRMdTdDM1NqSVp3dkRmdDJWNEEKTP9W44u0MeZulLXCiLEJ/cTJTdRASXuH
        e3Y14YrSsYQRRyDl5BOThPRbUuAIS6MtzMoR6UlEm/yrW43JEkVZgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T11:50:19Z"
  mac: ENC[AES256_GCM,data:8NyfiydmKGA9M73bfH2hfA5ZB2I/kgNFrjeNFas5B3mQUAbEAMLEezcTKqaDxvzp98ETtQRmAXgu57Dg+NBdDDgnhuMLiQHOQEUSi5uROpj4t2nx52mvF28kNOVbi3rfmfDpERsmnW9yCBg0D4cRDQ8hpR2jGs0druxQi8g4Zn4=,iv:qGcOmkS/5sIoFTTBBMAcZ2CqRj/BLiu7kv3i7e+rkgI=,tag:lRhqDmwvjfPEMNi+2Obq4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
