apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:et7gpQ==,iv:A5IkpILf75RMJp3MIBUNGzAqkS70Rpln54ffYdF9BNQ=,tag:LuwbcrGnngRN0YS4DbiIPQ==,type:str]
  adminemail: ENC[AES256_GCM,data:+HbZ/x7Fz+F2puEfZfrs98IOqQ==,iv:aI/RCAyDsJReUAIupwtF6ZPWGd34RfumVlzOH7uF8/w=,tag:0Gmvoyyq1/+KHYi7Wa1JUg==,type:str]
  adminpassword: ENC[AES256_GCM,data:tUm4m6m03rV/ca+j,iv:cwAR5KMblFsTnsIJ/tMYDp7t1bF3MHkVyVgAxJZVWrg=,tag:3n+7kkiNL3OQEds5uPE6CQ==,type:str]
  alermanagersmtphello: ENC[AES256_GCM,data:w63dEbg0o0ugSAYCT2tk7mVgHOLgLZjeZHc=,iv:NcC6BRrN/S1bteETBavN5F1rFO9/fVyNlbVnHNyQLhg=,tag:pVMQT/VJSC9uEklx/pRMZg==,type:str]
  alertmanagerhostname: ENC[AES256_GCM,data:B8YuqJZdihkZo9xLKFK4ekSr/GgNynvK96k=,iv:82BPiUnryM/RI80xYgBtcpDyMR9xQVYkzI6z66Z8brI=,tag:TP/2ry/oWQWclzmCXhUaKQ==,type:str]
  alertmanagerurl: ENC[AES256_GCM,data:utAaxd2W4wAjfEGYUAQmeLzmuoseJ/0Fhmp70F+JYkS9KQ==,iv:9mtcCW0I5CNf6R4/nJzLmmz3i+z8G9u0XFm5F0+/UIc=,tag:kcbVBKYrwJoTJwg+MNzg6g==,type:str]
  alertmanagersmtpfrom: ENC[AES256_GCM,data:X6uFya+968lsnk2DMDooUVI5J89T1DhTkSI=,iv:qj/G4HwZ3l8o/mGP4J84C9/CSAMXbz9OGW8Bd+CVeck=,tag:CnLUXvRuJD4pA8PD+a7DEg==,type:str]
  alertmanagersmtpsmarthost: ENC[AES256_GCM,data:k11LlddNiJ/1Ld7gQfyFQdRDYd7F2iQ=,iv:EqVaDlG5qYcpN/P1p2qSvgyA9koXovM87q/UINNaNwQ=,tag:cFk+mdQXVF2LQLuCQkwuFQ==,type:str]
  alertmanagersmtppassword: ENC[AES256_GCM,data:5bUHXQVugHk=,iv:WiwZrsYfM1VX06+pQ0pL4L/3aQbui4uublhxzYUivzk=,tag:Ke1Z775p1ZUwCEcd3dF4ug==,type:str]
  alertmanagersmtpusername: ENC[AES256_GCM,data:bGpxqoQ=,iv:yx5XAq28ZphtA6MRwhzAs4ymutPddaSVoSl5TaUSXvg=,tag:2L+46hufVZtLJtR5GFBS/w==,type:str]
  grafanahostname: ENC[AES256_GCM,data:4BR85xpwK1GS9HlLahhxLVr1atQQ,iv:d2t1ZNdbrS1Flj86fAgo3743gSbyYXltiQGbT/9dWOQ=,tag:1BVkpnPFGr18PZYo+vJU1A==,type:str]
  prometheushostname: ENC[AES256_GCM,data:HkFAdn391bfdbYwCU2D+gNvWAoyrvsg+,iv:EM4uHBvOo7d/XERkkcq3vHJA/lg1Bf/bO2VyG+S9UPw=,tag:fukqP1pLSfW36yAM02vkdw==,type:str]
  prometheusurl: ENC[AES256_GCM,data:GQYFZgVJcjSy5z3ZiO6C3h3lzo/xwqgoDQRbz5Q59VQ=,iv:5z0wiWuRaeF1x78CQs8TH3CL47eO7+7R/BPmY1suv94=,tag:vuOwKT4JOvkivY0kv5yf2A==,type:str]
  grafanaclientid: ENC[AES256_GCM,data:NyNR/m4cYaG6oudXq65LWNMU8VEZmZumxrnLvu+wGImF5RsRCofAxw==,iv:VThxLk7SMJx66D9gu9q/SjTVJLiZe70bqtG5HWIugYA=,tag:NExJFWRM4VjVxUKlikkC/A==,type:str]
  grafanaclientsecret: ENC[AES256_GCM,data:6Ihg/HfVYLAojqsPbRJKua6IX5ZPibCr5LC97t/NLPY6NFaJ6oC/siN9kgApYGwgvIPvVhRi6iH0TMVmwWfJNcudUdFRpXwewhUQaq2mhgbI7FTEHmzm1Dpu1m/bW1D7iwywGwFbhqBbpk0UrhP9pOB8VjaxcjuphQKyR6sgQ3M=,iv:+a7lVQw55e+XDxRhGZQm90WvRvKLd6/vAPT17XU9AMQ=,tag:9aCQEkc1r+yG+VS3AjIOOw==,type:str]
  authentikhostname: ENC[AES256_GCM,data:E4g25j6cfeRYsBGYUJIkA6Rs,iv:i8MYiISQLTPhaOtVylTDt3wWTZ7GswwgrOBZf8kIkYs=,tag:XlRZvNc/DUPRJu6IYfEn0A==,type:str]
  grafanarooturl: ENC[AES256_GCM,data:fqg+9jzi/z60tFue4d8sQMWTnwG1Op1NklxUc5c=,iv:9gnfFOyV505eX/yx89eoY4o8SZGa+SsYgpZplws68Fk=,tag:OrCA+/J4If0dqNxFE10d6Q==,type:str]
  grafanaauthurl: ENC[AES256_GCM,data:E//KRBmdRx46lXT7MsFo+2tkVkEQ28/z1yCU8h6BhSjf3UHlrvS8ni/xzw6bV4/5sjMA,iv:Xtxp3fBhMLhGaGwj/TpftgyxhTW+MlA3Qy6awIp2/zM=,tag:xXZ4yQG6IxAE5TGnh69UVA==,type:str]
  grafanasignoutredirecturl: ENC[AES256_GCM,data:MPRkK0TQGfBAU7Xdmjfjfw88JXrpgfkwArp2l1Cjs+kA+7cT/qNZ+0cgQHL3qH2BLYS1fDQNnd86oKd1fA==,iv:kRl6zfXXdMWmwd2Kmoavt8DFh1g/3tgT04DrQgaCvGQ=,tag:EkCRaBKeIRm2OFfo290jig==,type:str]
  grafanatokenurl: ENC[AES256_GCM,data:yIVpYGKUWtFJpj6TMO5VqOXjAIRARh2XtlFvTj9vg2rG3f3o1XOoCNmGI2Y9hv0=,iv:KfEpbhB0/7IQQCTvLtdjS6/2OWUvrGaOl9VWh8kmeq4=,tag:dNTJaLM1/gkslfIcl7yCOw==,type:str]
  grafanaapiurl: ENC[AES256_GCM,data:jKQwDcHhldD4BzJA4qOF31ZwHLH3P8y9qgdeKuV1nwrRxkFil76ICAxMuYqzVfkRzRM=,iv:5HCZwaRPsKP6FNzWUp0spYDhTWeSXerVvkpxxt1P7Nk=,tag:pVSvj/gHyowUajHe6b5gVg==,type:str]
  scrapehostname: ENC[AES256_GCM,data:959qSVw=,iv:MNjpjWFcZFV+7ZHv8ryrkmXi5sq/wW1b1So0ZytUnTk=,tag:0AKTSlkI1DDY7inco/Tlcg==,type:str]
  scrapefqdn: ENC[AES256_GCM,data:Ij9fN2V+SMP0hIaEmymAQC5v5g==,iv:co9269F2uDe/RV+LUC2yv6JSjP45PsYl1iGjw6iY9xM=,tag:6xf2w18kFst2ULCfo8V2SA==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ3ZianRoaVB6cTdrSDdj
        NFlSSkQySmtDc2xmUUNrbEtnc2JRVXpOSzJ3CjVZRDFtTjlOZzdoanhoby9QeHdE
        aWx2bENBdUthSEkzYzNuM2kyVVNKRlUKLS0tIGp0WWdHQkg3UndGTVd2UEoyaTc3
        NEVwY1I2bUpkSkpacSs0STc1Z0EwN0EKMXmavos6u7P3DIi0MdZDbj/ssHpp1QFE
        6m4f7+W7X6VuZEDz+vZdibAP3D89gRx4G0BoR6o1QUDDAESS1b471Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T09:31:53Z"
  mac: ENC[AES256_GCM,data:wllUdwt94gG9CQJ2Ij3zCS63ttarVWpdoXVph4EUWqt32xo985s0NoKYpiJ7wZQn4CZemHbPcVf7IFeir8AM/ceYJaWQK+Cn+k7y8ONXt/Wds84J1UzqpKH7g7G9MYGCl4hC8AezthkrhEp/NKGoB2idf/xyOFUCypnxoBFhqOk=,iv:uXhAX71hmCOT4PtbhhiXSxx7z+m5sFnWDzp4BOjR4lU=,tag:RTDbQDcAsT8Fcfhc0GctvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
