---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mochi-mqtt
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: application
      version: 5.2.5
      sourceRef:
        kind: HelmRepository
        name: mochi-mqtt
      interval: 1h
  releaseName: mochi-mqtt
  targetNamespace: mochi-mqtt
  storageNamespace: mochi-mqtt
  valuesFrom:
    - kind: ConfigMap
      name: mochi-mqtt
