---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - resources.yaml
configMapGenerator:
- name: mochi-mqtt
  namespace: flux
  files:
  - values.yaml
generatorOptions:
  disableNameSuffixHash: true
