---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mochi-mqtt-resources
  namespace: flux
spec:
  force: false
  interval: 30m0s
  path: ./manifests/mochi-mqtt/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
    - name: cluster
