apiVersion: v1
kind: Secret
metadata:
  name: mochi-mqtt
  namespace: flux
type: Opaque
stringData:
  lan: ENC[AES256_GCM,data:laXEr9JotdqZCpHwbkI2,iv:HYYmvLcGNJeFSG/eVGsf4Grn+J7k+HlQ75NpdoTmiwU=,tag:6OXXjWMrn29kPB9ubAq0hA==,type:str]
  ip: ENC[AES256_GCM,data:KhkGwMwWA1TjDg3Krnk=,iv:/SamGD690APJm717ohTs7QSZKPy0GAt1gepvxooQxbg=,tag:VIgOesM+Q42Rh7B0xBkpBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJd0VrdUNINWVxMVl2K2hE
        RFpWOThZc1NTMWQzRS9qVnpmQ3dGZzJLeFFnCnc2QmgzdjYxSlhtQjgzdTN6R25V
        YjBackZDU1RzY0cyY2xLUytJNnVnUzAKLS0tIGpKZTY4b2lPLzN5RkxyQTN3Zjcv
        S3dxZmNwNG03Nlc4ZzFDclhaVGN2WWsK7owLjRooY4/3wHDH4Gq8w8Ge3zx4IB9K
        rRcBkZnjKYaKa/IUxNgHclUumvg4HI2ZB92cjDOI4TbpWg4JO1/xXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T06:46:37Z"
  mac: ENC[AES256_GCM,data:6mGPKIna/MY9Rdo/DmtBDAKu+dtKrJd6qoyPEtH/yERGNAt0imkBBCFuWDhS4KPr3nk+NRQvQmI8DcXN1qPYB9BqdAJu4BfjfoqQzaaoICoBgjvFv9NSfHbBOtBUuHontZQ3nqNnAXB3WW8F0noiJ4Ozwoh6kEx1oWze8pL50Ns=,iv:6trH1syNQsZvGmSsWkgZAWwamA/L/UIiz915w7Kl5MQ=,tag:huqwuaJQhTs4+BibaG/FQw==,type:str]
  version: 3.13.3
