apiVersion: v1
kind: Secret
metadata:
  name: mochi-mqtt
  namespace: flux
type: Opaque
stringData:
  lan: ENC[AES256_GCM,data:Y39GzNNTA9cTwJ2akufg,iv:8vx9LtfJ9LdKZuAsnKn2WI44oX/XiitGRoOk0TgWpws=,tag:H0yrOT0C/1Sr5HV6ZSPfsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeHBjTkZ4M0hqTGlNTFlU
        cVNySDBLZjlNYWQ0aWdLVWIyZ01YRkdhY1VVCmZPK3BxV3d1eW0rM3hYV1BnSXFj
        em9DR0xiaG4xVUhBWTdjYTVWWDZiKzQKLS0tIEd3bjhic3k0TFhsN2tFN0VoeHha
        RVJLa0JoSm4zRHdlYWhUMWw5NFl4RlkKMYMpD4LZCmMNu3R2YCiZr3KnscEUoCCM
        hQY2DdWGSxUmvNlsaQUH2+DDxWvmhnrtmmAJ4bTyOhzzAs3s2tPsIQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T03:59:04Z"
  mac: ENC[AES256_GCM,data:XQHpeuxReQgRHAD53EGwNPwUPMSDLVsxtSPuE6ubfakwwszyxvFYHwaUIBjXsMh4S2koprXj9bV5rmghktnREw9BWE75kAwyY3gc/zCKEEOj+41N6OQcXt02a+CJn5Wza728V8o/o//oF7MGTW0hyfb605IOLiKnydEfKS6xrKQ=,iv:ngD8p+ae0UbKolOSR8/krmNnLqoS1hrlq3kN0AO8lpg=,tag:qHzAB7DSPC2jPoNLlv97Sg==,type:str]
  version: 3.13.0
