apiVersion: v1
kind: Secret
metadata:
  name: moch-mqtt
  namespace: flux
type: Opaque
stringData:
  lan: ENC[AES256_GCM,data:HrUaxgptoxlf2CCLpXY+,iv:RuHyYXB/aSyh4GIbXCnypvIurNoRejPBDX1sb1Shuc4=,tag:YgTvDeoa/EaWChRY2Yr3pg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQzlQYVVnTW5YM05rUWZq
        cjRKam5ZTlhBcHIwYlpZVjEvWDZQOEJDLzJvCmsxYVpTb1JnZ2FVR2p4SXRZYzdz
        WmhOd3NIVTVzWDA3dWZIMmJZOVpWOTQKLS0tIEZpWXhMN2FndUFoTVViMzNNSWhV
        b1N1Q3Rhd2dYNVdJc3BkbllQenZBVGcKr4H+sdrQ3NaIyg2W+GEHL/ubBKwxKQdw
        b4OEJUX2cgCBdEfETydBs55XFKWav8HqcIYX6Ot1NRav+3p0dDDbDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T11:17:24Z"
  mac: ENC[AES256_GCM,data:M7fo5BOsgeSTMHhXZ/zkybSwESBs85sEmmdjwZemnF3xXYPzXPsDWZAR71rJHkFIqsBOctFfjAcLqbcuyo3pV3AsdqMAq4lypOmI+lFuuR2AmFrercQnbOsIa+iV8pWQ76AuSI+9zbkZNPcRkxofIiwRmZomBzlD6sOdqjOciJc=,iv:ikgrKCvfZ1q9FxMdCGPmQub8pF+rzoM2fgDGEFGpjys=,tag:5Pcjh4tAKOPW3LRYLZKIMg==,type:str]
  version: 3.13.0
