---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: zigbee2mqtt
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
      interval: 1h
  releaseName: zigbee2mqtt
  targetNamespace: zigbee2mqtt
  storageNamespace: zigbee2mqtt
  valuesFrom:
    - kind: ConfigMap
      name: zigbee2mqtt
    - kind: Secret
      name: zigbee2mqtt
      valuesKey: nodename
      targetPath: statefulset.nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: zigbee2mqtt
      valuesKey: hostname
      targetPath: ingress.hosts[0].host
    - kind: Secret
      name: zigbee2mqtt
      valuesKey: hostname
      targetPath: ingress.tls[0].hosts[0]
