apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:sKcC+DaZ,iv:BmWylOoEz/iFds4c6ljKuQYfjZXxrxZhKsBEmlqINEU=,tag:Xdw3f63Bt9JI4McdKmy9ug==,type:str]
  hostname: ENC[AES256_GCM,data:uGFzfPIKaNIf+MEn+ju1j1t7cxA=,iv:92Xx4JqJymia+Z0aYcgUwxVN1HqEf7w1yMH3uU59Kcc=,tag:TLwTW5FsOZ8vaQoZpnc3+w==,type:str]
  ingresswhitelist: ENC[AES256_GCM,data:eBcYcoY3YGaFFJKR1cwk+B4EP+65tWWxOWF2PZx32/TG2/VxC9iiIQKycZwlP9vP,iv:oWZ505kvN7c6hB7ObzNnkez8k2FbQavUtOsb7tlMfc4=,tag:O48xqd90IT9HZaUiBV9cQA==,type:str]
  backupusername: ENC[AES256_GCM,data:j9GskbFpBSg=,iv:C+fhxMtgE9f9zeIFKPmgDHTIg3U0zJJTOXNwQO0dkIM=,tag:ZGy0c/X4UA8Pb4ObhpHyhQ==,type:str]
  backuppassword: ENC[AES256_GCM,data:1PdZVD0oPoAcMSOq,iv:DZxU0UZ/1J4/k2WffE+AW4nwEOegTNkSAh0JTrfIP3w=,tag:i4BT/x+J38rPpYGqvYoBcQ==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:5kk9h64DADrixQPGxJg=,iv:dcYBRr9W0TCODzqi71uroO+yo0MN78cShhkhVF6sVZA=,tag:upHeRGjIUXY1/SfD8XzqcQ==,type:str]
  backuphost: ENC[AES256_GCM,data:YjlYrsJ/nogQqZeERrHlofD1jIOkm/gKWZbG4yY7,iv:yWrX6K2EHq9OQwU3u8t0PtTEaGGaQSk63H8TJO4KD0o=,tag:O7Nsf4+v/NUQxMeKZxVHAg==,type:str]
  backupurl: ENC[AES256_GCM,data:oIUiJFWKY7SwmHzgzFkSdT9YxT6sZ43LBKS1KeDv7WiK2uttA+VSSmBcU8BtaicJJrE9,iv:yVkocv4JcQeDuXgaytSrrtfM/f7T/suSw87r3AAt9dM=,tag:Sx6smWYAe3NHBWSpV8Hg7g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWDhnS2JLT0NNNEF3N1c4
        UlNVaWg1WFl2TjVoYUFIelByZW5DempMSUNvCnh4aEpxenhCT2V5OHRxQ09yZmxS
        dFI5cDhIaGY1OHJGSTNXMFh0NnBldHcKLS0tIE9UK1ovYzZGKzRoYzYvVWJIa2Fp
        eXBBbXg4V1BDQ3h6UnA4TktSUUVSZWMKjdyShGQWnInceYKKr8Jc0c/GMHWzMJXa
        ySdSdk+9/5XwXC22947Hb0yW63ZY6b6A6+KyE/UJnJIgyoscD/2mhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-18T13:08:04Z"
  mac: ENC[AES256_GCM,data:KRVAVt/UvS5+ZmXUBzr3KiBBtgXedRB0y+M1eaZISLKaPH/gVkOCPpsgMu9i4IU81i7gwuKzSAYGRjRufUxKdSV5qc+yXm7HjkbEErmGJRGd2xgjINUcVmIjU6yxD2nWypdNKOIc+djNU7GQDvXb28jpv2Y8b1u/osMp7MNR7x8=,iv:1wUVP2uwwBGje0L0Is26NiPHjcZBuMt7reX03d8ZoTA=,tag:QmoKNIddZiEfdsysSphQPw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
