---
image:
  repository: koenkk/zigbee2mqtt
  tag: 2.2.0
service:
  type: ClusterIP
statefulset:
  nodeSelector:
    kubernetes.io/hostname: ${nodename}
  storage:
    enabled: true
    existingVolume: data-volume-zigbee2mqtt-0
    storageClassName: ssd
    size: 1Gi
zigbee2mqtt:
  mqtt:
    server: mqtt://mochi-mqtt.mochi-mqtt.svc.cluster.local:1883
  serial:
    adapter: zstack
    port: /dev/ttyUSB0
