---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: samba
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: application
      version: 6.11.0
      sourceRef:
        kind: HelmRepository
        name: samba
      interval: 1h
  releaseName: samba
  targetNamespace: samba
  storageNamespace: samba
  valuesFrom:
    - kind: ConfigMap
      name: samba
    - kind: Secret
      name: samba
      valuesKey: nodename
      targetPath: deployment.nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: samba
      valuesKey: nodename
      targetPath: persistence.annotations.volume\.kubernetes\.io/selected-node
    - kind: Secret
      name: samba
      valuesKey: nodename
      targetPath: deployment.env.SAMBA_CONF_SERVER_STRING.value
    - kind: Secret
      name: samba
      valuesKey: workgroup
      targetPath: deployment.env.SAMBA_CONF_WORKGROUP.value
