---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 1h
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  storageNamespace: ingress-nginx
  dependsOn:
    - name: prometheus
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx
    - kind: Secret
      name: ingress-nginx
      valuesKey: nodename
      targetPath: controller.nodeSelector.kubernetes\.io/hostname
