apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:OgTgBu9M,iv:l4RRV0FgIpRJSIIMuGPPlz7yHfNIKHoVv7n460jDIyc=,tag:KQt4zFwBijAAj+BflWayJA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NzB4blJvTWI2V1B5SkMz
        ZEFhbUtmRG5sT2FrQW4wQUZkSUZqVlBaUzNRCk4xK2Z2SHJQV3VUOXNyYmY4RUdy
        Y1RjZGFVV0hvVTh4cFJpYUpTbUN1ZVUKLS0tIGUvNUhUMUJlc0ZUUVFTQ2FnV1Zn
        ZGZjUEM4OXdkZEF5UWJNU21RVlNOOFEK3HCh9r6jcxLZ6jfTuUnjLD7B8JWKK3YC
        P67NofhF/14rM6Npl70LnGNhH7HblGa3THq+KlwiIigsf+HcRxDQeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-16T06:49:03Z"
  mac: ENC[AES256_GCM,data:BKSLUtb5/MZ+juX45UEapAbxo6VEAI+Vfr3fzpW2TI3cPrlDGiajngigntuGysTIl457Qh0T2epzgWBPAJF/WYQ7NrVtJltYzExfV+JFt21t0ED9aRiuxsBn8Kuw4yOWO6kSo7+lGyLbug4qHfXEbcE4L3gKuYZOCX1BtmYoX3k=,iv:tQPpKn2Egvw87WSFhBLWpNTiydLbZ23ijwJlqS6KGGI=,tag:oyjgtBr4eaR5eiG0JYQS5w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
