---
controller:
  config:
    use-proxy-protocol: "true"
    annotations-risk-level: Critical
    strict-validate-path-type: "false"
  allowSnippetAnnotations: true
  kind: Deployment
  updateStrategy:
    type: Recreate
    rollingUpdate: null
  nodeSelector:
    kubernetes.io/hostname: ${nodename}
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  metrics:
    enabled: true
