helmChart:
  repo: https://prometheus-community.github.io/helm-charts
  chartName: kube-prometheus-stack
  # renovate: datasource=github-tags depName=prometheus-community/helm-charts
  chartVersion: 89.2.0
  releaseName: prometheus
  namespace: monitoring
  skipPrePull: true
