apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 1h
  releaseName: ingress-nginx
  targetNamespace: kube-system
  values:
    controller:
      config:
        use-proxy-protocol: "true"
      kind: DaemonSet
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      admissionWebhooks:
        tolerations:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        patch:
          tolerations:
            - key: node-role.kubernetes.io/master
              effect: NoSchedule
            - key: node-role.kubernetes.io/control-plane
              effect: NoSchedule
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
