apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-wrapper
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  values:
    name: ingress-nginx
    spec:
      interval: 1h
      install:
        createNamespace: true
      chart:
        spec:
          chart: ingress-nginx
          version: 4.0.1
          sourceRef:
            kind: HelmRepository
            name: ingress-nginx
          interval: 1h
    template:
      controller:
        config:
          use-proxy-protocol: "true"
        tolerations:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
        admissionWebhooks:
          tolerations:
            - key: node-role.kubernetes.io/master
              effect: NoSchedule
          patch:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
        service:
          type: NodePort
          nodePorts:
            http: "{ var:httpNodePort }"
            https: "{ var:httpsNodePort }"
    config: |
      - name: ingress-nginx
        namespace: kube-nginx
    defaults:
      httpNodePort: 30080
      httpsNodePort: 30443
