apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  releaseName: ingress-nginx
  targetNamespace: kube-nginx
  install:
    createNamespace: true
  chart:
    spec:
      chart: ingress-nginx
      version: 3.15.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 1h
  values:
    controller:
      config:
        use-proxy-protocol: "true"
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
