apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-wrapper
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      version: 1.3.0
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  values:
    optional: false
    name: ingress-nginx
    spec:
      interval: 1h
      releaseName: ingress-nginx
      targetNamespace: kube-nginx
      install:
        createNamespace: true
      chart:
        spec:
          chart: ingress-nginx
          version: 3.15.2
          sourceRef:
            kind: HelmRepository
            name: ingress-nginx
          interval: 1h
    template:
      controller:
        config:
          use-proxy-protocol: "true"
        service:
          type: NodePort
          nodePorts:
            http: "{ var:httpNodePort }"
            https: "{ var:httpsNodePort }"
    defaults:
      httpNodePort: 30080
      httpsNodePort: 30443
