---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: gitea
    namespace: flux
  releaseName: gitea
  targetNamespace: gitea
  storageNamespace: gitea
  valuesFrom:
    - kind: ConfigMap
      name: gitea
    - kind: Secret
      name: gitea
      valuesKey: nodename
      targetPath: nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: gitea
      valuesKey: nodename
      targetPath: persistence.annotations.volume\.kubernetes\.io/selected-node
    - kind: Secret
      name: gitea
      valuesKey: hostname
      targetPath: ingress.hosts[0].host
    - kind: Secret
      name: gitea
      valuesKey: hostname
      targetPath: ingress.tls[0].hosts[0]
    - kind: Secret
      name: gitea
      valuesKey: adminpassword
      targetPath: gitea.admin.password
    - kind: Secret
      name: gitea
      valuesKey: oauthkey
      targetPath: gitea.oauth[0].key
    - kind: Secret
      name: gitea
      valuesKey: oauthsecret
      targetPath: gitea.oauth[0].secret
    - kind: Secret
      name: gitea
      valuesKey: oauthdiscover
      targetPath: gitea.oauth[0].autoDiscoverUrl
    - kind: Secret
      name: gitea
      valuesKey: smtphost
      targetPath: gitea.config.mailer.SMTP_ADDR
    - kind: Secret
      name: gitea
      valuesKey: smtpuser
      targetPath: gitea.config.mailer.USER
    - kind: Secret
      name: gitea
      valuesKey: smtppassword
      targetPath: gitea.config.mailer.PASSWD
    - kind: Secret
      name: gitea
      valuesKey: smtpfrom
      targetPath: gitea.config.mailer.FROM
    - kind: Secret
      name: gitea
      valuesKey: smtpenvelope
      targetPath: gitea.config.mailer.ENVELOPE_FROM
