---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rest-server
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: application
      version: 6.0.3
      sourceRef:
        kind: HelmRepository
        name: rest-server
      interval: 1h
  releaseName: rest-server
  targetNamespace: rest-server
  storageNamespace: rest-server
  dependsOn:
    - name: prometheus
  valuesFrom:
    - kind: ConfigMap
      name: rest-server
    - kind: Secret
      name: rest-server
      valuesKey: nodename
      targetPath: deployment.nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: rest-server
      valuesKey: nodename
      targetPath: persistence.annotations.volume\.kubernetes\.io/selected-node
