---
applicationName: rest-server
deployment:
  image:
    repository: docker.io/restic/rest-server
    tag: 0.14.0
  nodeSelector:
    kubernetes.io/hostname: ${nodename}
  env:
    OPTIONS:
      value: --listen :8765 --private-repos --prometheus --prometheus-no-auth
  ports:
    - containerPort: 8765
      name: restic
      protocol: TCP
      hostPort: 8765
  strategy:
    type: Recreate
    rollingUpdate: null
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 999
    seccompProfile:
      type: RuntimeDefault
persistence:
  enabled: true
  mountPVC: true
  mountPath: /data
  storageClass: hdd
  annotations:
    helm.sh/resource-policy: keep
    volume.kubernetes.io/selected-node: ${nodename}
service:
  ports:
    - port: 8765
      name: restic
      protocol: TCP
      targetPort: 8765
serviceMonitor:
  enabled: true
  endpoints:
    - interval: 60s
      path: /metrics
      port: restic
