apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt-wrapper
spec:
  interval: 1h
  releaseName: zigbee2mqtt-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  dependsOn:
    - name: nfs-subdir-external-provisioner-wrapper
    - name: cert-manager
    - name: clusterissuers
  values:
    name: zigbee2mqtt
    spec:
      interval: 1h
      releaseName: unnamed-zigbee2mqtt
      targetNamespace: unnamed-zigbee2mqtt
      install:
        createNamespace: true
      chart:
        spec:
          chart: zigbee2mqtt
          version: 7.1.1
          sourceRef:
            kind: HelmRepository
            name: zigbee2mqtt
          interval: 1h
    defaults:
      issuer: letsencrypt-staging
      usbDevice: /dev/ttyUSB0
      mqttServer: "mqtt://localhost"
    template:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "{ var:issuer }"
          nginx.org/websocket-services: "{ var:name }"
        hosts:
          - host: "{ var:host }"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - "{ var:host }"
            secretName: nextcloud-tls
      persistence:
        data:
          enabled: true
          mountPath: /data
          accessMode: ReadWriteOnce
          size: 1Gi
      additionalVolumeMounts:
        - name: usb
          mountPath: "{ var:usbDevice }"
      additionalVolumes:
        - name: usb
          hostPath:
            path: "{ var:usbDevice }"
      config:
        homeassistant: true
        permit_join: true
        mqtt:
          base_topic: zigbee2mqtt
          server: "{ var:mqttServer }"
          include_device_information: true
        serial:
          port: "{ var:usbDevice }"
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: zigbee2mqtt
      targetPath: config
      optional: true
