---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gs1200-exporter
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: application
      version: 6.0.3
      sourceRef:
        kind: HelmRepository
        name: gs1200-exporter
      interval: 1h
  releaseName: gs1200-exporter
  targetNamespace: gs1200-exporter
  storageNamespace: gs1200-exporter
  valuesFrom:
    - kind: ConfigMap
      name: gs1200-exporter
    - kind: Secret
      name: gs1200-exporter
      valuesKey: nodename
      targetPath: deployment.nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: gs1200-exporter
      valuesKey: address
      targetPath: deployment.env.GS1200_ADDRESS.value
    - kind: Secret
      name: gs1200-exporter
      valuesKey: password
      targetPath: deployment.env.GS1200_PASSWORD.value
