---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gs1200-exporter
  namespace: flux
data:
  values.yaml: |
    applicationName: gs1200-exporter
    deployment:
      image:
        repository: ghcr.io/robinelfrink/gs1200-exporter
        tag: v2.11.1
      ports:
        - containerPort: 9934
          name: metrics
          protocol: TCP
      nodeSelector:
        kubernetes.io/hostname: ${nodename}
      env:
        GS1200_ADDRESS:
          value: ${address}
        GS1200_PASSWORD:
          value: ${password}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    service:
      annotations:
        prometheus.io/port: "9934"
        prometheus.io/scrape: "true"
      ports:
        - port: 9934
          name: metrics
          protocol: TCP
          targetPort: 9934
