---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-operator
  namespace: flux
spec:
  interval: 1h
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator
  ref:
    tag: 0.50.0
