---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-resources
  namespace: flux
spec:
  force: false
  interval: 30m0s
  path: ./manifests/victoria-metrics/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
    - name: cluster
  postBuild:
    substituteFrom:
      - kind: Secret
        name: victoria-metrics
