apiVersion: v1
kind: Secret
metadata:
  name: config
  namespace: config
type: Opaque
stringData:
  age.agekey: |
    {{ config.source.sops.age_key | indent(4) }}
  config: |
    {{ config | to_yaml | indent(4) }}
