---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-keydb
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: keydb
      version: 0.5.13
      sourceRef:
        kind: HelmRepository
        name: authentik-keydb
      interval: 1h
  releaseName: keydb
  targetNamespace: authentik
  storageNamespace: authentik
  dependsOn:
    - name: prometheus
  valuesFrom:
    - kind: ConfigMap
      name: authentik-keydb
    - kind: Secret
      name: authentik
      valuesKey: keydbpassword
      targetPath: auth.password
