---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - resources.yaml
  - valkey-helmrepository.yaml
  - valkey-helmrelease.yaml
configMapGenerator:
- name: authentik
  namespace: flux
  files:
  - values.yaml
generatorOptions:
  disableNameSuffixHash: true
