apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:PmgzHg==,iv:Q5mhfWQyLeZ/b0vu/yp40SHLrpq3owK1KbKP8gXvIUI=,tag:szOWQcq7nWOLz26E4dLjyg==,type:str]
  hostname: ENC[AES256_GCM,data:y426xXV2j2Y3/XFWW7UoWspl,iv:PpqD6L6PKvTuItB/ECNV0gZQJte2wfzCqtA6SVzx/d4=,tag:7/IwxIbI54qsELWhGN9COA==,type:str]
  secretkey: ENC[AES256_GCM,data:1eoh8t/41nRC3xiUWPubvqehuAendl83cIhPhB7ST0Pdl/vCpmKtmU709j5qsZlRp/I=,iv:dSTq92OiBMMbq2pvgXxDqa8ihiXkyRaQLVfFEtUAL0E=,tag:5vfVpLbAwgfk0u6PYf13tw==,type:str]
  emailhost: ENC[AES256_GCM,data:OI7qVVZiTtDzt6WzZSVAzUxNMw==,iv:R7NeDwyrP8S3L7//DNVykUBAk4tmd8Qdh0IjLkJINsY=,tag:uaw4axLTtcHGgSDTovxX0A==,type:str]
  emailusername: ENC[AES256_GCM,data:IdErw44=,iv:mynEzBQTY95fRrapTUNr3M/qF4pzrQUsS89teD2Yiek=,tag:YjwwRWjvLjXAmDanG9waWQ==,type:str]
  emailpassword: ENC[AES256_GCM,data:hQenVvrHa8g=,iv:ktImiJTBYxi+zDCcbxzcYQH/ywR7MKR6GZepsVz4Oa4=,tag:FqI3XHjPmi99PKJxKkx2tA==,type:str]
  emailfrom: ENC[AES256_GCM,data:k86y456D+uhICR6nA+MFEcfwp//LXls=,iv:iLHraGBjFKjrMf1nfAV/KoU4tamwxQMmhYcxII9FFpA=,tag:fuc22QLnTkcDXZv4jnUIyA==,type:str]
  backupusername: ENC[AES256_GCM,data:FeFqy7XTpqo=,iv:YOWuq9OohDHUCUHyaO7R6L0XUYWHcW3y2FCc6+flZkI=,tag:aTPjsxN+k84nrbpg958zUA==,type:str]
  backuppassword: ENC[AES256_GCM,data:YtvkxzEfcImI1mSc,iv:t7HTtx5PmPI3W+1SfKBY4Y/HGklbHvOljNGON1xPqYA=,tag:iP0GxDEJv4JPlSBnu8xzIg==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:e2DtdH0wnqGhHixvIgA=,iv:+EZAlqM0bZH3XDbOJPUSY/rgRfJXN67RairytIZ+zVk=,tag:FSUxilJI1fyhBAyvCxghtg==,type:str]
  backuphost: ENC[AES256_GCM,data:dzxGRCEYyuK6HbYQEdjYfbXorF31iMEmO5Wfhepl,iv:IONqPHOl10V6ebGXbgUhZ6SzcikE73bDqMAE8jlPk5E=,tag:T3WEkbMvnod0R6kvSqh7mQ==,type:str]
  backupurl: ENC[AES256_GCM,data:eZzAmMuQ1z79AJVbULbxjOmPKyOGQHXhhRuSqFmWMwUc+3UXD2/a8lDcxLfCH+sI8K98,iv:RlZcOzzAXsKobmdS/HXbCdtupQ6ZsDr4UbhCzvKD7mE=,tag:CSPXli3l36L0DLDDlsi+nA==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK2xJWnVLR0RZWHJHM21p
        bG1KNFFpZzZjanVzd2FUOHlXRENWY0wvaEE0CjBDK24yVit6Q3ZIZDhhdHJBYmNs
        MnN3OE95OFp0bGVWZGcyKzJ4bXdoK2MKLS0tIDZEby96ajhoR09FQjlTdFV3WkNa
        RDJEUlhHaWx0aXBlRXRIQlEwZXZqZEkK8lOQ8WXPCjWID+K7MHcF7V0lm7V+6X+d
        84cJPrF95sQm1JfbLLZR/gtmpODls+GIznetS/9dhEMtIWyaVDHREw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T09:32:44Z"
  mac: ENC[AES256_GCM,data:q0YrovQCsEmMd7dsup2bDXh9gqkGKb6jGsSpnKAZ22j2I1ryGqS4h9rFmmO6mPmviIS2lUNSKY4pcKS3hrX/xOUoZbYO18iorI95/UNFiKF83pbPIXLIdeEHT4HONRu5YnRForpc7fzCh0N4RYHdH6VSbbiLO7eow0jdj3lr8L0=,iv:fAHCtCHy4qXSZo6eDNfd/RNHCQYiypAfgn6OrTXJC2M=,tag:BlPU0+z/StUPwB1doSUQ/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
