apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:gu6ZUQ==,iv:nHZdAig+yYNfKj5e1cJdOw/FFxPRloFeiBbHaDtMVIU=,tag:zbvgLSqsxhyWzhD+gb0LBw==,type:str]
  hostname: ENC[AES256_GCM,data:OALNGpHMuZ68AVwxqroo6sDw,iv:n6kQipmsJfS7xBE64r/x9mzo2XrBllTUkRG0/QGq+eQ=,tag:dE5NtHqn4nVxKu0jHzh58Q==,type:str]
  secretkey: ENC[AES256_GCM,data:KcM90j6l1jHiA5tlmASg5b1jicI8avH+t7ofRv+GbKizTX4OUSGfFc4818m+IHiQYhQ=,iv:9WK+zck2qkH4ZVrhTwpPeCgO10asDRMhORgKAQ4kDp0=,tag:JMvLU7LJG11K/qoQWGfQnQ==,type:str]
  emailhost: ENC[AES256_GCM,data:q2ll/UboMBIjbL/N0I1hylhj,iv:rUJehyTb/TzFx3bepSRW7O912fM+w94ZNhptAgNIIao=,tag:vC13UTFLHIQaoMgry6Zh+w==,type:str]
  emailusername: ENC[AES256_GCM,data:pOfR1d3YvooZAJVhvEudTjxXmQ==,iv:vhljafIGWSPDsUoSHSLvmC2mUwqs125OgQ8GDu8cxHI=,tag:s1m6vttp4r57lfjkqjkmyA==,type:str]
  emailpassword: ENC[AES256_GCM,data:gaoC/UJbfuDGqEiMDOM=,iv:HBeVC1QW541NG8tIsAP73ztsFQKsSynezov7+eaNKi0=,tag:ruBpZnxOBAYqkQvhpm7G5Q==,type:str]
  emailfrom: ENC[AES256_GCM,data:a8d9vb1kRd/vgL8iRNpLWvJY2ZPDpAo=,iv:+30+28XZLC4PDoRsAyZwJf+ucNUSCADVhIFZq8N/RSs=,tag:DWdY9+jX3C1csF5v8ejI0Q==,type:str]
  backupusername: ENC[AES256_GCM,data:IaVCjPx6qQA=,iv:J0k4LVHEl+D/VOSFHLYYNY7uoNPLGQrnyAine5ZIH3M=,tag:L8VizOU8i0YDr8FfhzjGoQ==,type:str]
  backuppassword: ENC[AES256_GCM,data:lxE/QaJMjgeMbW1C,iv:6efsa4CTcSjAaM7cIfU6P/sDCTXYdgg2P26RL/dqXC4=,tag:jtG4HeNd4vfsQHaBtNqGdQ==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:VtjYiZBAcP5pAdNxOh8=,iv:27k6ElgDYCtv5m8DtodSnOJatgzkI9vA6SJC9eWy2Gw=,tag:7qv/79oSbWOursSdZ3Qh5w==,type:str]
  backuphost: ENC[AES256_GCM,data:3vVFg0yGWgAs0xs8qbpkePCVFu3omJUkBSFL91GH,iv:WcTbenueBGShZjrLfdAi1t3GyBJfTOKQpICNeRz6/eY=,tag:Y21QSvH3deWTL9MtH4z9DQ==,type:str]
  backupurl: ENC[AES256_GCM,data:THqLF/vJ79d97k63zc4OhMy96t7/0QGFxA6Wz13jjQTL5GgEnuEZsIrVyctVHeOAdXdo,iv:wSX7GFAc8+e0hNn2U4Hqp//T4OIn2rUNBpbROLwTdTE=,tag:7lAbxO3jIjoWE6EDQrsXfA==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROWxXa3Y5aEtMcFdTUlM3
        ak9VeE9teVdtQXgwN3BucXZJaG1mMms5amlRCllDa21MejFYNmowR1djWTlpZDNF
        SUt2eVc2OHdYNHlmK0h1YTk4K2htM00KLS0tIEE3OUtkdUpBaFVtNDhYR3JvYUx2
        SnVaeVhZNzYxQzRISjQwV2xuWFBwZFEKoM7eRORmAft1xVNnsne6ly9opXGCvQj3
        bsyAJ6W8W/O2VSPDtn6Q/km3V9X1aqk1QCTBUbV6CovmEn2q1GT3Qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T13:01:45Z"
  mac: ENC[AES256_GCM,data:3SaShRxzs72ngDQKsaFoGDlXZTaVLjtDBF2RRx4h2kCI3eTiMFGlteLno6JA5mqByknia1KGPgxmI8UGygHXBPoMfP9EH6ouhPpkqT5N3zbYCUwTX3iM4HxtTzK8rRCWOFb4MNnkzDk+iEeUvnQdnDHKfaFIE5A7LDZZs/XmR90=,iv:SOmMG0PSGEO2AYadKocnF8J3KvDmq7H/7cIGI+CnC3k=,tag:hxcZ314y6OeVU7eh6uCYxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
