deployments:
  - path: namespace
    waitReadiness: true
  - path: victoria-metrics-operator-crds
  - barrier: true
    waitReadinessObjects:
      - kind: CustomResourceDefinition
        name: vmsingles.operator.victoriametrics.com
  - path: victoria-metrics-operator
  - path: metrics
    when: get_var('config.base.observability.metrics.enabled')

#  - path: prometheus-operator-crds
#  - include: kube-prometheus-stack
#    when: "'monitoring.coreos.com' in apigroups"
#  - include: prometheus-pushgateway
#    when: "'monitoring.coreos.com' in apigroups and get_var('config.base.monitoring.prometheus-pushgateway.enabled')"
