---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: unifi
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: unifi-controller
      interval: 1h
  releaseName: unifi-controller
  targetNamespace: unifi-controller
  storageNamespace: unifi-controller
  valuesFrom:
    - kind: ConfigMap
      name: unifi-controller
    - kind: Secret
      name: unifi-controller
      valuesKey: nodename
      targetPath: nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: unifi-controller
      valuesKey:  ingresswhitelist
      targetPath: ingress.annotations.nginx\.ingress\.kubernetes\.io/whitelist-source-range
    - kind: Secret
      name: unifi-controller
      valuesKey: nodename
      targetPath: persistence.annotations.volume\.kubernetes\.io/selected-node
    - kind: Secret
      name: unifi-controller
      valuesKey: hostname
      targetPath: ingress.hosts[0]
    - kind: Secret
      name: unifi-controller
      valuesKey: hostname
      targetPath: ingress.tls[0].hosts[0]
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: unifi-controller
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/volumeMounts
                value:
                  - mountPath: /unifi
                    name: unifi-data
