apiVersion: v1
kind: Secret
metadata:
  name: unifi-controller
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:87vuew==,iv:JGqg2+RunfbBaHZSKL/g6kG1Pam6GrRzOdTS3r2jbCk=,tag:HnYgoUWgCq79zKMYywAApw==,type:str]
  hostname: ENC[AES256_GCM,data:s/GXe3NnGPDWMVyqz3pRQ3a8aA==,iv:MeKd+vFiLNvYSU0lg/6FKf5JpXzED/S13LZgUr5MVqs=,tag:HK32f6atJJB+zvDkNJ1RBg==,type:str]
  ingresswhitelist: ENC[AES256_GCM,data:wTmG596iw2GWfnnP+TmBBfKndmnUXy4rVLIUvfR9uQMVSe9d7f6GqhgkzSVSfnAr,iv:gb1dybiPLXcV2yCRZVnYzOEK89kTKAS50OTOeSyPN+Q=,tag:saZLWwvT9b7vwC5o6R5/hQ==,type:str]
  backupusername: ENC[AES256_GCM,data:0SV7DNfZbnk=,iv:NgeqpydDmPDgdSlkAKbPDBTHGizVJZ0HYMge2cbNa7k=,tag:U5/LJbVkXdfE5uGbLlLAWQ==,type:str]
  backuppassword: ENC[AES256_GCM,data:YEsRkuhO3jkL12Jc,iv:uOBt/ifmrBeNopUAnJxeCDYwfFpqLRAmaxpef4h2X2A=,tag:TLiI6DZnaKuM4JbIAwI0jA==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:4k/MERMtFX1O9idpG9k=,iv:jRjmoRNYCKIv+NutMOkC09f4q3iy5u96FzctZhbzLFc=,tag:OTZHhVpcyRQQGBhftNqcHw==,type:str]
  backuphost: ENC[AES256_GCM,data:UW/1kvpXwUryXMS58k0zs4ebwCipF4tleMw7Jshy,iv:sAC0aszoAkYib8bLH7rsgDDbD5KWZOtVQDu4UGmn+eY=,tag:GRvfTMUY4ToqEV3LSkH/Jw==,type:str]
  backupurl: ENC[AES256_GCM,data:XiAl74gnIy17k2C0cm0gB594ZG0WaeB28aDS+RKP/HQpn1oCQ76kbiSsTM1ym83A5zdh,iv:HhqVIu23FWheO2b5wJVB5R5m4qBEmGWduenRmaWKGqU=,tag:2XLZnXex35nOqEyKglrcjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuanhFdWY0eEd1VHpWNUtm
        b1ZaVmVPbGN0SEdhNlZKem5URjhWdUszbDEwCmVsRWdLQkx2Z1lESG9RNjJDYWZZ
        Q3I4NUcxSW5QSldXMUN6MFNxa2oyRzAKLS0tIFhNMG1SdHlwSmJrTTBhckVkVzVm
        TG5Nek5naE42MVVkRVBIR1NFaXNJbkUKJ3PTMeeqplPaQnAufw8VMKBu9e2S3lBr
        uzEFUHDmS+5Xhy9Fs9/CugE53nyVhRoxRx92MqXKBWYO0Nn0oFE7yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-18T11:57:02Z"
  mac: ENC[AES256_GCM,data:abfLAng1DZuEJ3azzI7G//o/PeSn/b/p/HJNZsCj9KMYVB5v/NlFIc8P1tFpHw1MM26+XvChjRaxRI8TWCH2a9mwe1f7pN6eJJOLzhvRMQHGtYlydUV3k7pL3gO/B7KezxakfhT2kx8VwqXDsTeWdWCSGfWYSaLuw/9xEeXjQKs=,iv:8PAIpHD4tj0u67hNmxyiFlZ+n2frq03jtC4rfLJf1Qo=,tag:qbNqGMkNAhfwCYN2swABDg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
