---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-controller
  namespace: flux
data:
  values.yaml: |
    nodeSelector:
      kubernetes.io/hostname: nodename
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/whitelist-source-range: ${ingresswhitelist}
      hosts:
        - hostname
      tls:
        - secretName: unifi-tls
          hosts:
            - hostname
    captivePortalService:
      enabled: false
    controllerService:
      nodePort: 30001
    stunService:
      nodePort: 30002
    discoveryService:
      nodePort: 30003
    syslogService:
      nodePort: 30004
    speedtestService:
      enabled: false
    timezone: Europe/Amsterdam
    persistence:
      enabled: true
      storageClass: hdd
      annotations:
        helm.sh/resource-policy: keep
        volume.kubernetes.io/selected-node: ${nodename}
    extraVolumeMounts:
      - mountPath: /unifi
        name: unifi-data
