{% for target in config.monitoring.extraTargets | default({}) }}
{%   if 'node-exporter' in config.monitoring.extraTargets[target].scrapes | default([]) %}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  staticConfigs:
    - labels:
        job: node-exporter
        node: {{ target }}
      targets:
        - {{ config.monitoring.extraTargets[target].fqdn }}:9100
{%   endif %}
{% endfor %}
