apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: proxmox
  namespace: cluster-api
spec:
  version: v0.3.4
  configSecret:
    name: proxmox
  fetchConfig:
    url: https://github.com/k8s-proxmox/cluster-api-provider-proxmox/releases/v0.3.4/infrastructure-components.yaml
