---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mikrotik-exporter
  namespace: mikrotik-exporter
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mikrotik-exporter
  updatePolicy:
    updateMode: "Off"
