---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2/manifests/crds/?ref=v2.7.2
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - resources.yaml
configMapGenerator:
  - name: flux-values
    namespace: flux
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
