---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mikrotik-exporter
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: application
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: mikrotik-exporter
      interval: 1h
  releaseName: mikrotik-exporter
  targetNamespace: mikrotik-exporter
  storageNamespace: mikrotik-exporter
  valuesFrom:
    - kind: ConfigMap
      name: mikrotik-exporter
    - kind: Secret
      name: mikrotik-exporter
      valuesKey: nodename
      targetPath: deployment.nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: mikrotik-exporter
      valuesKey: config
      targetPath: configMap.files.config.config\.yml
