---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mikrotik-exporter-resources
  namespace: flux
spec:
  force: false
  interval: 30m0s
  path: ./manifests/mikrotik-exporter/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
    - name: cluster
  postBuild:
    substituteFrom:
      - kind: Secret
        name: mikrotik-exporter
