apiVersion: v1
kind: Secret
metadata:
  name: mikrotik-exporter
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:nj5HpQ==,iv:49tqfZmS2ldI26qbvbAhUh7zv/t9h+/tAXgCF0bmV8U=,tag:grnLaUpj8E3sgduioiMaXw==,type:str]
  address: ENC[AES256_GCM,data:VtRYVxJjnmorsD34dDI00uw=,iv:xLIkr4DtDIJeADgmcu5PlOrO6QUWTMmkrVSIXBJNivg=,tag:Sv/irgEbP6x37CAFIkkwCw==,type:str]
  config: ENC[AES256_GCM,data:tVlZVUZp0SvXjKBu9ZI9ZBZy3JwioSQsGaV5sDeHFCKI715ovvLvMM3TeQ//Zg1kyIpE8IdXSQ2gWy3+QZCv+ZIdGT0VdnOmr22T1aWdJu4xNCiB89dySzWceiqH6bo2to8FJQsSJzodtyt1Hf28dGMt+gUCHUavGUApyDUUb7p9LV9/ZCBuVbgL+7/fFWLUAhfwaD5dpPS5n29mSweQTuI7CeHEr7QEXCzmbk+rfWBg3TGKZxDXwxM3ZpVM7o3kpSeY40FjVwGrswB4zmnUZPvZOdf1688X3zB9mJ1bbeCtM6L+fnzCc4BcmRYc+bKBZQySM4ylueBJPKQ/z9lB9n1kHfQrPlK05xokZShmTTX7Gb2MJXmXaCQh7Ypocr0tZAj2yRYB210V9BdkmXQiUwhNOXl2KSWoHA==,iv:1Q/q/jU1XEqab8dLFhanxQPpsmOdXs6VEcjtF9jPJBE=,tag:U7vof1pMJ8nxTiKC2LRLPg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS3FzbWJrSks4TS9CM2hZ
        Y2E1UzVIU2xoNGlnYm1pUDR4RWJaRW1LbkFrCmdGbFlsdGErVndKcWVTNFFWT3Jv
        Nk9EU2tZTXA1Qkg2bmZ2MzhlQXVlTDAKLS0tIHBvajEycUM4dTdVTFdjRll1aUxm
        WHd6Mk94cDlSYU5qak0zWnBpZW5rclkK72UVQapXMvE8EpwlwylF8ToFHr19+HKt
        jXO9tOM6Y8MBFpdsfceNilmEJW2LbhumiDVxl5PO/6D2yAnHLWhm4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-08T10:27:32Z"
  mac: ENC[AES256_GCM,data:tG1LNUy6zYzPgegEDBjiNNfzbXsFfD2vUFqsemjz+KE5tMt5qmCZPA9NMjmTa73QpxxXPXCFgk/T8og4vRyOKUxiUcbSXn7qdMZd2VWaEh/Nsc3BA/uaL3RFsmsSWlBrqQX3f40Ab4oIW8bOlPjnxvDuuz6y6duainuX4puVeJQ=,iv:Uwfjw/K1mdSmV+tMVp9GnGFM1CCmXUMMkcLkg9fYvq0=,tag:B1H1dznwmplmUw5jvpdkJA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
