---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mikrotik-exporter
  namespace: flux
data:
  values.yaml: |
    applicationName: mikrotik-exporter
    deployment:
      image:
        repository: ghcr.io/ananthb/mikrotik-exporter
        tag: v1.1.1
      nodeSelector:
        kubernetes.io/hostname: ${nodename}
      args:
        - -config-file
        - /app/config.yml
      ports:
        - containerPort: 9436
          name: metrics
          protocol: TCP
      volumes:
        config:
          configMap:
            name: mikrotik-exporter-config
      volumeMounts:
        config:
          mountPath: /app/config.yml
          subPath: config.yml
      resources:
        requests:
          cpu: 100m
          memory: 25Mi
        limits:
          cpu: 200m
          memory: 50Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    service:
      annotations:
        prometheus.io/port: "9436"
        prometheus.io/scrape: "true"
      ports:
        - port: 9436
          name: metrics
          protocol: TCP
          targetPort: 9436
    configMap:
      enabled: true
      files:
        config:
          config.yml: ${config}
