{{- $config := .Values.config | fromYaml -}}
{{- if and (kindIs "map" $config) $config.enabled -}}

{{/*
  Replace vars in $.Values.template with values from $config.
*/}}
{{- range keys $config -}}
{{- if kindIs "string" (get $config .) -}}
{{- $_ := set $.Values "template" ((regexReplaceAll (printf "{ %s }" .) ($.Values.template | toYaml) (get $config . )) | fromYaml) -}}
{{- end -}}
{{- end -}}

{{/*
  Replace vars in $.Values.template with values from $.Values.defaults
  */}}
{{- range keys $.Values.defaults -}}
{{- $_ := set $.Values "template" ((regexReplaceAll (printf "{ %s }" .) ($.Values.template | toYaml) (get $.Values.defaults . )) | fromYaml) -}}
{{- end -}}

{{- $values := dict "values" (get $config "values") -}}
{{- $template := dict "values" $.Values.template -}}
{{- $spec := merge $values $template $.Values.spec -}}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .Values.name }}
spec:
  {{- $spec | toYaml | nindent 2 }}
{{- end -}}
