{{- $configitem := printf "item:\n%s" (indent 2 .Values.config) | fromYaml -}}
{{- if kindIs "map" $configitem.item -}}
{{- $config:= $configitem.item -}}
{{- if or (not .Values.optional) (default $config.enabled false) -}}

{{/*
  Replace vars in $.Values.template with values from $config.
*/}}
{{- range keys $config -}}
{{- if kindIs "string" (get $config .) -}}
{{- $_ := set $.Values "template" ((regexReplaceAll (printf "{ %s }" .) ($.Values.template | toYaml) (get $config . | toString)) | fromYaml) -}}
{{- end -}}
{{- end -}}

{{/*
  Replace vars in $.Values.template with values from $.Values.defaults
  */}}
{{- range keys $.Values.defaults -}}
{{- $_ := set $.Values "template" ((regexReplaceAll (printf "{ %s }" .) ($.Values.template | toYaml) (get $.Values.defaults . | toString)) | fromYaml) -}}
{{- end -}}

{{- $values := dict "values" (get $config "values") -}}
{{- $template := dict "values" $.Values.template -}}
{{- $spec := merge $values $template $.Values.spec -}}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .Values.name }}
spec:
  {{- $spec | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
