{{- $releases := fromYaml (include "releases" .) -}}
{{- if kindIs "slice" $releases.releases -}}
  {{- range $index, $config := $releases.releases -}}

    {{- if not (hasKey $config "name") -}}
      {{- fail "Missing chart name" -}}
    {{- end -}}

    {{- $template := dict "values" $.Values.template -}}

{{/*
  Replace vars from $config.
*/}}
    {{- $_ := set $template "values" (include "replace-vars" (dict "template" $template.values "vars" $config) | fromYaml) -}}

{{/*
  Replace vars from $.Values.defaults.
*/}}
    {{- $_ := set $template "values" (include "replace-vars" (dict "template" $template.values "vars" $.Values.defaults) | fromYaml) -}}

{{/*
  Check for missing replaces vars
*/}}
    {{- include "missing-vars" (dict "template" $template.values) -}}

    {{- $values := dict "values" (get $config "values") -}}
    {{- $releasename := dict "releaseName" .name -}}
    {{- $releasenamespace := dict "targetNamespace" (default $.Values.spec.targetNamespace .namespace) -}}
    {{- if and (gt $index 0) (not (hasKey $config "namespace")) -}}
    {{- $_ := set $releasenamespace "install" (dict "createNamespace" false) -}}
    {{- end -}}
    {{- $storagenamespace := dict "storageNamespace" (default $.Values.spec.targetNamespace .namespace) -}}
    {{- $spec := merge $values $template $releasename $storagenamespace $releasenamespace $.Values.spec }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ (default $.Values.spec.targetNamespace .namespace) }}-{{ .name }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
    {{- $spec | toYaml | nindent 2 }}
  {{- end -}}
{{- end -}}
