{{- $configitems := printf "items:\n%s" (indent 2 .Values.config) | fromYaml -}}
{{- if not (kindIs "slice" $configitems.items) -}}
{{- fail "Expecting a list for 'config'" -}}
{{- else if and (empty $configitems.items) .Values.required -}}
{{- fail "Require at least one item in 'config'" -}}
{{- end -}}

{{- range $configitems.items -}}
{{- $config := . -}}

{{- if not (hasKey $config "name") -}}
{{- fail "Missing chart name" -}}
{{- else if not (hasKey $config "namespace") -}}
{{- fail "Missing chart namespace" -}}
{{- end -}}

{{/*
  Replace vars from $config.
*/}}
{{- $_ := set $.Values "template" (include "replace-vars" (dict "template" $.Values.template "vars" $config) | fromYaml) -}}

{{/*
  Replace vars from $.Values.defaults
*/}}
{{- $_ := set $.Values "template" (include "replace-vars" (dict "template" $.Values.template "vars" $.Values.defaults) | fromYaml) -}}

{{/*
  Check for missing replaces vars
*/}}
{{- include "missing-vars" (dict "template" $.Values.template) -}}

{{- $values := dict "values" (get $config "values") -}}
{{- $template := dict "values" $.Values.template -}}
{{- $releasename := dict "releaseName" .name -}}
{{- $releasenamespace := dict "targetNamespace" .namespace -}}
{{- $spec := merge $values $template $releasename $releasenamespace $.Values.spec }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .namespace }}-{{ .name }}
spec:
  {{- $spec | toYaml | nindent 2 }}
{{- end -}}
