{{- $configitems := printf "items:\n%s" (indent 2 .Values.config) | fromYaml -}}
{{- if empty $configitems.items -}}
  {{- if .Values.required -}}
  {{- fail "Require at least one item in 'config'" -}}
  {{- end -}}
{{- else if kindIs "map" $configitems.items -}}
  {{- $_ := set $configitems "items" (list $configitems.items) -}}
{{- end -}}

{{- if not (kindIs "slice" $configitems.items) -}}
{{- fail "Expecting a list or a dict for 'config'" -}}
{{- end -}}

{{- range $config := $configitems.items -}}

{{- if not (hasKey $config "namespace") -}}
{{- fail "Missing chart namespace" -}}
{{- end -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
{{ end -}}
