{{- $configitems := fromYaml (include "config" .) -}}
{{- range $config := $configitems.items -}}

{{- if not (hasKey $config "namespace") -}}
{{- fail "Missing chart namespace" -}}
{{- end -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
{{ end -}}
