---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - cert-manager
  - cilium
  - cloudnative-pg
  - flux
  - gitea
  - gs1200-exporter
  - home-assistant
  - ingress-nginx
  - k8up
  - metrics-server
  - mikrotik-exporter
  - mochi-mqtt
  - nextcloud
  - nextcloud2
  - prometheus
  - prometheus-pushgateway
  - rest-server
  - samba
  - storage
  - unifi-ap-exporter
  - vaultwarden
  - zigbee2mqtt
