---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - cert-manager
  - cilium
  - cloudnative-pg
  - flux
  - gs1200-exporter
  - home-assistant
  - ingress-nginx
  - k8up
  - metrics-server
  - mikrotik-exporter
  - mochi-mqtt
  - nextcloud
  - ntfy
  - prometheus
  - prometheus-pushgateway
  - rest-server
  - samba
  - storage
  - unifi-controller
  - unpoller
  - vaultwarden
  - zigbee2mqtt
