apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: vaultwarden
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:N1o+rhjRjCoaiwE5ONf7+/E=,iv:ZYA2gt28mZ/0GPniwMZMdvM3ijnsZAyD6ad3KSES/4w=,tag:PuWDdyAMg5CZjjKdpYmIWA==,type:str]
  password: ENC[AES256_GCM,data:dKEitC4AzzgxSto3TodF3CE=,iv:OK3P6UhkJmpMMORSOnpfBQAeyBp9orZDOjeZXCQrYLg=,tag:FM84Ux7JTqDLFhqjr/OB9w==,type:str]
  passwordEncoded: ENC[AES256_GCM,data:3H8As40snfZJjcVOzzEuOg7CxSDigQtT,iv:+o3CqrNtKagTUESOAbkhWYE0mLZB/zJLgP6EUkygyHY=,tag:jhrtmlWLXq1zDtCccNOPTQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WEZGME9GKy80a0V4TUJk
        RDNRS0FRVkdZdk41TVdDV0xWNkRQVUE3Y1JJCjBUOHUwSDFRWDhhemZJVTdSUFJF
        NU5DWGlYRkRkQkFCUTV3ckM2TFdwM28KLS0tIHFMVTFLUUJBUmdkZG43OGx0Kzlh
        K1V5cTFUSTRCczh2MTdieWovUkNRbjQK34IcSTy3hxNQIjN0eYkHmQb54neF7vKJ
        vQUG9oz+QGQxOCziCtjIERd0DNiguoddqu4RABRUOFVh0gjW16h1YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-05T14:46:07Z"
  mac: ENC[AES256_GCM,data:8j9iT5eEGjVWCsD9Luq/dQVBNGfkFTBOZkA2U54M2iKCHGnhar3THnQv6WhYDkTaLc28DnK+V6qYsUfVckhvhsPubjzLYKfDY7Cn8R/7Gos+qQLbFUqCMqU+X1mjJQ+OKMjeKUGEPilBVmbAZB12eqzYsczKVE0M32b9kcb/nYk=,iv:pw8IS0lRd2tcF+lPDOfJciRIhCT/2R5guzI8lpfxWI4=,tag:VKc7txqYWT2RPhwXyJg50Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
