---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vaultwarden
  updatePolicy:
    updateMode: "Off"
