apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:SVpoeQ==,iv:5HmTWX4svBTh7wm8tp10BA3ehF0r4g+yXwJxnmb+XlU=,tag:hendFFfdOYuQEVJ+AHZcuw==,type:str]
  hostname: ENC[AES256_GCM,data:KqfQjXMEu5LXeqHzqCl5vPtw8A==,iv:CcdDp7ahuRZJJF/nOHom79WM8N4Y6fOW0B3DaIAhIv4=,tag:ee/QXbimKgFg5RjDrMggeg==,type:str]
  mailfrom: ENC[AES256_GCM,data:kqQ21QU=,iv:21P129O55fjkXD759RUZulV8XveHONo/MkVyfDrjiv4=,tag:75chb4H5yYuhw7TETJMPgw==,type:str]
  maildomain: ENC[AES256_GCM,data:VrWSeoGvNxpSv3qo4A==,iv:qhbSYWZeq4p16ITdPWVWGJERW0fJC1dJM/r84y4PyGc=,tag:bJ2zdMQVxCGaNWrQzhHI+A==,type:str]
  smtphost: ENC[AES256_GCM,data:O4BM0cbBqYu/o7TOL+8FgJsLCQ==,iv:2olThZYPoS2VfFyofHaYzfk7U8XbeUEL9JiFPTQM1ks=,tag:sszzti6Kx4NLjRFf0ntcAQ==,type:str]
  smtpusername: ENC[AES256_GCM,data:gyw8JEM=,iv:ibcAxoI3kXpp/gf4cfBIcnCzFxC3F8z+2iJ5fXLJ0oY=,tag:eUniDNDug5zmsP2CE1R/sQ==,type:str]
  smtppassword: ENC[AES256_GCM,data:UWNBYt134Hs=,iv:Dl5RFrS7EX+SOm1HV4xsLNWULe3ExzM9i7Z+RZt5zq4=,tag:Tb/oAn55mYP4PsQzMHfFPQ==,type:str]
  backupusername: ENC[AES256_GCM,data:GauDwHFdo7E=,iv:tWroQ04Z9n0zIQhCsH97rzSJaV65zWCYoJCyuCk2VUE=,tag:lO8sAJy+SRel+KDUz2OT0w==,type:str]
  backuppassword: ENC[AES256_GCM,data:pG3F1sHG0hEbNboq,iv:73V1cp5Pm+8bN1OhZ+z47cyRRta1LNOmt6CVtT72k9I=,tag:N77+1ZcmwcuBEzeK/WxgZQ==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:GMRwaYJn19didiCsH1Y=,iv:5wOx8fyj/f915xlmGs3gEKMXhCQObQFo8B9G28jPTWA=,tag:qO3KTNDuzHOoEUA9W8Se6A==,type:str]
  backuphost: ENC[AES256_GCM,data:A27cA7r2YZ7eVfUd+YmiDDTIVbx7yGQt7lbgsb7J,iv:lhvAWoeTCYphDoE7xZJ8+OeP0DuylWM9TSA2dLuRc+Q=,tag:iCat88wnR/x5s+dEXFbAmw==,type:str]
  backupurl: ENC[AES256_GCM,data:mU58zyb2xqv0I1VwAHfAthHeKn/pdHCteAm2oIzL8yTYKFa+towIdRryffsaiUVQZKpq,iv:ZaV1sc00hJY8tJxDZol6okNbvlDJLNJqPaUvPK0AN0Y=,tag:f4NyGqqFc9HjkjouEV0d0A==,type:str]
  website_one_path: ENC[AES256_GCM,data:khdBhm/OCRUbGcnwe4Ygc7XwRmzhLOGv2t0YR1u4wHrZqMQXVvRq6Y+hzQ==,iv:KsVLtNpH/tT1uBhJNeeTAKAIUq7wUPNxqkM0Wejgk18=,tag:Snpj4Nk8PGkP3xuQnTLKFA==,type:str]
  website_one_hostname: ENC[AES256_GCM,data:yIOcLLYTomVMuW8l3G+/lBEV728x,iv:/xjYNSnCjgOBOKmApO8Ao3ytCn1ZYlcYa+aSOP9gqlI=,tag:4NL5KoI0so8cHROfJ6KD9g==,type:str]
  website_one_port: ENC[AES256_GCM,data:ChNT4g==,iv:jDhFGCSo2Dg6OcXr3uixM15b0L+Z8Vee3yQaQ+/IsAY=,tag:grwiMnwvZai59aglzgwmXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSHJRbHkvYVRrbzBLZ3RR
        K1ZFMytTLzYrVXQ0Z1BuZzVIM2xkNFlhczNvCmplb0w4dmtvRUEvL0p1bTBleW5E
        ZFZxd2x5L1ozMmk1TXVScis2eGZwOTQKLS0tIFlRd0ZBOTdUcHllY0x1TTZxYmJ1
        M1pZalpRV0R5azRkUzhCaG10RW9BVmMKxm9T46rScJJXv7aE0wiEPqcUZG6q8KBS
        MRMzOS7uXHGRsW3zRmOYHFlUpXDo2eCpLFURP6gYmdnG7VWJT22PrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T12:41:58Z"
  mac: ENC[AES256_GCM,data:xHjGNy+tuVRVlT9zQQ0kKpLHrrU1tpDhB6eWzYULSlQ2b2J/J69DgXMW8RS38unv3Q+PTLnJyZ7/KZtQ3KxDi22KN2Y9vwSRAnw/+u4WAW6qov4EX1W0zw+zkoucUPydAPYw3xtlDAu7ozQQEHd5gG7kZGVv2MmOYBht5y3iH5c=,iv:TydwEYlbo+b4W9DHVbCcjZ9/OikShRX9wmIiS3/uqVY=,tag:mVtSd1WieLnwE27hLDBEpg==,type:str]
  version: 3.13.3
