apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:pMfxYQ==,iv:j0cQVw8FHmz/EDjOV3nWHFXKoQt+EPrNLga+SIXDI2k=,tag:MiP66K6w5RozbBkwRxBL+A==,type:str]
  hostname: ENC[AES256_GCM,data:etc0mTemDqSIbP+LvLfZRYB10UyJXjw=,iv:7FTSsYx65R85bko3vtFSFOeHHPISYLtr9GO1xc1iZx4=,tag:t78buO0WQq/UA1laxuvHvQ==,type:str]
  mailfrom: ENC[AES256_GCM,data:vrnNTyQ=,iv:wDu421RBAW4g8aEZACxP34BzUdZz4cWLYoqwRn0qVO8=,tag:a1fY3rZXBnU86YFevljNMg==,type:str]
  maildomain: ENC[AES256_GCM,data:VvEtUtxgwBQq9/aQvw==,iv:NMbkv2QnUf2sluWT3tPxnA+r+tGCPpg6w+RcVacvwzk=,tag:nUEQcQWsjur0kEAao/e9CA==,type:str]
  smtphost: ENC[AES256_GCM,data:pUvRh1rW6mIZXzMgJ5f1zlVH,iv:YIfijydNLJXqUsFFWpDomsXYATMGraG1hgKNm+nJg9g=,tag:Aow6yEkyb2fTQWB/FCG33Q==,type:str]
  smtpusername: ENC[AES256_GCM,data:3bHavkn/dxM3n+4BTDHXX6di8Q==,iv:+epiwZ+ehojXX8NDv0mu/HKuQll5bxYk904ibT6Myxg=,tag:BG7kOW2uWBKY/8CQiJjHNg==,type:str]
  smtppassword: ENC[AES256_GCM,data:p8ucvtpaRFkrMAP3CqU=,iv:lffSSSWFzOsl+And+7ujjSk4yH4Kn970sx/C7fm1EEE=,tag:0DCLDgeoB0BtraLxHkVoRQ==,type:str]
  backuppassword: ENC[AES256_GCM,data:u/P3FJL3122/ZFTE,iv:DVDwoFnGws+Kd94jd9v5NgHmnP6LueusFcwTP6XBl+E=,tag:Kembtbb129sESI1nW0Lemw==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:ERsQ+ZRr1R5BZDuqp+8=,iv:bWQPKf3xi1QthEpkA6TPTzPwt6uY0LFkYytsL9dhyfE=,tag:2/nw/ll6FUbp9FMa712wYQ==,type:str]
  backuphost: ENC[AES256_GCM,data:m3j+8qYwp3wfj9Mcp9K51Y45SqzHpUCGYR89+GAZ,iv:6r/tcedQxpDOIrVPLhDMAv9MM0LV+TVmB642kH6b6RA=,tag:DNYa040q3To6luUy1Euhwg==,type:str]
  backupurl: ENC[AES256_GCM,data:F/2ESqzkn1erTGZFvV+7IOj3ngsiM5AIa9NZHAz9cpjMlQlppAMdOiaj4q2aNpO6bvfX,iv:CUc4mNxyNkViFAPuZ3fIHbkqsQLq6x7K3+VrJWKhlfg=,tag:0UQPXnmQKdyTTknQ0axbFw==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzclNnVER1dVpvSm5semR3
        SGZLNW5RRWNRd3lGWkEwWXRBbzhobWtnK1RzCktnbjB1K0dWd25KVGFIS0YwRmVE
        dGx2NlZRZFpKWDZFa1RKTERRV0NQaG8KLS0tIEJjSVg5ZVhGQkxzb0Z4blVsM1J3
        czBpbHRNazNudTVHU241T0Nka2dWVjgKqzRKF9LTZcS9Rxl3omItOUjsDvA6ksDs
        +oD6DtAmH9Nca5O64UVXY8iHdQh4WNIzW/4b3LIQdBYzwvLEf4mllw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T12:07:38Z"
  mac: ENC[AES256_GCM,data:SNyja9bez0Sjq5BhCLDUNXHz3V1Gfm18/kp+cpLyYwu4JRr3Dq5uhC9daE+7/577Xd0mR4dUECmkhYw79LTahaHEutTRHhm/6h1yyWF7+oflQ3IaLHp/lQYathn/VNU14ex8Wd3FcPAtpmPnIvVJK30OS6wjbMg3sQZADOUWEwo=,iv:Mm3Cmf9Pzoaf0/uLSzdty2Aq0GSwpSWvADyZvxFTQvE=,tag:IJf5lZ2+8fm0nANTbkl1sQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
