apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:QYK6aA==,iv:mq1aQuJz/pyUg8oyj0YuGDQI0syKJGj4AwoJ3eGdOiE=,tag:cNr3CH5MnDN6dCeavicsWw==,type:str]
  hostname: ENC[AES256_GCM,data:UffGhgXd0H3TBW3VplQYEoes/g==,iv:M185DtiiwAUCT7i4xDulg84lahTvyxS0sh46zWPkMCA=,tag:hWauRfr6Lw7Ihq51ZtfQiQ==,type:str]
  mailfrom: ENC[AES256_GCM,data:otI+xNQ=,iv:edJH6MUmjPZ7F+Gi9gPoHUBq3g0aTkZdqDxFNcJYC9M=,tag:I0q8yg+jcHDx1SWQAvHiBw==,type:str]
  maildomain: ENC[AES256_GCM,data:jsovEkumyUyCHDsa5Q==,iv:yEoM5QsrKpgeRTfti2bhHWZHNNd9yCSMni9s8mhajtw=,tag:4Zek2TWm8oGHKCUs7qAA/A==,type:str]
  smtphost: ENC[AES256_GCM,data:iPq5QSnpN8OnzLWrJRsRKRRlJg==,iv:u4h2ei0BOKvW4T8A021N94hpkiw4UnYdkCsJb0hyPcw=,tag:XT7Do0v+Fe4j2QhjuZecJA==,type:str]
  smtpusername: ENC[AES256_GCM,data:mZjttOg=,iv:h0kjoUdkNG1ZB+VKy9RtZWTw27UJcs4pZ0f33SCLGaE=,tag:JCNaVTTA1/i/t/2BMX8HuA==,type:str]
  smtppassword: ENC[AES256_GCM,data:weInnrp0zSU=,iv:T4pWvHixSiEYZiHFj9/YmDC8MEWxwuwfyN36EGVdqvI=,tag:HXMQzDjCz2HqHsfGAaeiZg==,type:str]
  backupusername: ENC[AES256_GCM,data:QeRRHX1Uc6M=,iv:jh3pbJN2iX5963C+t1IEjj3riClaD/WGAqJ5yDdFVUE=,tag:oGZ/A64aJ4bdHyukQB9MXQ==,type:str]
  backuppassword: ENC[AES256_GCM,data:TH+Friv4Ve1FupFv,iv:mjQ/glJ/tmU2lYQPhNsQC08YhtKlnheE4Y+ZJkWwZDo=,tag:QFphN1NX6YYAz7/yy79LFg==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:Eaas7rnSRTxaNS2hp1Y=,iv:qD5ZDXFYQ3ue0uDASHunVeWaDv8Krt2IgpF+3SC7Z2A=,tag:E0ZowWFuLiJfmpaeGbnQAg==,type:str]
  backuphost: ENC[AES256_GCM,data:i4+PJ1btizDVx8LdLKdJW2WiqkjS9Hk7gwW2bx/E,iv:2f551zA44MfeEIwsiTsuRiCKbGDlLN349Dnw/qKC5rU=,tag:Wb3Uu7UrPWOdfKpl/fV6zg==,type:str]
  backupurl: ENC[AES256_GCM,data:gDXgfuBt6Zn44sFOSd7DrcySM4nRyvYkuPPMtpZCuBD4Q6Rt3MLaBlG1SMyVrtCWtO3O,iv:LCWdzWZzjE/GstLkHST7J5BCWblFF75nNewG9iWRevg=,tag:0X9SpdUz3jRRNMJvCOB5mw==,type:str]
  website_one_path: ENC[AES256_GCM,data:0XaCOO2NBpdPw1iv0MI1l8ggEublJvitIhUVrqfmG50n1kCgJGpvVEK84V6QfdZUEfi/PMB1pTMC,iv:HXzRbjrkEbkbPoXIBc04CIcOJke+5EDv36UR6/HbCHY=,tag:Wli+g2eDQP+ul5J8ujDnmQ==,type:str]
  website_one_hostname: ENC[AES256_GCM,data:CrRPcewRtjP4Wh/5eIgZIh6Dt6Da,iv:sQC5LMpTGsHEiaCsUlheo/A5ezOxa/P1t+MxZ+GS+ck=,tag:dJZj9vt8VpSeRrqpXKIVVg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TUtiMFlrRy91L1hCZUd4
        TXpvV3ZMYTZlWEJJbkFqd2lISDQ0bW5TVGxNCit3RUFzODdxT2tsU1lWelNYTHA5
        blVaT3lYWkgwMndlcURlQWlIQkNIZkEKLS0tIFJ2RzE4eWNvM3FvbThVT0NxeU9o
        M0tIb2dXRXk4N3RWRlNsdHV3cXZVVzQKallDK4h5Jpd9VKfSgkuWjwXbK5JNm99l
        YAzMTaM+861mW9ZWnfQ0V+0qKLrneLF69sY3ASOA+NaBN4wunuaRLw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T11:58:45Z"
  mac: ENC[AES256_GCM,data:3wHHBGP8+BV4nkVnAp/YZgbaoh7hKMsFPn3n7Jom/CLSpJ82afTrzUHL16Z/Qmtv2uJdGwpZQemK9zfVNm22CYk4gsDKH/K6fAbPEuJCX8iF/MQi+XcD2XYfm3wZ8JmeZqd73LGdvQPBJQTxKs2KrkFuMsmkQ1ID9KYVucWGQvE=,iv:TjAMWUz6J0KyKyin6NdA8Hat73KK+yLI1saJaagwcpg=,tag:TTU2AlTI8H83d2lR2hdGBw==,type:str]
  version: 3.13.3
