apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:atXJQw==,iv:v2L+u50UpRK2mhMFiJ6nGKV/uZOOWQpdTQUoZzEiByg=,tag:ZH7+3pyTxx4j4uq8HIIHOA==,type:str]
  hostname: ENC[AES256_GCM,data:a9WA2wl+O7TFEx50kVpQ67KzIw==,iv:ypU+lGLTcFYSnZILskOSIuVWYIJC+xywBOsPZtHCgPU=,tag:Yp9bdCZOMn6thdLlF1yJiA==,type:str]
  mailfrom: ENC[AES256_GCM,data:NFEn+ac=,iv:NFCNeRnY+/9Sp9op7AStnG/X6ZdseH+yWNarHH/ijbQ=,tag:UNQzOgpCteuCb+c1udHYAw==,type:str]
  maildomain: ENC[AES256_GCM,data:Q9Tt5EKJNbYUhzmqKw==,iv:r1boDc29fPmSfPWxuhbfxETCanZ/RJFZN6aNwrVQRI8=,tag:xqCUd0cv7Qj0ycYrfGTHqQ==,type:str]
  smtphost: ENC[AES256_GCM,data:jQNX5celwqQpGLW4klnwPcbmMQ==,iv:kmcoykIjUfXITh5xtLerZERfRUEW0iKcDvSLFj/qODg=,tag:JIj3Aw3rsajO1uid1RuHjA==,type:str]
  smtpusername: ENC[AES256_GCM,data:ViSYdyQ=,iv:8Y6lxorbrBSzC6fWuXn926AJb2cHu6p/9UMPS2Y8Jjs=,tag:gkIlMboAIpaeg6KL0nqFwg==,type:str]
  smtppassword: ENC[AES256_GCM,data:sFke7tStsZc=,iv:Gt6emLjpNvCyh069QPz7Y/0j4tLkYbr2wlMuKfa9dtI=,tag:aUEkrcu47JlAAeyzLmb0rQ==,type:str]
  backupusername: ENC[AES256_GCM,data:ONolh7odAMU=,iv:EjIcqa3NJYihY/odIBszDTd3TJiM0WjA6KlXc3Zl+Dg=,tag:QMkb+1pgQLVYCtk8S9+gsQ==,type:str]
  backuppassword: ENC[AES256_GCM,data:uk9DFTrCxjH6m2xJ,iv:/FH6chHEROEqtEYuB6UZQ02XkIj4ppXqahbmigpAX4k=,tag:DP+YVKBjDR6ADitwCoUyjw==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:pB+qQNlbz5m3Nsfg7BM=,iv:GvESd8eSGieD3ohWOW9fWx/e7hQS/Iri9dk15LwafLY=,tag:MsujQ/U8oCq7aI7OIGg2fQ==,type:str]
  backuphost: ENC[AES256_GCM,data:m41Fau9wvnrG9l5azPvpXcBUPHJdLKrv69GlVJkf,iv:RF+VZZ4lb5vlvADuxSRViGeqCwRMtOeXYPA2aGUUPDw=,tag:eiuVuts/oJtOIc9bU2yhSg==,type:str]
  backupurl: ENC[AES256_GCM,data:cZ/T1hukPBLMEW+FMtWROCxM/lsQjVI3IP57fEwIEVFvgUpMHp9XmN3WfNqlnHf3nLw7,iv:mlEOhT6fWIzGhA1WZVav+yhTTurco2q1jfNvhHufJTo=,tag:d2A6hlooMSup7WDlZ7BtDw==,type:str]
  website_one_path: ENC[AES256_GCM,data:pK/stju4aYWJPbCLyv44onMMsv7Znsb9Vo+coPB5YIvmgBe+W3mRJ+Ej2w==,iv:zLfKLltIvbsU99UH9EJmwLtzFKgMWLXeYwVA5ya8XqI=,tag:k1i6o6OfY3Gl5QExDXLFDw==,type:str]
  website_one_hostname: ENC[AES256_GCM,data:k6ify/aaeZF4UiLQQs1HeFVCAQ0l,iv:9ccFycUxi4X2iAIehKY8BmI9GXmcurWrINqapHr0iGI=,tag:1tc2c9w3kx06QIAFtygjfg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxazQyMERqNUtTbHdqOWw3
        MzZMYzlzdHFMRmlTM3o5NWVjWXdRZWxzQ0RzCkVBeXRmcVlVQmNxMkZTR0ZPbU1V
        VjBqSjk4NjdRRUNrT3l1ZVJhdDl6WWsKLS0tIFh3ZzIwT2QwNndUTnBBb3hTRGY0
        K0RraTZIQ3lrS2NHbW1wMUc4UkllclUKKKCkv48av+x2BAiW7tfOG3rG0Bp2AHN/
        9kTqT+LCiWWMqbi9BPI1BULKve9Y/ukrKi9WmffD3j+I5r2fc0NLbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T12:47:55Z"
  mac: ENC[AES256_GCM,data:Mir1Cmk7b8Z0uc9MyOMVQS+R02gX5ZVVlkasHjhUarT8QumbxzsfSgiY+9GmGRPZKcjGru7HrcRWY+tNhESY/tX0mzr0WVE8cgzM/fBjjj6mYw8v+LxL+/8zquzCBJuE34oqmuUp38HB2rxxW+q8yqEg5dstQUlFLu2RYkz7rK4=,iv:wDEhmlR1MHfmiMcoTaxYkoVwIPegqy7GNEKusYiLcFo=,tag:/6+zd3uIsdufXLsD87kMNw==,type:str]
  version: 3.13.3
