---
image:
  repository: nextcloud
  tag: 32.0.1-apache
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
  tls:
    - secretName: nextcloud-tls
      hosts:
        - ${hostname}
nextcloud:
  host: ${hostname}
  configs:
    extra.config.php: |-
      <?php
        $CONFIG = array(
          'overwriteprotocol' => 'https',
          'default_phone_region' => 31,
          'maintenance_window_start' => 11,
        );
      ?>
    proxy.config.php: |-
      <?php
        $CONFIG=array(
          'trusted_proxies' => array(
            0 => '127.0.0.1',
            1 => '10.0.0.0/8',
          ),
          'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        );
      ?>
  mail:
    enabled: true
    fromAddress: ${mailfrom}
    domain: ${maildomain}
    smtp:
      host: ${smtphost}
      secure: ssl
      port: 465
      authtype: LOGIN
      name: ${smtpusername}
      password: ${smtppassword}
  strategy:
    type: Recreate
    rollingUpdate: null
cronjob:
  enabled: true
persistence:
  enabled: true
  annotations:
    volume.kubernetes.io/selected-node: ${nodename}
  storageClass: hdd
startupProbe:
  enabled: true
  failureThreshold: 360
nodeSelector:
  kubernetes.io/hostname: ${nodename}
internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: postgresql-rw.nextcloud.svc.cluster.local
  existingSecret:
    enabled: true
    secretName: postgresql-app
    usernameKey: username
    passwordKey: password
    databaseKey: dbname
externalRedis:
  enabled: true
  host: valkey.nextcloud.svc.cluster.local
