---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: vertical-pod-autoscaler
      version: 9.9.0
      sourceRef:
        kind: HelmRepository
        name: vertical-pod-autoscaler
      interval: 1h
  releaseName: vertical-pod-autoscaler
  targetNamespace: vertical-pod-autoscaler
  storageNamespace: vertical-pod-autoscaler
  valuesFrom:
    - kind: ConfigMap
      name: vertical-pod-autoscaler
