---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vertical-pod-autoscaler-resources
  namespace: flux
spec:
  force: false
  interval: 30m0s
  path: ./manifests/vertical-pod-autoscaler/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
    - name: cluster
