---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: application
      version: 6.5.0
      sourceRef:
        kind: HelmRepository
        name: ntfy
      interval: 1h
  releaseName: ntfy
  targetNamespace: ntfy
  storageNamespace: ntfy
  valuesFrom:
    - kind: ConfigMap
      name: ntfy
    - kind: Secret
      name: ntfy
      valuesKey: baseurl
      targetPath: deployment.env.NTFY_BASE_URL.value
    - kind: Secret
      name: ntfy
      valuesKey: nodename
      targetPath: deployment.nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: ntfy
      valuesKey: nodename
      targetPath: persistence.annotations.volume\.kubernetes\.io/selected-node
    - kind: Secret
      name: ntfy
      valuesKey: hostname
      targetPath: ingress.hosts[0].host
    - kind: Secret
      name: ntfy
      valuesKey: hostname
      targetPath: ingress.tls[0].hosts[0]
