apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux
spec:
  interval: 10m
  path: "../base"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube
  postBuild:
    substituteFrom:
      - kind: Secret
        name: secrets
