apiVersion: v1
kind: Secret
metadata:
    name: secrets
type: Opaque
stringData:
    cluster.endpoint: ENC[AES256_GCM,data:9XjaXPxfU44zPaYB4g==,iv:Yg64Qy5krgk+am6EteEjH7GleekJD2ryOkHFehbUEDM=,tag:EMPXtcvZ27wn19JCdd+K1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-07T09:50:10Z"
    mac: ENC[AES256_GCM,data:zds7Ljylr3qxS5eg/RsCVqMUl1rSYWN0X7cXSz7O1IvMuhZltEYJgaA6tka8XVW0Tx1aBVyb60Lxt202cF/4cW4kAUu7gXv4m5AH5UA+Ta9NY4ATK7cyBMjz1Vij6ZQELTxR9LwDAnUpb3f8iz0b7/CpSZ7tXNlXStBNxWxtkIU=,iv:vG1ZiWWSgWYbIa+eyEjCbT9DOwzQ39EQvCtZv1aWyHw=,tag:KQuaVRskaqbWKOEx9xurDA==,type:str]
    pgp:
        - created_at: "2023-07-07T09:50:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3F6ciqgn+yoARAAjYGIRAWIRkzpZJayXDPqbmL7LIJiDuugRoB4IPmb9RII
            P9W40+/mlnZBayPsG5qZCOTRbLZM6/V4p1m2yuWsL7XZXnD6AXsiTBFMntORW9fn
            0tnxcTxqw7fCv+wWoRdEedDj7JP8oZYiBYCT+kCxnEr+scZLTLB6+E9gtFtLpqYi
            pQVL9yokfUQNq6P/SkiuxHjhjNAGrjgqWXFkPYoT7tcu7J2yhuJ3c+4/o5fV4Frf
            +NDzvcBYtlU2zQo5WKuMGdGpZxrqjQXHonlJ4kxH3q5eigysl36mcFiZMsVBe4II
            Dr/67+4Cd2i9cqRJphS6f/FT+sPgu5dDOS86aZTolNK9URztQ3ELJG5/7Dct4N1I
            /eByzmQRu2UGhWNpNaxJQDevwhQO7348JeRizeuxekh0wS1e5zwazMuzvHJEd4U3
            z3X0fv4y+VMyBLaEHGNvZQQ0DuWhHFd4iwKrPAKrx4k8orlCteMSkmIqs1LcrZCy
            l0U9Ug1KSnfQ50aZUT9NChJBXkjd/Q1stx/6BMW7fgj8FcNbfQC6wUxAHOVFU62t
            0XY2p7eXagKzUTDoZz4uZAVkq3Cca1AhlBcgPS5Z6fNZLD0o2HHptghDiP5MA0fc
            LTXQ4ry6RQZamrvXl6jN7AfAkSH3l40clL1X+Z5xrLefDnHUnSlbtUNCE0z2XLfS
            XgEDZnIBk+LGnEpLqPQqDKbv8gFGaLzcfCcYfAef/5nFzvxL/y0KbyGaIVH3oI5O
            Paod4hkg7SgOfYVoffX4ZxGSy93kRtsmdvADKDH1dhN5OueN3Pv5r++/IFenXYA=
            =u4Fj
            -----END PGP MESSAGE-----
          fp: 905CCEEEDF2A4C8D52F5DE8D9E760ECEE16736E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
