{% if get_var('config.base.kubevirt.manager.authentication.enabled') %}
apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-manager
  namespace: kubevirt
type: Opaque
stringData:
  auth: "{{ config.base.kubevirt.manager.authentication.auth }}"
{% endif %}
