metrics:
  enabled: true
  serviceMonitor:
    enabled: {{ 'monitoring.coreos.com' in apigroups }}
  prometheusRule:
    enabled: {{ 'monitoring.coreos.com' in apigroups }}
    rules:
{% raw %}
      - alert: ValkeyDown
        annotations:
          summary: Valkey instance {{ "{{ $labels.instance }}" }} down
          description: Valkey instance {{ "{{ $labels.instance }}" }} is down.
        expr: |
          redis_up{service="{{ include "valkey.fullname" . }}-metrics"} == 0
        for: 2m
        labels:
          severity: error
      - alert: ValkeyMemoryHigh
        annotations:
          summary: Valkey instance {{ "{{ $labels.instance }}" }} is using too much memory
          description: |
             Valkey instance {{ "{{ $labels.instance }}" }} is using {{ "{{ $value }}" }}% of its available memory.
        expr: |
           redis_memory_used_bytes{service="{{ include "valkey.fullname" . }}-metrics"} * 100
           /
           redis_memory_max_bytes{service="{{ include "valkey.fullname" . }}-metrics"}
           > 90 <= 100
        for: 2m
        labels:
          severity: error
      - alert: ValkeyKeyEviction
        annotations:
          summary: Valkey instance {{ "{{ $labels.instance }}" }} has evicted keys
          description: |
             Valkey instance {{ "{{ $labels.instance }}" }} has evicted {{ "{{ $value }}" }} keys in the last 5 minutes.
        expr: |
          increase(redis_evicted_keys_total{service="{{ include "valkey.fullname" . }}-metrics"}[5m]) > 0
        for: 1s
        labels:
          severity: error
{% endraw %}
