apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwardenrs-wrapper
spec:
  interval: 1h
  releaseName: bitwardenrs-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: cert-manager
    - name: clusterissuers
  values:
    name: bitwarden
    spec:
      interval: 1h
      releaseName: unnamed-bitwardenrs
      targetNamespace: unnamed-bitwardenrs
      install:
        createNamespace: true
      chart:
        spec:
          chart: charts/bitwarden
          version: 0.2.0
          sourceRef:
            kind: GitRepository
            name: bitwardenrs
          interval: 1h
      values:
        deployment:
          image:
            repository: bitwardenrs/server
            tag: 1.18.0
            pullPolicy: IfNotPresent
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: bitwardenrs
      targetPath: config
