---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cilium
  namespace: cilium
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: cilium
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cilium-operator
  namespace: cilium
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cilium-operator
  updatePolicy:
    updateMode: "Off"
