---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup
  namespace: samba
spec:
  backend:
    repoPasswordSecretRef:
      name: backup
      key: password
    rest:
      url: ${backupurl}
      userSecretRef:
        name: backup
        key: username
      passwordSecretReg:
        name: backup
        key: passwordEncoded
  backup:
    schedule: "@weekly-random"
    activeDeadlineSeconds: 14400
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    promURL: http://prometheus-pushgateway.prometheus-pushgateway.svc.cluster.local:9091
  check:
    schedule: "@weekly-random"
    activeDeadlineSeconds: 14400
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    promURL: http://prometheus-pushgateway.prometheus-pushgateway.svc.cluster.local:9091
  prune:
    schedule: "@monthly-random"
    activeDeadlineSeconds: 14400
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    retention:
      keepDaily: 7
      keepMonthly: 12
      keepYearly: 10
  podSecurityContext:
    fsGroup: 0
    runAsUser: 0
