apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: samba
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:Nx66X7f8U6JBNyKLqW1qApM=,iv:wtvnEXunlDswDttafCEpr+AVAQhJ+5N2+21HxUqlDNU=,tag:J+qx5WGSbWZBCT0mhSfAHA==,type:str]
  password: ENC[AES256_GCM,data:sFuEG7Rsk6VPz0mKnuP0snQ=,iv:Ww7XaUxC/SY4les46dt8l0GPiDufWH+VA3mlbZdDJEU=,tag:sv4SDmktuIvM0KnEP2nfiQ==,type:str]
  passwordEncoded: ENC[AES256_GCM,data:wzkI1NDgl6tzxYwI7NAre5xuNu5+FpGI,iv:GMk7ar0S5osfLPA22piGnoE901a598ChZJXo+tjdT+w=,tag:qFqeT7AvCq3DFdt4LPjSMg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYanh0Zmo4OXNrVHpydE5J
        ejYwekFXTzJ2YndVcEg5cWdZNkJKNlNNb3dJCklXZitROTBvQ3I1RVdPTU5kSjEz
        aXEvU0YrVnJWdDdSWEcvMnE3T0JOeE0KLS0tIGlnSFNyb2NBL1pYSUNOb0lGN1Zs
        VDNzV3BPZlpSMlhFM01zRDVhYXRKQjAKywQ5obRB4oMgVtvipCtq2Dq2wefVeGmw
        QQlahy/jptYcS/x5n1joVudfYQhHxzq8FxBsF90S2YGODZkLgpTzbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-04T11:41:54Z"
  mac: ENC[AES256_GCM,data:kYFPnsMSq9NkuzEfvD/vMuFFhb8lCu+IAPOjLS9vlGP09d595TUFP3BuUHqmRzYtWxnkm2lS/kNvYRSeLNdoFxR1Btebgy0Jmt6QRpmf5joBRpq19IiiMwFcc08YZaP2jhLy21ch0EYUUE7JjQr/5U8Gp+GMW8B9iWqGNJtNz7Q=,iv:Hf+3W2ByfJOXvLUad736C3BjnBUchQf3t4huCsVooH8=,tag:MKhAy/2SrwvL/wgm1H5/ew==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
