---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: samba
  namespace: samba
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: samba
  updatePolicy:
    updateMode: "Off"
