apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden-wrapper
spec:
  interval: 1h
  releaseName: vaultwarden-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  dependsOn:
    - name: nfs-subdir-external-provisioner-wrapper
    - name: cert-manager
    - name: clusterissuers
  values:
    name: vaultwarden
    configKey: vaultwarden
    spec:
      interval: 1h
      chart:
        spec:
          chart: vaultwarden
          version: 0.5.1
          sourceRef:
            kind: HelmRepository
            name: vaultwarden
          interval: 1h
      releaseName: unnamed-vaultwarden
      targetNamespace: unnamed-vaultwarden
      install:
        createNamespace: true
    defaults:
      issuer: letsencrypt-staging
    template:
      database:
        type: sqlite
        wal: false
      vaultwarden:
        domain: "https://{ var:host }"
        allowSignups: false
      ingress:
        enabled: true
        host: "{ var:host }"
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "{ var:issuer }"
        tls:
          - secretName: vaultwarden-tls-secret
            hosts:
            - "{ var:host }"
      persistence:
        enabled: true
        size: 1Gi
        accessMode: ReadWriteOnce
      image:
        pullPolicy: IfNotPresent
        repository: vaultwarden/server
        tag: "1.24.0"
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: config
      targetPath: config
