apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden-wrapper
spec:
  interval: 1h
  releaseName: vaultwarden-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  dependsOn:
    - name: nfs-subdir-external-provisioner-wrapper
    - name: cert-manager
    - name: clusterissuers
    - name: ingress-nginx
  values:
    name: vaultwarden
    configKey: vaultwarden
    spec:
      interval: 1h
      chart:
        spec:
          chart: ./
          version: 0.5.0
          sourceRef:
            kind: GitRepository
            name: vaultwarden
          interval: 1h
      install:
        createNamespace: true
    defaults:
      issuer: letsencrypt-staging
      admintoken: ""
    template:
      image:
        tag: "1.27.0"
      domain: "https://{ var:host }"
      adminToken: "{ var:admintoken }"
      signupsAllowed: false
      ingress:
        enabled: true
        additionalAnnotations:
          cert-manager.io/cluster-issuer: "{ var:issuer }"
        hostname: "{ var:host }"
        tlsSecret: vaultwarden-tls-secret
      storage:
        enabled: true
        class: "nfs-client"
      smtp: {}
      podSecurityContext:
        fsGroup: 65534
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        readOnlyRootFilesystem: true
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: config
      targetPath: config
