apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden-wrapper
spec:
  interval: 1h
  releaseName: vaultwarden-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  dependsOn:
    - name: nfs-subdir-external-provisioner-wrapper
    - name: cert-manager
    - name: clusterissuers
    - name: ingress-nginx
  values:
    name: vaultwarden
    configKey: vaultwarden
    spec:
      interval: 1h
      chart:
        spec:
          chart: vaultwarden
          version: 1.0.0
          sourceRef:
            kind: HelmRepository
            name: vaultwarden
          interval: 1h
      install:
        createNamespace: true
    defaults:
      issuer: letsencrypt-staging
      admintoken: ""
    template:
      vaultwarden:
        allowSignups: false
        admin:
          enabled: true
          token: "{ var:admintoken }"
      ingress:
        enabled: true
        host: "{ var:host }"
        annotations:
          cert-manager.io/cluster-issuer: "{ var:issuer }"
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: vaultwarden-tls-secret
            hosts:
              - "{ var:host }"
      persistence:
        enabled: true
        storageClass: "nfs-client"
      image:
        tag: "1.28.1"
      securityContext:
        readOnlyRootFilesystem: true
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: config
      targetPath: config
