apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${name}-oauth2-proxy
  namespace: flux
spec:
  interval: 1h
  releaseName: ${name}-oauth2-proxy
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: cert-manager
    - name: ingress-nginx
  chart:
    spec:
      chart: oauth2-proxy
      version: 6.23.1
      sourceRef:
        kind: HelmRepository
        name: ${name}-oauth2-proxy
      interval: 1h
  targetNamespace: ${namespace}
  storageNamespace: ${namespace}
  values:
    config:
      clientID: ${oidcAlertmanagerClientID}
      clientSecret: ${oidcAlertmanagerClientSecret}
      cookieSecret: ${oidcAlertmanagerCookieSecret}
    extraArgs:
      provider: oidc
      provider-display-name: "Authentik"
      redirect-url: https://${alertmanagerHostname}/oauth2/callback
      oidc-issuer-url: ${oidcAlertmanagerIssuerUrl}
      cookie-secure: false
      allowed-group: ${oidcAlertmanagerGroup}
      email-domain: "*"
      set-authorization-header: true
    ingress:
      enabled: true
      className: nginx
      hosts:
        - ${alertmanagerHostname}
      tls:
        - secretName: ${name}-alertmanager-tls
          hosts:
            - ${alertmanagerHostname}
      annotations:
        cert-manager.io/cluster-issuer: ${issuer}
        nginx.org/mergeable-ingress-type: minion
        nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
      path: /oauth2
