---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgresql
  namespace: nextcloud
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: postgresql
