---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-pushgateway
  namespace: prometheus-pushgateway
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
  ingress:
  - toPorts:
    - ports:
      - port: "9091"
        protocol: TCP
