apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 4.18.1
      sourceRef:
        kind: HelmRepository
        name: node-exporter
      interval: 1h
  releaseName: node-exporter
  targetNamespace: node-exporter
  storageNamespace: node-exporter
  values:
    rbac:
      create: true
      pspEnabled: false
