apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: authentik-{{ app.name }}
type: Opaque
stringData:
  username: "{{ config.base.k8up.username }}"
  password: "{{ config.base.k8up.password }}"
