apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: cert-manager
  namespace: ingress
spec:
  groups:
    - name: cert-manager
      rules:
        {{ rules.certmanager.groups[0].rules | to_yaml | indent(8) }}
