apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-wrapper
spec:
  interval: 1h
  releaseName: nextcloud-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      version: 1.3.0
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: cert-manager
    - name: clusterissuers
  values:
    name: nextcloud
    spec:
      interval: 1h
      releaseName: unnamed-nextcloud
      targetNamespace: unnamed-nextcloud
      install:
        createNamespace: true
      chart:
        spec:
          chart: nextcloud
          version: 2.5.1
          sourceRef:
            kind: HelmRepository
            name: nextcloud
          interval: 1h
    defaults:
      issuer: letsencrypt-staging
    template:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "{ var:issuer }"
        tls:
          - hosts:
            - "{ var:host }"
            secretName: nextcloud-tls
      nextcloud:
        host: "{ var:host }"
        username: "{ var:username }"
        password: "{ var:password }"
      cronjob:
        enabled: true
      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 8Gi
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: nextcloud
      targetPath: config
      optional: true
