deployments:
  - path: operators
  - barrier: true
    waitReadinessObjects:
      - kind: CustomResourceDefinition
        name: kubevirts.kubevirt.io
      - kind: CustomResourceDefinition
        name: cdis.cdi.kubevirt.io
  - path: resources
    waitReadiness: true
#  - path: kubevirt-manager
