apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name}-values
  namespace: flux
data:
  values.yaml: |
    loginRequired: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: ${issuer}
      hosts:
        - host: ${hostname}
          paths:
            - /
      tls:
        - secretName: ${name}-tls
          hosts:
            - ${hostname}
    redis:
      architecture: standalone
