apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: haproxy-ingress
spec:
  blocks:
    - cidr: ${ip}/32
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: haproxy-ingress
      io.kubernetes.service.name: haproxy-ingress
