apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    imagePullPolicy: IfNotPresent
{% if get_var('config.base.kubevirt.storage_class') %}
    vmStateStorageClass: {{ config.base.kubevirt.storage_class }}
{% endif %}
