---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant-resources
  namespace: flux
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m
  path: ./manifests/home-assistant/resources
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
    - name: cluster
  postBuild:
    substituteFrom:
      - kind: Secret
        name: home-assistant
