---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
  namespace: flux
data:
  values.yaml: |
    nodeSelector:
      kubernetes.io/hostname: nodename
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/server-snippet: |
          if ($request_uri = /api/prometheus) {
              return 403;
          }
      hosts:
        - host: hostname
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: home-assistant
          hosts:
            - hostname
    persistence:
      enabled: true
      annotations:
        helm.sh/resource-policy: keep
        volume.kubernetes.io/selected-node: ${nodename}
      storageClass: ssd
    serviceMonitor:
      enabled: true
