---
nodeSelector:
  kubernetes.io/hostname: nodename
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: haproxy
    cert-manager.io/cluster-issuer: letsencrypt
    haproxy-ingress.github.io/config-backend: |
      acl bad path_beg /api/prometheus
      http-request deny if bad
  hosts:
    - host: hostname
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: home-assistant
      hosts:
        - hostname
persistence:
  enabled: true
  annotations:
    helm.sh/resource-policy: keep
    volume.kubernetes.io/selected-node: ${nodename}
  storageClass: ssd
serviceMonitor:
  enabled: true
