apiVersion: v1
kind: Secret
metadata:
    name: monitor
    namespace: flux
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:Tp/WZCi9QA==,iv:DzArmcTuqqKkXKO8Zz6gnGgulb59B4OlonFMGxKo8os=,tag:tmWcNLNImZ9EYOKLpKG3cQ==,type:str]
    namespace: ENC[AES256_GCM,data:x/ub94OBeA==,iv:PYfnVFuOk6X0dzacEw4GdbSC7D66uHOiccknYhNs028=,tag:VzE6jCsBc3D3iIBy1uZARg==,type:str]
    issuer: ENC[AES256_GCM,data:zDChmNKdx7LQgXk=,iv:JRiIyb7esrnwI0DZeA8H9g+pZI5UoDsabI9wHylwhEw=,tag:I1LXzdUsK8S/GlX6XcueuQ==,type:str]
    adminEmail: ENC[AES256_GCM,data:nSYAvlF5RqCssHQa2Ud4jSVirQ==,iv:TDTBd4eqmftxEXtjHsjbwaFxK9+HrvZzg8B8VkHEZA0=,tag:v1khVtWXn9rhXXk3Enn1Cw==,type:str]
    alertmanagerHostname: ENC[AES256_GCM,data:oA59MuPvOmi9//VFHoo2QFGEsEaR67OLeTo=,iv:WPbE+bD4KrUUV2ELv0NG0nedDSLxdaG2ftpWz6kHNfM=,tag:1lIc1ysgiE/VOdwajO3E6A==,type:str]
    grafanaHostname: ENC[AES256_GCM,data:XMZAdnlj6vTnyB3sZKpxQgzF8aR4,iv:38F1bEnyEkuEMKX6kVnhibtkQMgjizK2kAWi4YryCvE=,tag:hXcXepb7VXRfLtk+fIuC6g==,type:str]
    oidcAlertmanagerClientID: ENC[AES256_GCM,data:dFE1Wdg2gUlQmHG7tLuMQ++51AeQckzgcyZf3z0UHEUhk8EjGrYiEg==,iv:95qVH1DEL4y8Tr1fIFxmdBg/NWZY92KWnRG7TmZ0aZA=,tag:D2xzYYz11UZ9Hi/QscXcOw==,type:str]
    oidcAlertmanagerClientSecret: ENC[AES256_GCM,data:6yDmz7lbZu64ImuXHkKsTpO8u6t3QC8HUNRE8MwjPyZhtOKdt3fT+swyJZtJ87n2HfbpiF43QF9OQNQq+TYXhDK5jPYGBD8X2AsdWBDIYRfURU5Hop3jUlCw+QZ72Ffcbet8HvVgrx0zf1ESKCzi69pv7H5ZGCqSrlwdMHk4IIg=,iv:wKvfllFuumO2vCdMbynqoL4LDv8KB1tfx0XaH6n/V+I=,tag:pwxHj5D1oNl76fB69wN+1A==,type:str]
    oidcAlertmanagerCookieSecret: ENC[AES256_GCM,data:hJ69nvaL4uhL0ogj3r/c6w==,iv:FwPUz5+XDy8irDyf3qfGn1Z+LtpoTTVfy6I7+6eCzLY=,tag:uVvXos3ojyKpGBvZFFWFyQ==,type:str]
    oidcAlertmanagerGroup: ENC[AES256_GCM,data:hwsGE+o=,iv:gfresg+OzWb2tU01fgOMYk0+WBPlkZtYJDu5eOVISPI=,tag:6G0JSRfbHQGR4a7dpI7Csw==,type:str]
    oidcAlertmanagerIssuerUrl: ENC[AES256_GCM,data:ObTk9MIexCrcs/18oMk1KyPF4+cma87aWMJwAfUBscYobDL4nyLNF0mV4G/xA5phohyeW6Q=,iv:2wcWjO0VVvqgh+Nb/Mnum0l3B1anDXJKkZk0puyebHQ=,tag:lS2bu0hZlRzSakZMaTHCyA==,type:str]
    oidcGrafanaClientID: ENC[AES256_GCM,data:dmTGtK1eSNSTX56kmhXv0JwCSPkPq0SDTfhpT/xLv3sbDyHizr3DHA==,iv:FCDLoTu1yqxhJ6Li/38lrocHCKR3HiLZk5sdQqbE8GQ=,tag:nouvr31CzrGaXsVMIs5vaA==,type:str]
    oidcGrafanaClientSecret: ENC[AES256_GCM,data:lseaExB00OnuldOaqqOClo6KrsULiAoWzE6rYpVaacDnBw/7xKoUxW4IBQ2K+FTE6l+/vSX0Hf0LZtNUb31LHCO9FdQQgxqRAt8AKSMY/h5NKwQzDipiorrjeyw4BkK/FXhIstn3m8fJd+IebChzn3VBicO6crp93I0fPQEMeGA=,iv:PoGi45Rj7LboIpgicvr11brBAAe3P/rSFBTQ4zCHAR8=,tag:U4AHc9O3KOxjEJ6vdhrtHA==,type:str]
    oidcGrafanaAuthUrl: ENC[AES256_GCM,data:pUnMAOtDYGsVbalX1c//E1EcK/C91l240V8I86+Y/LdWt062QOFzu29qr2WaRw==,iv:AMdKPjCkdl+gxm/Z5Vh+451ev1CZ5Y/BZeE/QmLE/Qs=,tag:Lwuxg4qG/zTDn9z9YNd6nw==,type:str]
    oidcGrafanaSignoutUrl: ENC[AES256_GCM,data:ZICS+ezFJIBWG2xZR5ftGaF5PKaMn+mF+XYtIvgjxKmLHnfFna1c5mBbbVd0,iv:9wsaicx3FhAjkrhbdjjGj3A95qHUxn0qpV2hugXRUJo=,tag:vWZ7WCQmVGumPt8i6Gl7SA==,type:str]
    oidcGrafanaTokenUrl: ENC[AES256_GCM,data:A6pNRJH5zFgBnY40cccjwmbYLDcrpmpniDqQ1qUqJxDJSfn9hTxRm1RE,iv:v15MbpUN/t8ueJ9x9zxsHAT+bpI4bil3u9ZJjENLsuE=,tag:0xFdJItbiCndhtBb1eVlow==,type:str]
    oidcGrafanaUserinfoUrl: ENC[AES256_GCM,data:neVdXvBN/8HINWzoeTHdKK6M7FzQz9FTRoEEb9dbOJuzXoGEJhAoZ7WW6HFq,iv:erx44fAppp57JEObYhteBy8ur/CIIBBPjOR+yi9+x2A=,tag:6+HPw2Wwnx9RY8HuXp6NIQ==,type:str]
    smtpAlertmanagerFrom: ENC[AES256_GCM,data:6DXhH426qL3IMhNjiqv3d8nTXFTQ,iv:lZ1EjeFGxy3utbny7unhmNR3NDQ9/MEXkQMLqEfpJMg=,tag:cqo2ntDkbNWJHPA1mBrReA==,type:str]
    smtpAlertmanagerSmarthost: ENC[AES256_GCM,data:i2ab5V0jIOPooSwj/R5WAEq9aQ==,iv:p9Z8eycRx3px7hSu9P0NusDsADL9UyfrQDmtDGukXlw=,tag:2FQgQciIqbS/T/1Ccwq+Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-22T13:28:27Z"
    mac: ENC[AES256_GCM,data:DtPiXCxJmiP9ACe+uzUdmiGiuFZwM0+fVhW9iNOGkwEuQFIvdg1z6G9OdCNAj3WHW2m/R1TeKL6LDf0MYzrLQ/ZpjB11fFYHZtwJo6wzbBkfdGLFlYtHBNOTm04VMfF2wzQ+kxcSK+oXEv8b227kKRDMTrHX7GDtnN55B994pn0=,iv:B2v1U8IeyfUXhSlsPrVnSmCb6x/W9TVquSFRnCBPq+8=,tag:UuzwyWF4A2bRPGreYzdYnA==,type:str]
    pgp:
        - created_at: "2023-07-22T13:28:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3ARAAjTLMwcBSGkTJHKzo1NGgS2JhSy6iI2AuWU5mUyIGuCLP
            CM806vZW3WZ7gY3/tQcYGZTpCUCFSMKIbnMPM0iPIr5DIhlpSAgvd8dpwBT0+Wme
            drDURGJvUP7Ruxt6nFWAj2m8yKDJKDxstqCPmmOTackIU4KllxGk1kZHRFnrF7sO
            2mL1L1GpwQPHHjHlKypduwMn7fObSKTWbTRf1PkvVIw9xX52abiGRmJzt8tG0Wek
            zv5RpFhyl2/PXcBsi772N8nUGaggs39d1nA8ywmIAW9E2q8v52QcTEAVyDPdlQsq
            9MjfvpJNVxZjEaHH+5Djr6gFnSOlx34lRPwUVi+igwpx6BuqR0h1bpz1GmXWuFzh
            i8UJy17ezw9V6blkdAPPh/ErtE8ekvXPARPup1IsaN4PUSGo9/UUV9cE9SZ5higq
            xSy0LXTOZ9ldu1tujDewnDisxTJ/9kHg/pYw37qSZ1jCxJpLhmVDgBwLEBFdeq/O
            AoJNt7RGx78kJVNjp7RnW0JA9IqPYI2q8TllR9nJK7OJuBuepyZceZ/32U2RGEiV
            92C2Ur2KEHiKKtiBiIk+wN5Rt4GYkSgGpcIMxyNoCD18N5wvL1ShUks2guARYTDR
            6ifdQQthORannD+eBUnFLHh3nOIaqlRvQWFRmzCFtXg2XY9FoVb3oRewsc1pbQ3S
            XAFiwVC3bb9OWcn8OM6nLafPXcmiwRHGCzpPwymhHCj8BTLNTG2BpzlPxP0Yla6J
            9Z5kOPo0bl35aDIspkNOdbyyiBAeIXFpcyzO9Tc41fp2a3JeneTGCBmrpvEy
            =VrXP
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
