---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitea
  namespace: gitea
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgresql
  namespace: gitea
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: postgresql
