apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: gitea
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:Y/xJfnvKGt6I6GNR8xaCCkE=,iv:B/qoFlpPUoyqukS/OGGa6OQ91mX5ITIINTnVMcNQ+cg=,tag:HvLGerlvqbHXtEvGfiym2w==,type:str]
  password: ENC[AES256_GCM,data:DqmvVoEqjZiSwA/DPROmw6I=,iv:LIynT1GasaVjKai7bxFjFIDgBgrNVxV1OpIozLS+lRY=,tag:7hj1D/Z1YbSGLHwEGfVLGQ==,type:str]
  passwordEncoded: ENC[AES256_GCM,data:W7zcELkIAj9PR4jfK9NeawCPomf/B4EW,iv:oafw8Hgl3A1Gl864GhyFpKohJ/nbDPAgVEgS+KryN/I=,tag:VQV5Ql0qZRXhNfbDb0bbxA==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT1cxT2Y5a1B4cUpBYTIy
        LzF2QnJOSVVHUS9VRTRyVmJXN3M2WnM1YlE4CmZ4aUxJdDZmS3V2anp0NGhFTHBU
        ckhqTDhSbFBsc0cxdnF3enU4WDhqY00KLS0tIDVMbnBOUHNFSUc0VldoUElHbVdn
        NUxKdUVoRFJCRGJPd1IyT0tXVlFVVkUKIeiO5kyyyknncGzDCQdtTfCnxmthChjJ
        e/QHFkMKNk1GL2jFyqKb/nuHpmdKllabvdLwPwTVes8zcUabIdjPWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T08:51:46Z"
  mac: ENC[AES256_GCM,data:5ZJklq1eyIQ26nzGdrh+ZQIdcmqO+RqYcmTSKlGTAKQx4sepX3sKiP5v3CIbGQ5knQJTTlHgQ4kmuhKMdiZiIEPMhWuNizp25dLamin6ggKMelwKTm5ltP0W3UfPJi3RKVbuQcpev4/Bea1PqfWsOWe/NJgrBGnu5VO+pbZgF9M=,iv:yRV5uEmdMWk5Rnu4q39QAKjp4fEx+DP1U7b7pX2FXWY=,tag:pM6JSnKFwy5bNntpnwi1dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
