---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kustomize-controller
  namespace: flux
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kustomize-controller
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: helm-controler
  namespace: flux
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helm-controller
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: source-controller
  namespace: flux
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: source-controller
  updatePolicy:
    updateMode: "Off"
