apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: base-metrics-server
spec:
  interval: 1h
  path: ./kustomize/base/metrics-server/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube
  validation: client
