---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nextcloud2
  namespace: flux
spec:
  interval: 1h
  url: oci://ghcr.io/nextcloud/helm/nextcloud
  ref:
    tag: 8.5.1
