---
image:
  repository: nextcloud
  tag: 33.0.0-apache
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    haproxy-ingress.github.io/config-backend: |
      acl url_discovery path /.well-known/caldav /.well-known/carddav
      http-request redirect location /remote.php/dav/ code 301 if url_discovery
  tls:
    - secretName: nextcloud-tls
      hosts:
        - ${hostname}
nextcloud:
  host: ${hostname}
  extraEnv:
    - name: OVERWRITEPROTOCOL
      value: https
    - name: TRUSTED_PROXIES
      value: 127.0.0.1 10.0.0.0/8
    - name: FORWARDED_FOR_HEADERS
      value: HTTP_X_FORWARDED_FOR
  mail:
    enabled: true
    fromAddress: ${mailfrom}
    domain: ${maildomain}
    smtp:
      host: ${smtphost}
      secure: ssl
      port: 465
      authtype: LOGIN
      name: ${smtpusername}
      password: ${smtppassword}
  strategy:
    type: Recreate
    rollingUpdate: null
cronjob:
  enabled: true
persistence:
  enabled: true
  annotations:
    volume.kubernetes.io/selected-node: ${nodename}
  storageClass: hdd
startupProbe:
  enabled: true
  failureThreshold: 360
nodeSelector:
  kubernetes.io/hostname: ${nodename}
internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: postgresql-rw.nextcloud2.svc.cluster.local
  existingSecret:
    enabled: true
    secretName: postgresql-app
    usernameKey: username
    passwordKey: password
    databaseKey: dbname
externalRedis:
  enabled: true
  host: valkey.nextcloud2.svc.cluster.local
collabora:
  enabled: true
  collabora:
    extra_params: --o:ssl.enable=false --o:ssl.termination=true
  ingress:
    enabled: true
    className: haproxy
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      haproxy-ingress.github.io/config-backend: |
        acl bad1 path_beg /cool/getMetrics
        http-request deny if bad1
        acl bad2 path_beg /cool/adminws
        http-request deny if bad2
        acl bad3 path_beg /browser/dist/admin/admin.html
        http-request deny if bad3
    hosts:
      - host: ${collabora_hostname}
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: nextcloud-office-tls
        hosts:
         - ${collabora_hostname}
  nodeSelector:
    kubernetes.io/hostname: ${nodename}
