---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentik-server
  namespace: authentik
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/component: server
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentik-worker
  namespace: authentik
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/component: worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgresql
  namespace: authentik
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: postgresql
