---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: postgresql
  namespace: authentik
spec:
  affinity:
    nodeSelector:
      kubernetes.io/hostname: ${nodename}
  inheritedMetadata:
    annotations:
      volume.kubernetes.io/selected-node: ${nodename}
      k8up.io/backupcommand: sh -c 'PGDATABASE="authentik" pg_dump --clean'
      k8up.io/file-extension: .sql
  instances: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 256m
      memory: 256Mi
  storage:
    size: 5Gi
    storageClass: ssd
  bootstrap:
    initdb:
      database: authentik
