---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: postgresql
  namespace: authentik
spec:
  affinity:
    nodeSelector:
      kubernetes.io/hostname: ${nodename}
  inheritedMetadata:
    annotations:
      volume.kubernetes.io/selected-node: ${nodename}
      k8up.io/backupcommand: sh -c 'pg_dumpall -U postgres --clean'
      k8up.io/file-extension: .sql
  instances: 1
  storage:
    size: 5Gi
    storageClass: ssd
  bootstrap:
    initdb:
      database: authentik
  monitoring:
    enablePodMonitor: true
  enablePDB: false
