apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: authentik
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:EhUJg3LHqsXXSy385sihC4o=,iv:CkmqjSzxyWTLMgDNhZfloosDJN2PimCs9SQGUyqSXUg=,tag:15KcBCYwn+o1vgr/PgMZYw==,type:str]
  password: ENC[AES256_GCM,data:d6xA9R2gkKhuw2NDyUwcPjI=,iv:d66LtuM0kCHGESYMjR+uOLqiekiJ7pWESE1KuTsCPUs=,tag:CS90JZ0BCa+9g/Qfqs02Kg==,type:str]
  passwordEncoded: ENC[AES256_GCM,data:V6pPMHul9WWjaVS66zdtG+/PNJeJ2BXH,iv:BZOWQ3hBdD37Q76qpiYsQP/0QJ0OxdZUYJSEvHr9cFw=,tag:3neblNegKKIkXnXHdtactQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOHlVNlVzcVlJTExRQ3Fk
        enp2V0sxSitSQ1d3OU1OeU45VXlrcEl1VWw0ClFNeU1mamMzb0E0SnVqS0x0WXh4
        NVNGNlZ3Z3U0RFFNRDd3NndOUm5TY2cKLS0tIGtRbTJwM3Y5QnRWVmhBYlBPM3NJ
        bGlyVlZFU2pOd0c3dm9NSFZJRkUrQ28KSEo7l9OnPlKY61fPTCKBayWdgfQzMxt3
        OLglUhH7qhme7AKY7918ujICQutLqzYAKqtpN/OxjgU+0Xo9E0VHVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-18T07:25:04Z"
  mac: ENC[AES256_GCM,data:w9yntfAU5PjZhNh2l8on4iACBrhVRXFg69xHxS3wdnH4qSAU6W9uq7zsnydk/YcAcxW93ApL0//imclS2cKUUATwOYtcwnD0IAkHktTESXzp0ksXcZcabaLraTz+fAA5k7ZBBkf7RgsdqXTG1R1lX0K63qxUuWfpCp6AmFTR4WE=,iv:B6UBDkfVq6L+zGE2nw5D1I+nsbmeIFQCFSzKqCO6fpU=,tag:HKll3iny/U6OzgI0Za+MvA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
