deployments:
  - path: namespace
  - path: helm
  - barrier: true
    waitReadinessObjects:
      - kind: CustomResourceDefinition
        name: ciliumnetworkpolicies.cilium.io
  - path: networkpolicies
