---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux
spec:
  chart:
    spec:
      chart: cloudnative-pg
      interval: 1h
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      version: 0.25.0
  dependsOn:
    - name: prometheus
  interval: 1h
  releaseName: cloudnative-pg
  storageNamespace: cloudnative-pg
  targetNamespace: cloudnative-pg
  valuesFrom:
    - kind: ConfigMap
      name: cloudnative-pg
