---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudnative-pg
  namespace: flux
data:
  values.yaml: |
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
