---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: storage-local
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: deploy/chart/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: storage-local
      interval: 1h
  releaseName: storage-local
  targetNamespace: storage
  storageNamespace: storage
  values:
    storageClass:
      create: false
    storageClassConfigs:
      ssd:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /var/mnt/ssd
      hdd:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /var/mnt/hdd
    nodePathMap: []
    configmap:
      name: local-path-config
      setup: |-
        #!/bin/sh
        set -eu
        echo "Creating $VOL_DIR"
        mkdir -m 0777 -p "$VOL_DIR"
      teardown: |-
        #!/bin/sh
        set -eu
        ARCHIVED_DIR="$(dirname $VOL_DIR)/archived-$(basename $VOL_DIR)"
        echo "Renaming $VOL_DIR to $ARCHIVED_DIR"
        mv "$VOL_DIR" "$ARCHIVED_DIR"
