apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium-wrapper
spec:
  interval: 1h
  releaseName: cilium-wrapper
  chart:
    spec:
      chart: charts/helmrelease-wrapper
      sourceRef:
        kind: GitRepository
        name: kube
      interval: 1h
  values:
    name: cilium
    configKey: cilium
    spec:
      interval: 1h
      releaseName: cilium
      targetNamespace: kube-system
      chart:
        spec:
          chart: cilium
          version: v1.13.0
          sourceRef:
            kind: HelmRepository
            name: cilium
          interval: 1h
    template:
      ipam:
        mode: kubernetes
      kubeProxyReplacement: strict
      k8sServiceHost: "{ var:apiAddress }"
      k8sServicePort: "{ var:apiPort }"
      operator:
        replicas: 1
      securityContext:
        privileged: true
      hubble:
        relay:
          enabled: true
    defaults:
      apiPort: 6443
  valuesFrom:
    - kind: Secret
      name: config
      valuesKey: config
      targetPath: config
