apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: victoria-metrics
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:cQdELkBFWAUil8McoQJL1Vc=,iv:RqaMzGtStyTWb0eUqZcHuOff77IJx6qLbAmhm5EpP30=,tag:EgN9ODkbMCww7z5reZlObw==,type:str]
  password: ENC[AES256_GCM,data:ryx5PVDBJBSAkD/rV0fVKJM=,iv:xegOkBce7UIBn6eykT/+u7rgex4okVDyiHJQ76xASCI=,tag:BzTbRjHjm2l5t0oVx8j3kw==,type:str]
  passwordEncoded: ENC[AES256_GCM,data:tMlzzEue8Rc6lHSFTU5DEqszkciOEy9b,iv:cmxHlcoMc116QNSjoaZlHiszTYXp6n4AjuMZOYtqrzc=,tag:FNKZaz6nPBGe0XxYPK59kQ==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV0JJVDBoS2hzelV0cXNx
        ZVVrcXZpRDlmREVnYTZhODJBdU1wMm9RUndZCjZTRlRWdDJRSmhwYXdqZjB1aGxw
        VEY0UEJ5QkxlczljdUFiTHFqSWwvck0KLS0tIE9sZ3V0WTEwMS9QVFo3MWJic0Qz
        eE1ONlY5R25KTFhkNVBFSm85WjFnR3MKlQul3n+NFPOuhbj009ai7iU+KfQUecPP
        YHeeQpANsY5hsrM51yTzt9/3e1YBNtFfHLXDT+04zjX/4cz6vUchTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T08:04:58Z"
  mac: ENC[AES256_GCM,data:xLMalSFIMC/Z3r2WgDa2BJCRtqUivhXqg9KILaxs5Yt+RmPgeF61WH3GUyuTnjSW3bQsO4RwCgbaqUqpjjc/vhrVl37Y2QzjQjELs4pbY5iZyq6duo2d/wP4F9aXu/doTXwxLnm1wG3y2hAnRrHHRWaaNqMUI9hQMoguEk3ePeQ=,iv:yhRavKyRKLiAQiA95wpyeep93cylmIOp87Meu4DmPww=,tag:yN1o+ORHVq7e/1Mu9i56xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
