apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: victoria-metrics
spec:
  disableSelfServiceScrape: true
  remoteWrite:
  - url: "http://vmsingle-vmsingle.victoria-metrics.svc.cluster.local:8429/api/v1/write"
    inlineUrlRelabelConfig:
    - action: labeldrop
      regex: "^storage-period$"
  - url: "http://vmsingle-vmsingle-long.victoria-metrics.svc.cluster.local:8429/api/v1/write"
    inlineUrlRelabelConfig:
    - action: keep
      sourceLabels: [storage-period]
      regex: long
    - action: labeldrop
      regex: "^storage-period$"
  selectAllByDefault: true
