helmChart:
  repo: https://prometheus-community.github.io/helm-charts
  chartVersion: 31.0.1
  chartName: prometheus-operator-crds
  releaseName: prometheus-operator-crds
  namespace: monitoring
  skipPrePull: true
