apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: coredns
  namespace: observability
spec:
  jobLabel: kubernetes.io/name
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      kubernetes.io/name: CoreDNS
  endpoints:
    - port: metrics
