apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics
  namespace: observability
spec:
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
      - kube-state-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - port: http
