apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: node-exporter
  namespace: observability
spec:
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
      - node-exporter
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
  podMetricsEndpoints:
    - port: metrics
      relabelConfigs:
        - sourceLabels:
            - "__meta_kubernetes_pod_node_name"
          action: replace
          targetLabel: node
