---
controller:
  ingressClassResource:
    enabled: true
    default: true
    controllerClass: haproxy
  kind: DaemonSet
  config:
    use-proxy-protocol: "true"
  extraArgs:
    watch-ingress-without-class: "true"
  service:
{% if 'ip' in config.base.ingress %}
    type: LoadBalancer
    loadBalancerClass: io.cilium/l2-announcer
    annotations:
      lbipam.cilium.io/ips: {{ config.base.ingress.ip }}
{% endif %}
    httpPorts:
      - port: 8080
        targetPort: http
    httpsPorts:
      - port: 8443
        targetPort: https
  tcp:
    8081: "haproxy-ingress/haproxy-ingress:8080::PROXY-V2"
    8444: "haproxy-ingress/haproxy-ingress:8443::PROXY-V2"
  haproxy:
    enabled: true
  metrics:
    enabled: true
