apiVersion: v1
kind: Secret
metadata:
  name: meshcore-proxy
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:AoEZRXiH,iv:lNcDyh1JLVr5s+VL6YD61incVXj/HATVvDQdzXDCGMI=,tag:0ZBBo0ZPviWZQH3mwWcbXA==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYWZkNGlTbFh0OHFQM1RO
        TjJMdk9TSlB6SVRPK05nQ0dUTEhTL05zS2hRClBwTVU3VHFiU3RNT0hFckNaMnAv
        bXJLS1RLRXhidTE0WWViTExaTERtWVEKLS0tIGJPZDBrUDY2ZWdveXNNeHR2MUlx
        cWthbUhzZmw3RVN3QnRjT2Jhc0ZuamMKjG29lNF7ZLcfODfKeCWCX+GpLe50yWiK
        4wmXbU9stJD2oIFFcVKRImMU5SlOiYZqtFdI9itwd6ahfpo3XQo0WA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T18:33:19Z"
  mac: ENC[AES256_GCM,data:676W6OGZ+Q2Ofgfs0Ca3ZZPjbY8mVgZSv2EBPjonaSyWwdjD+Qvt4H/aKekoHi9j4NhPrhSnALtWObSU+aP8x9AoMN9D1v3Kw3DS6KxyuzJ3st5jep3TGKVx6eVBcy+H/ZP0Hb0SLO1M1o5F1P7jQVeZYRSpF0kxpn4vN11vq80=,iv:Z+U+bZXjctJOIiPFiNjf7Saqjv85aVLFwGBEgVAHeN8=,tag:SkSkXJJJpU27FFWf4dqHvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
