apiVersion: v1
kind: Secret
metadata:
  name: haproxy-ingress
  namespace: flux
type: Opaque
stringData:
  ip: ENC[AES256_GCM,data:mKPGHqsCPaOzEnw3nR0=,iv:SBQuEytE6VtYWSKgB9BJSwVDAasuNz5F/bxPDXL2L6s=,tag:JJ9/X0p8NPXTSAFS3qe8hw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Yk1qTTVqeC9yb3I1VTlL
        d0gvV29YZ096SENjNnZhbzlQQTJoUE50VGh3CjBkeFJEUXpqeFNVenY3SmdoNm5S
        ek4xYXlTQi8wT0NPc2RFUXhxbmdzWUEKLS0tIEdMcjhra1k0d29JMnViTHp1NFpE
        cXhXYVFtVm00bmFrdmxFZk5UN1JVYXMKs2mCahNm16ZHZ4NjrkB+oP2Aqc4GJVI7
        2GWNUzK8foW+L1ubEFfTJtSG5jkGHhIefiQvDb5bBlcwzFelT1io8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-21T09:21:37Z"
  mac: ENC[AES256_GCM,data:i1IJYY0NidgtnqUq1VnGXhFWZHdKJ5qPMznUwuf3lYS+WC3+dbv837wSvb3VK8eDXs5UhDz9vkFM+8u66boJgFTRsCpPKNqfUM1oQHSjlmVUAuP5xEx9AuBykrdCecJ1pnntuTE7D1MLiHH7ZhccFwKFSS+ZcSJDqodMWV7EgVQ=,iv:BMhtyuTTo/Pbq638JDL2PBgzfDqQ2WKvrs/IQSr7Tp8=,tag:BoCy8PR8CB5L7ViL0QKuUA==,type:str]
  version: 3.13.2
