apiVersion: v1
kind: Secret
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress
type: Opaque
stringData:
  ip: ENC[AES256_GCM,data:mKPGHqsCPaOzEnw3nR0=,iv:SBQuEytE6VtYWSKgB9BJSwVDAasuNz5F/bxPDXL2L6s=,tag:JJ9/X0p8NPXTSAFS3qe8hw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Yk1qTTVqeC9yb3I1VTlL
        d0gvV29YZ096SENjNnZhbzlQQTJoUE50VGh3CjBkeFJEUXpqeFNVenY3SmdoNm5S
        ek4xYXlTQi8wT0NPc2RFUXhxbmdzWUEKLS0tIEdMcjhra1k0d29JMnViTHp1NFpE
        cXhXYVFtVm00bmFrdmxFZk5UN1JVYXMKs2mCahNm16ZHZ4NjrkB+oP2Aqc4GJVI7
        2GWNUzK8foW+L1ubEFfTJtSG5jkGHhIefiQvDb5bBlcwzFelT1io8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-21T09:01:17Z"
  mac: ENC[AES256_GCM,data:E5nnkLrV9gafJWE6ufx1tSjvYTHDAJR+iFFW2GdDD16lLb6nAQFWzOxdwbwI84At6G2jkIbmXj4wosjuqsvGwVM+8uTsU1fRhzN5CxMsHTWqPDNM6U7YItehxur5NUozhjTNPK8cdGPYa7Rj4HheuQRPTOSKXaWpVCXpUH0dC/w=,iv:bgJVxoq/B5sbDu+QmZRPm1hEhGpZowtTYZweB7sheYM=,tag:yhqPIGnsDgYtShUY0vJWIw==,type:str]
  version: 3.13.2
