---
controller:
  ingressClassResource:
    enabled: true
    default: true
    controllerClass: haproxy
  kind: DaemonSet
  config:
    use-proxy-protocol: "true"
  extraArgs:
    watch-ingress-without-class: "true"
  service:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: ${ip}
    httpPorts:
      - port: 8080
        targetPort: http
        nodePort: 31080
    httpsPorts:
      - port: 8443
        targetPort: https
        nodePort: 31443
  haproxy:
    enabled: true
  metrics:
    enabled: true
