---
controller:
  ingressClassResource:
    enabled: true
    default: true
    controllerClass: haproxy
  kind: DaemonSet
  config:
    use-proxy-protocol: "true"
  extraArgs:
    watch-ingress-without-class: "true"
  service:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: ${ip}
    httpPorts:
      - port: 8080
        targetPort: http
    httpsPorts:
      - port: 8443
        targetPort: https
  tcp:
    8081: "haproxy-ingress/haproxy-ingress:8080::PROXY-V2"
    8444: "haproxy-ingress/haproxy-ingress:8443::PROXY-V2"
    2222: "gitea/git-ingress:22::PROXY-V2"
  haproxy:
    enabled: true
  metrics:
    enabled: true
