---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: flux
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoriametrics
    namespace: flux
  releaseName: victoriametrics
  targetNamespace: victoriametrics
  storageNamespace: victoriametrics
  valuesFrom:
    - kind: ConfigMap
      name: victoriametrics
    - kind: Secret
      name: victoriametrics
      valuesKey: nodename
      targetPath: server.nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: victoriametrics
      valuesKey: nodename
      targetPath: server.persistentVolume.annotations.volume\.kubernetes\.io/selected-node
