---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - ocirepository.yaml
  - helmrelease.yaml
  - resources.yaml
configMapGenerator:
- name: victoriametrics
  namespace: flux
  files:
  - values.yaml
generatorOptions:
  disableNameSuffixHash: true
