---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: home-assistant-victoria
  namespace: flux
  files:
  - victoria-values.yaml
resources:
  - secret.yaml
  - schedule.yaml
  - prometheusrules.yaml
  - service-auth.yaml
  - victoria-ocirepository.yaml
  - victoria-helmrelease.yaml
  - victoria-ingress.yaml
