---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: home-assistant
  updatePolicy:
    updateMode: "Off"
