---
server:
  retentionPeriod: 100y
  nodeSelector:
    kubernetes.io/hostname: ${nodename}
  persistentVolume:
    annotations:
      helm.sh/resource-policy: keep
      volume.kubernetes.io/selected-node: ${nodename}
    storageClassName: hdd
    size: 100Gi
