---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant-victoria
  namespace: flux
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: home-assistant-victoria
    namespace: flux
  releaseName: home-assistant-victoria
  targetNamespace: home-assistant
  storageNamespace: home-assistant
  valuesFrom:
    - kind: ConfigMap
      name: home-assistant-victoria
