---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: home-assistant-victoria
  namespace: flux
spec:
  interval: 1h
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-single
  ref:
    tag: 0.24.6
