---
server:
  retentionPeriod: 100y
  nodeSelector:
    kubernetes.io/hostname: ${nodename}
  persistentVolume:
    annotations:
      helm.sh/resource-policy: keep
      volume.kubernetes.io/selected-node: ${nodename}
    storageClassName: hdd
    size: 100Gi
  service:
    clusterIP:
  scrape:
    enabled: true
    config:
      global:
        scrape_interval: 60s
      scrape_configs:
      - job_name: home-assistant
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - home-assistant
        metrics_path: /api/prometheus
        relabel_configs:
        - action: keep
          source_labels:
          - __meta_kubernetes_service_label_app_kubernetes_io_instance
          regex: home-assistant
        - action: keep
          source_labels:
          - __meta_kubernetes_service_label_app_kubernetes_io_name
          regex: home-assistant
        - action: keep
          source_labels:
          - __meta_kubernetes_endpoint_port_name
          regex: http
        - source_labels:
          - __meta_kubernetes_endpoint_address_target_kind
          - __meta_kubernetes_endpoint_address_target_name
          separator: ;
          regex: Node;(.*)
          replacement: ${1}
          target_label: node
        - source_labels:
          - __meta_kubernetes_endpoint_address_target_kind
          - __meta_kubernetes_endpoint_address_target_name
          separator: ;
          regex: Pod;(.*)
          replacement: ${1}
          target_label: pod
        - source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container
        - source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - source_labels:
          - __meta_kubernetes_service_name
          target_label: service
        - source_labels:
          - __meta_kubernetes_service_name
          target_label: job
          replacement: ${1}
        - target_label: endpoint
          replacement: http
        metric_relabel_configs:
        - action: keep
          source_labels:
          - domain
          separator: ;
          regex: sensor
