---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  endpoints:
  - path: /api/prometheus
    port: http
    metricRelabelConfigs:
    - source_labels: [entity]
      target_label: storage_period
      replacement: long
      if:
      - '{__name__="hass_sensor_state", entity="sensor.electricity_failures"}'
      - '{__name__="hass_sensor_energy_kwh", entity="sensor.energy_consumed_tariff_1"}'
      - '{__name__="hass_sensor_energy_kwh", entity="sensor.energy_consumed_tariff_2"}'
      - '{__name__="hass_sensor_gas_mu0xb3", entity="sensor.gas_consumed"}'
      - '{__name__="hass_sensor_state", entity="sensor.long_electricity_failures"}'
      - '{__name__="hass_sensor_duration_h", entity="sensor.opentherm_ketel_draaitijd_van_de_centrale_verwarmingspomp"}'
      - '{__name__="hass_sensor_duration_h", entity="sensor.opentherm_ketel_hot_water_burner_running_time"}'
      - '{__name__="hass_sensor_duration_h", entity="sensor.opentherm_ketel_hot_water_pump_running_time"}'
      - '{__name__="hass_sensor_duration_h", entity="sensor.opentherm_ketel_looptijd_brander"}'
      - '{__name__="hass_sensor_pressure_bar", entity="sensor.opentherm_ketel_waterdruk_centrale_verwarming"}'
      - '{__name__="hass_sensor_temperature_celsius", entity="sensor.opentherm_ketel_centrale_verwarming_1_watertemperatuur"}'
      - '{__name__="hass_sensor_temperature_celsius", entity="sensor.opentherm_ketel_maximale_bovengrens_voor_warmwater_instelpunt"}'
      - '{__name__="hass_sensor_temperature_celsius", entity="sensor.opentherm_ketel_maximale_instelpunt_centrale_verwarming"}'
      - '{__name__="hass_sensor_temperature_celsius", entity="sensor.opentherm_ketel_maximale_ondergrens_centrale_verwarmings_instelpunt"}'
      - '{__name__="hass_sensor_temperature_celsius", entity="sensor.opentherm_ketel_maximale_ondergrens_voor_warmwater_instelpunt"}'
      - '{__name__="hass_sensor_temperature_celsius", entity="sensor.opentherm_ketel_regel_instelpunt_1"}'
      - '{__name__="hass_sensor_temperature_celsius", entity="sensor.opentherm_ketel_temperatuur_retourwater"}'
      - '{__name__="hass_sensor_temperature_celsius", entity="sensor.opentherm_ketel_uitlaattemperatuur"}'
      - '{__name__="hass_sensor_temperature_celsius", entity="sensor.opentherm_ketel_warmwater_1_temperatuur"}'
      - '{__name__="hass_sensor_unit_percent", entity="sensor.opentherm_ketel_maximaal_relatief_modulatieniveau"}'
      - '{__name__="hass_sensor_unit_percent", entity="sensor.opentherm_ketel_minimaal_modulatieniveau"}'
      - '{__name__="hass_sensor_unit_percent", entity="sensor.opentherm_ketel_relatief_modulatieniveau"}'
      - '{__name__="hass_sensor_unit_starts", entity="sensor.opentherm_ketel_burner_start_count"}'
      - '{__name__="hass_sensor_unit_starts", entity="sensor.opentherm_ketel_central_heating_pump_start_count"}'
      - '{__name__="hass_sensor_unit_starts", entity="sensor.opentherm_ketel_hot_water_burner_start_count"}'
      - '{__name__="hass_sensor_unit_starts", entity="sensor.opentherm_ketel_hot_water_pump_start_count"}'
      - '{__name__="hass_sensor_volume_flow_rate_l_per_min", entity="sensor.opentherm_ketel_hot_water_flow_rate"}'
  namespaceSelector:
    matchNames:
      - home-assistant
  selector:
    matchLabels:
      app.kubernetes.io/instance: home-assistant
      app.kubernetes.io/name: home-assistant
