---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8up
  namespace: k8up
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8up
  updatePolicy:
    updateMode: "Off"
