apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  ingress:
  # Ingress
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": ingress
    toPorts:
    - ports:
      - port: "9090"
        protocol: TCP
  # Grafana
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: grafana
    toPorts:
    - ports:
      - port: "9090"
        protocol: TCP
  egress:
  # The world
  - toEntities:
    - all
