---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: k8up
      version: 4.8.3
      sourceRef:
        kind: HelmRepository
        name: k8up
      interval: 1h
  releaseName: k8up
  targetNamespace: k8up
  storageNamespace: k8up
  dependsOn:
    - name: prometheus
  valuesFrom:
    - kind: ConfigMap
      name: k8up
