---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8up-resources
  namespace: flux
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m
  path: ./manifests/k8up/resources
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
    - name: cluster
