---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8up
  namespace: flux
data:
  values.yaml: |
    timezone: Europe/Amsterdam
    metrics:
      service:
        annotations:
          prometheus.io/port: "8080"
          prometheus.io/scrape: "true"
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
      grafanaDashboard:
        enabled: true
        additionalLabels:
          grafana_dashboard: "1"
