---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-pushgateway
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: prometheus-pushgateway
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-pushgateway
      interval: 1h
  releaseName: prometheus-pushgateway
  targetNamespace: prometheus-pushgateway
  storageNamespace: prometheus-pushgateway
  dependsOn:
    - name: prometheus
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-pushgateway
