---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-pushgateway
  namespace: flux
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
