---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-pushgateway
  namespace: flux
data:
  values.yaml: |
    serviceMonitor:
      enabled: true
      namespace: prometheus-pushgateway
      interval: 60s
