---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: recommender
  namespace: unpoller
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unpoller
  updatePolicy:
    updateMode: "Off"
