apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - letsencrypt.yaml
  - letsencrypt-staging.yaml
  - selfsigned.yaml
replacements:
  - source:
      kind: Secret
      version: v1
      name: clusterissuers
      fieldPath: stringData.[admin.email]
    targets:
      - select:
          kind: ClusterIssuer
        reject:
          - kind: ClusterIssuer
            name: selfsigned
        fieldPaths:
          - spec.acme.email
