apiVersion: v1
kind: Secret
metadata:
    name: clusterissuers
type: Opaque
stringData:
    admin.email: ENC[AES256_GCM,data:MZAp2I5lPaSnlIpYnjVoert1mA==,iv:ySaRi97fchi2As4pPsaGn/NuBH22BHsPDaWBxbdCmEU=,tag:bydQpNN/nRDkL5HZ3EvP7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-28T11:13:08Z"
    mac: ENC[AES256_GCM,data:b4t7r7B6r9i/No4yw+iazF22sAD0oc7bwf6e9um25w5B2qnNqv57zLdgKP25KRAfiETT2XurnZwdBSy4hbwwNXTRRHBJzp5E3EOBRoaDpvYkdyzt4uu/FhGp3TIpvhdxwGYGrrfkmzrloJwXDhLqM2n4YPBxsS6P81ZcDy5ANXA=,iv:I+bkHYYvWy+LY2N5Hn8tgwrQgwJf0X6ELyudgCGBJaA=,tag:woR5gN4iTU7No8uyELYszw==,type:str]
    pgp:
        - created_at: "2023-04-28T11:13:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3AQ/+K5XulXWUimO8lEREMCd8AJBFSRNqMytNrqwkXPe1eGB/
            7KHjMeO72b0eRlqvmYflJ2kzj2DiOLOd1X8ieAw8m9hNHBNwlp9sw1907FKEre03
            MMC7Y03puyK+2p/h6Bl6ga1RkRunTSnVkLS0iNFJtqk0KXcY+409q4Nxt6GtwtpO
            MjMfroanyCbDAU//w4QExJXxuUkepCaq/uzdMbbp3tOFixl7XBXPWoTfT6JVnGbu
            M6Jvk70LflsfqRZeJVwymrb7BGBgk4WhKveLPL/drphlwc3onM/xdCNNTBgB/opY
            gc/twjfQmXriYvE+tfILQgwJj4rpt+8HiK+rBODxCD13XD+QeoFmyjvOhwPz3bUH
            MzlJhlZkLaTmpHEDqNpP23GgtOwBAPWkoLB1hfy1k+JoNpbUKQddOkbnTqmqG90M
            dzLgECt4FsZr+MQKy3gwq+o+1Usz2T4/Hv9mF9DjQULNLP0Vn7rSOgEXuMgPDOc7
            qmr+nZRx6MLwgwbwaLFa0M4LAwxYdDj+sD3QGNBnGxx8U7J7gy0XWCB5TkByMYpt
            Q+VZUnIZznO+XyQNloA6nP0prexToew5HchniBM6igmcxaHJE2qPbKjDUIu4SHT7
            z/bxhc0C/rP27TkAZbBqYkg+LfiFaq9GvcivtR64FksfRtx+TP4ORBu55IKG9uLS
            XgEtWpdWF9LoKPsw4k7kZv4cP4ImeFZ3n197QxCWdrZA0gtxZL5kb6QfLl94k5k2
            i0r9r4+RZz57tqyyhY5ZddmLNa0AXn2h3N5n+VdiHu8gneM4w78lABdw1Bu1OnM=
            =IotW
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
