apiVersion: v1
kind: Secret
metadata:
    name: clusterissuers
    namespace: kube-system
type: Opaque
stringData:
    admin.email: ENC[AES256_GCM,data:TYwf5x3B0wNJ7tDiExEYdm//FA==,iv:jaeyqItuLd0dK3pPZ7e4+R+dqp+LdCHjVyDMLFFwUQU=,tag:QHkbH04HnvUbLairdJtpaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-28T11:15:25Z"
    mac: ENC[AES256_GCM,data:CmxO3YTgtOOK5md1+RTtCMuCz2QL4GxLOg3zPNtU2Havfb8NB701kE5ryHdHW6igCYrcLU6AhEjgUmqMpu6DX0mqaEDEBwRiizPsz6RLHaN5o94JmZ0bWQD3SdD9py6DX6J/ba0vAp9/rjQbsSbohGi+l0JymPrLIZ3DNdi34ss=,iv:cpf9EWYcCOvq45HopG/y47NQLz01CzYNcrBbeTZVRR8=,tag:pxk+cedNBB1a4MKmCflZZQ==,type:str]
    pgp:
        - created_at: "2023-04-28T11:15:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10wx5U3gEw3AQ//ZnVQyJEDMDjorOuV7Sj9P3Mzj88dm+xpwWlQnSLduia1
            7LAlA0VPie/pBYAKpngCvJngD6XJ/wiZSoDX1WKhm+JSHXBsHRfUCVE/4JtRcJAB
            KBdMcUaLbaX6r3PcjCCQDRaPEgwpYqWVqoqSeXsRLWASll17FT2WS4QaV/v2T/U4
            Rp+QJk60JdCQQD4raanuQR83Wnk/eLaX0zIlGTw25DAOJtj8S3O/82NNN+bqO+UN
            evxY6DiLEvhSKugbHZ/WE0tMj/WUV1yz8c7XMBuU05PwLkQXVBZck0jDVVQWnQZU
            cJt8145pJGdyam8nDGtgR6D2MakowmL1armhFqNLqSBUSFqFQtCNq9g4TLSThYXL
            SWaCoAXT+cpRbN2OoEh1R5714TRVRcvHygKFc7JDHgngqWoPzVQSSqozPd9qJowX
            OwDx7hChKi2XVCWIJff3cl8hcQuiF+rural8aIx3wMSkP9J/3IohuYBKQDiMgIoC
            nWONrKJ3tu8CsLN5JvbZmCL0hh9Hb5/1gilvxfWPoGthiLJgZe5XrmiMT7KKfsUu
            7k2jtBiK9TxOub4yn+nHHIUQGcmaRjLJ7OqCBhG/BuAkTNqSeBsy35kD5/gIJJeI
            rEFT8lyt41YPe46aztcSpxEgEG6MufMNR73LnHtBQy6G0N4pqqvVvqbr8J5LQG7S
            XAETT1Yq10a+P+wXHczvwGf+njBSqqXzabD1gopb3/blMAUJTd8agsE39Jccnhrv
            byl8tn84zya710AfxiUoz1EQderrMJXUYaadl/6cCZupDtjAI2/h9ARm7lxr
            =V2Rx
            -----END PGP MESSAGE-----
          fp: 8F6A472C7E7E4D37F0CF3EA912DD0773984838FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
