name: Check Helm chart versions

on: pull_request

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.2.1

    - name: Run chart-testing
      run: ct lint --all --remote=origin --target-branch=main
