name: Test Helm charts

on: push

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Install and run helm unittest plugin
      run: |
        helm plugin install https://github.com/quintush/helm-unittest >/dev/null
        helm unittest --helm3 charts/cluster-issuers
        helm unittest --helm3 charts/helmrelease-wrapper

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.2.1

    - name: Run chart-testing
      run: ct lint --all --check-version-increment=false --remote=origin --target-branch=main
