name: Release new version

on:
  push:
    branches:
      - main

jobs:

  release:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: "0"

    - name: List changes
      id: changes
      run: |
        git fetch --tags --force
        CHANGES="$(git log --reverse $(git describe --tags --abbrev=0)..${GITHUB_SHA} --pretty=format:'- %h %s')"
        CHANGES="${CHANGES//'%'/'%25'}"
        CHANGES="${CHANGES//$'\n'/'%0A'}"
        CHANGES="${CHANGES//$'\r'/'%0D'}"
        echo "::set-output name=changes::${CHANGES}"

    - name: Update version
      id: update-version
      uses: codacy/git-version@2.8.0
      with:
        prefix: "v"
        release-branch: main
        minor-identifier: /^feat(ure)?:/

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.update-version.outputs.version }}
        release_name: Release ${{ steps.update-version.outputs.version }}
        body: |
          Changes in this release:
          ${{ steps.changes.outputs.changes }}
        draft: false
        prerelease: false
