name: Template test

on: push

jobs:
  template-test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Test chart templates
      run: charts/template-test.sh
