apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${name}
  namespace: flux
spec:
  interval: 1h
  install:
    timeout: 50m
  releaseName: ${name}
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: cert-manager
    - name: ingress-nginx
  chart:
    spec:
      chart: gitea
      version: 10.2.0
      sourceRef:
        kind: HelmRepository
        name: gitea-${name}
      interval: 1h
  targetNamespace: ${namespace}
  storageNamespace: ${namespace}
  values:
    ssh:
      type: NodePort
      port: 2222
      nodePort: 30022
      externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${issuer}
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: ${hostname}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ${name}-tls
          hosts:
            - ${hostname}
    gitea:
      admin:
        username: ${adminUsername}
        password: ${adminPassword}
        adminEmail: ${adminEmail}
      config:
        database:
          DB_TYPE: postgres
        session:
          PROVIDER: db
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: ${dbUsername}
            password: ${dbPassword}
