---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: vaultwarden
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
      interval: 1h
  releaseName: vaultwarden
  targetNamespace: vaultwarden
  storageNamespace: vaultwarden
  valuesFrom:
    - kind: ConfigMap
      name: vaultwarden
    - kind: Secret
      name: vaultwarden
      valuesKey: nodename
      targetPath: nodeSelector.kubernetes\.io/hostname
    - kind: Secret
      name: vaultwarden
      valuesKey: nodename
      targetPath: persistence.annotations.volume\.kubernetes\.io/selected-node
    - kind: Secret
      name: vaultwarden
      valuesKey: url
      targetPath: vaultwarden.domain
    - kind: Secret
      name: vaultwarden
      valuesKey: hostname
      targetPath: ingress.host
    - kind: Secret
      name: vaultwarden
      valuesKey: hostname
      targetPath: ingress.tls[0].hosts[0]
