---
vaultwarden:
  domain: ${domain}
  allowSignups: false
ingress:
  enabled: true
  host: ${hostname}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  tls:
    - secretName: vaultwarden-tls
      hosts:
        - ${hostname}
persistence:
  enabled: true
  storageClass: ssd
  annotations:
    helm.sh/resource-policy: keep
    volume.kubernetes.io/selected-node: ${nodename}
image:
  repository: ghcr.io/dani-garcia/vaultwarden
  tag: "1.34.3"
nodeSelector:
  kubernetes.io/hostname: ${nodename}
strategy:
  type: Recreate
  rollingUpdate: null
securityContext:
  readOnlyRootFilesystem: true
